import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {JSDOM} from 'jsdom';
import {shell} from '../shell.mjs';
import {definitions} from '../model.mjs';
import {integrations} from '../integrations.mjs';
import {defaultSettings} from '../business-settings.mjs';
const code=readFileSync(new URL('../client.js',import.meta.url),'utf8');
async function settled(check){for(let i=0;i<100;i++){if(check())return;await new Promise(r=>setTimeout(r,5));}assert.fail('UI did not settle');}
function mount(path,extra={}){
 const calls=[],rows={contacts:[{id:'c',name:'Demo person',email:'demo@example.test'}],projects:[],...extra},dom=new JSDOM(shell,{url:'https://example.workers.dev'+path,runScripts:'outside-only'}),w=dom.window;
 w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');this.dispatchEvent(new w.Event('close'))};
 w.fetch=async(url,options={})=>{const route=url.slice('/api/admin/'.length),kind=route.split('/')[0];calls.push({route,...options});let data=route==='integrations'?{integrations}:route==='business-settings'?(rows['business-settings']||{data:structuredClone(defaultSettings),version:0}):route==='meta'?{definitions,email:'admin@example.test'}:rows[kind]||[];if(options.method==='POST'&&route.endsWith('/convert')){const lead=rows.leads.find(r=>r.id===route.split('/')[1]);const project={...lead,id:'converted',contactId:'c',status:'Inquiry'};rows.projects.push(project);lead.projectId=project.id;lead.archived=false;lead.lifecycle='Active';rows.contacts[0]={...rows.contacts[0],name:lead.name,email:lead.email,partnerName:lead.partnerName};data={id:project.id,contactId:'c'};}else if(options.method==='POST'){data={...JSON.parse(options.body).data,id:'new',version:1};rows[kind]=[...(rows[kind]||[]),data];}return {ok:true,json:async()=>data};};w.eval(code);return {dom,w,calls};
}
test('grouped navigation preserves routes and expands current tools',async()=>{
 const {w,dom}=mount('/admin/templates/');await settled(()=>w.document.querySelector('h1')?.textContent==='Email Templates');assert.equal(w.document.querySelectorAll('.primary-workspace-links a').length,6);assert.equal(w.document.querySelectorAll('#navigation a').length,18);const groups=[...w.document.querySelectorAll('.workspace-nav-group')];assert(groups.find(g=>g.textContent.includes('Email Templates')).open);assert(!groups.find(g=>g.textContent.includes('Automations')).open);assert(w.document.querySelector('[aria-label="Workspace breadcrumbs"]').textContent.includes('Email Templates'));assert.equal(w.document.querySelectorAll('.mobile-workspace-nav optgroup').length,3);dom.window.close();
});
test('project composer scopes context, escapes previews and saves only drafts',async()=>{
 const {w,dom,calls}=mount('/admin/projects/',{projects:[{id:'p',name:'DEMO event',contactId:'c',eventType:'Wedding',status:'Proposal',venue:'Demo venue'}],templates:[{id:'t',name:'Follow-up',subject:'For {{clientFirstName}}',body:'At {{venue}} on {{eventDate}}. Balance {{balance}}. <img src=x onerror=alert(1)>'}],invoices:[{id:'i',projectId:'other',amountCents:900000}],messages:[{id:'other',name:'Other project secret',projectId:'other',body:'PRIVATE OTHER'}]});
 await settled(()=>w.document.querySelector('td strong'));const click=name=>[...w.document.querySelectorAll('button')].find(b=>b.textContent===name).click();click('View');await settled(()=>w.document.querySelector('.project-view[open]'));assert.equal(w.document.querySelector('section[aria-label=Overview]').hidden,false);assert(!w.document.querySelector('.project-view').textContent.includes('PRIVATE OTHER'));click('Draft message');await settled(()=>w.document.querySelector('.message-composer[open]'));
 const template=w.document.querySelector('[aria-label="Email template"]');template.value='t';template.dispatchEvent(new w.Event('change'));const body=w.document.querySelector('[aria-label="Draft body"]');assert(body.value.includes('Demo venue'));assert(body.value.includes('[Confirm event date]'));assert(body.value.includes('[Confirm balance]'));assert(!body.value.includes('$9,000'));click('Preview draft');assert.equal(w.document.querySelectorAll('.message-preview img').length,0);assert(w.document.querySelector('.message-preview').textContent.includes('<img'));
 w.document.querySelector('.message-composer form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await settled(()=>calls.some(c=>c.method==='POST'));const saves=calls.filter(c=>c.method==='POST');assert.equal(saves.length,1);assert.equal(saves[0].route,'messages');assert.equal(JSON.parse(saves[0].body).data.status,'Draft');assert.equal(JSON.parse(saves[0].body).data.projectId,'p');await settled(()=>w.document.querySelector('.project-view[open]'));assert(w.document.querySelector('section[aria-label=Communications]').textContent.includes('For Demo'));dom.window.close();
});
test('project editor preserves stored statuses and advanced values',async()=>{
 const {w,dom}=mount('/admin/projects/',{projects:[{id:'p',name:'Demo project',contactId:'c',eventType:'Wedding',status:'Pre-Event',venue:'Venue',priceCents:10000,tags:'keep'}]});await settled(()=>w.document.querySelector('td strong'));[...w.document.querySelectorAll('button')].find(b=>b.textContent==='Edit').click();await settled(()=>w.document.querySelector('#editor[open]'));assert.equal(w.document.querySelector('[name=status]').value,'Pre-Event');assert.equal([...w.document.querySelector('[name=status]').options].find(o=>o.value==='Pre-Event').textContent,'Pre-event planning');assert.equal(w.document.querySelector('[name=priceCents]').value,'100');assert(w.document.querySelector('[name=tags]').closest('details'));dom.window.close();
});

test('simple Lead entry derives its name, retains advanced data, and conversion opens the Project',async()=>{
 const {w,dom,calls}=mount('/admin/leads/',{leads:[]});await settled(()=>w.document.querySelector('h1')?.textContent==='Leads');const click=name=>[...w.document.querySelectorAll('button')].find(b=>b.textContent===name).click();click('New Lead');await settled(()=>w.document.querySelector('#editor[open]'));
 const form=w.document.querySelector('#record-form'),set=(name,value)=>{const input=form.querySelector('[name='+name+']');input.value=value;input.dispatchEvent(new w.Event('input'));};assert.equal(form.querySelector('[name=name]').type,'hidden');assert(form.querySelector('[name=serviceIds]').closest('details'));assert(!form.querySelector('[name=firstName]').closest('details'));set('firstName','DEMO Jamie');set('lastName','Workflow');set('partnerName','DEMO Taylor');set('email','demo-workflow@example.test');set('eventType','Wedding');set('eventDate','2027-10-05');set('venue','DEMO venue');set('leadSource','DEMO manual review');set('notes','DEMO only; no sending');form.querySelector('[name=demo]').checked=true;form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await settled(()=>w.document.querySelector('td strong'));
 const payload=JSON.parse(calls.find(c=>c.method==='POST').body).data;assert.equal(payload.name,'DEMO Jamie Workflow');assert.equal(payload.status,'New');assert.equal(payload.demo,true);assert.equal(w.document.querySelector('[aria-label="Show Leads"]').selectedOptions[0].textContent,'Active Leads');click('Open Lead');await settled(()=>w.document.querySelector('.lead-view[open]'));w.document.querySelector('.lead-view .primary').click();await settled(()=>w.document.querySelector('.project-view[open]'));assert.equal(w.location.pathname,'/admin/projects/');assert.equal(new URLSearchParams(w.location.search).get('record'),'converted');assert.equal(calls.filter(c=>c.route.endsWith('/convert')).length,1);const project=w.document.querySelector('.project-view');assert(project.textContent.includes('DEMO Jamie Workflow'));assert(project.textContent.includes('DEMO Taylor'));assert(project.textContent.includes('DEMO venue'));assert(project.querySelector('section[aria-label=Notes]').textContent.includes('DEMO only; no sending'));assert.equal(project.querySelector('.project-next-step .primary').textContent,'Create Proposal');dom.window.close();
});
test('linked Lead opens its existing Project without another conversion',async()=>{
 const {w,dom,calls}=mount('/admin/leads/?record=l',{leads:[{id:'l',name:'TEST retained Lead',projectId:'p',archived:true}],projects:[{id:'p',name:'TEST existing Project',contactId:'c',eventType:'Wedding',status:'Inquiry'}],proposals:[{id:'proposal',projectId:'p',name:'TEST proposal',status:'Draft'}]});await settled(()=>w.document.querySelector('.lead-view[open]'));w.document.querySelector('.lead-view .primary').click();await settled(()=>w.document.querySelector('.project-view[open]'));assert.equal(calls.filter(c=>c.method==='POST').length,0);assert.equal(w.document.querySelector('.project-next-step .primary').textContent,'Preview as Client');dom.window.close();
});

test('Project appointment composer carries identity and converts Eastern time correctly',async()=>{
 const types=['Consultation','Client Meeting','Production Meeting','Other'].map((name,i)=>({id:'t'+i,name,durationMinutes:30,bufferMinutes:0})),{w,dom,calls}=mount('/admin/projects/?record=p',{projects:[{id:'p',name:'DEMO schedule',contactId:'c',eventType:'Wedding',status:'Inquiry',demo:true}], 'appointment-types':[...types,{id:'legacy',name:'Client Meeting',durationMinutes:60}]});await settled(()=>w.document.querySelector('.project-view[open]'));[...w.document.querySelectorAll('button')].find(b=>b.textContent==='Schedule Appointment').click();await settled(()=>w.document.querySelector('.appointment-composer[open]'));const composer=w.document.querySelector('.appointment-composer');assert.equal(composer.querySelector('[aria-label=Client]'),null);assert.equal(composer.querySelectorAll('[aria-label="Appointment type"] option').length,4);composer.querySelector('[aria-label="Date & time (Eastern)"]').value='2027-01-05T10:00';composer.querySelector('textarea').value='DEMO consultation notes';composer.querySelector('form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await settled(()=>calls.some(c=>c.route==='appointments'&&c.method==='POST'));const data=JSON.parse(calls.find(c=>c.route==='appointments'&&c.method==='POST').body).data;assert.equal(data.projectId,'p');assert.equal(data.contactId,'c');assert.equal(data.startAt,'2027-01-05T15:00:00.000Z');assert.equal(data.endAt,'2027-01-05T15:30:00.000Z');assert.equal(data.notes,'DEMO consultation notes');dom.window.close();
});

test('advanced Builder adds Sweet Sixteen as separately selectable source services',async()=>{
 const {w,dom,calls}=mount('/admin/proposals/',{packages:[{id:'current-sweet-sixteen',name:'Sweet Sixteen',serviceIds:['hb-1-13','hb-1-17'],priceCents:345000,active:true}],services:[{id:'hb-1-13',name:'Photography Essentials (6hr)',priceCents:165000},{id:'hb-1-17',name:'Feature Film & Edit Services 6hrs',priceCents:180000}]});await settled(()=>w.document.querySelector('h1')?.textContent==='Proposals');[...w.document.querySelectorAll('button')].find(b=>b.textContent==='New Proposal').click();await settled(()=>w.document.querySelector('[aria-label="Add catalog item"]'));const picker=w.document.querySelector('[aria-label="Add catalog item"]');assert(!picker.textContent.includes('$3,450'));picker.value='packages:current-sweet-sixteen';[...w.document.querySelectorAll('button')].find(b=>b.textContent==='Add selected item').click();const lines=[...w.document.querySelectorAll('.proposal-line')];assert.equal(lines.length,2);assert.deepEqual(lines.map(l=>Number(l.querySelector('[data-part=price]').value)),[1650,1800]);assert.deepEqual(lines.map(l=>l.dataset.sourceKind),['services','services']);assert(lines.every(l=>l.querySelector('[data-part=selectionGroupOptional]').checked));assert.notEqual(lines[0].querySelector('[data-part=selectionGroup]').value,lines[1].querySelector('[data-part=selectionGroup]').value);dom.window.close();
});

test('Project Documents keeps Proposal, Contract, Invoice and portal reachable in context',async()=>{
 const {w,dom}=mount('/admin/projects/?record=p&section=Documents',{projects:[{id:'p',name:'DEMO documents',contactId:'c',eventType:'Wedding',status:'Inquiry',demo:true}]});await settled(()=>w.document.querySelector('.project-view[open]'));const docs=w.document.querySelector('section[aria-label=Documents]');assert.equal(docs.hidden,false);assert.deepEqual([...docs.querySelectorAll('.actions button')].map(b=>b.textContent),['Proposal','Contract','Invoice']);assert(docs.textContent.includes('Contracts'));assert(docs.textContent.includes('Invoices / Payments'));assert(w.document.querySelector('.project-view > .actions').textContent.includes('Client Portal access'));[...docs.querySelectorAll('button')].find(b=>b.textContent==='Contract').click();await settled(()=>w.document.querySelector('#editor[open]'));assert.equal(w.document.querySelector('[name=projectId]').value,'p');assert(w.document.querySelector('[name=body]').value.includes('not a legal agreement'));assert.equal(w.document.querySelector('[name=status]').value,'Draft');dom.window.close();
});
test('invoice picker avoids accidental duplicates, supports separate S16 choices and updates visible math',async()=>{
 const {w,dom}=mount('/admin/invoices/',{projects:[{id:'p',name:'DEMO project'}],packages:[{id:'current-wedding',name:'Feature Film',priceCents:315000,active:true},{id:'current-sweet-sixteen',name:'S16',serviceIds:['photo','film'],active:true}],services:[{id:'photo',name:'6hr Photography',priceCents:165000},{id:'film',name:'6hr Film',priceCents:180000},{id:'addon',name:'Extra hour',catalogCategory:'Weddings / Add-ons',priceCents:10000}]});await settled(()=>w.document.querySelector('h1')?.textContent==='Invoices / Payments');const click=t=>[...w.document.querySelectorAll('button')].find(b=>b.textContent===t).click();click('New Invoice draft');await settled(()=>w.document.querySelector('.invoice-summary'));const picker=w.document.querySelector('[aria-label="Active package"]');assert(picker.textContent.includes('6hr Photography'));assert(!picker.textContent.includes('$3,450'));picker.value='packages:current-wedding';click('Add Package');click('Add Package');assert.equal(w.document.querySelectorAll('.proposal-line').length,1);const set=(name,value)=>{const i=w.document.querySelector('[name='+name+']');i.value=value;i.dispatchEvent(new w.Event('input',{bubbles:true}));};set('discountMode','percentage');set('discountPercent','10');set('taxMode','percentage');set('taxRate','8.25');assert.equal(w.document.querySelector('[name=amountCents]').value,'3068.89');assert(w.document.querySelector('.invoice-summary').textContent.includes('(10%)'));click('Remove item');assert.equal(w.document.querySelectorAll('.proposal-line').length,0);dom.window.close();
});
test('Use Template opens editable project email with recipient and per-draft signature controls',async()=>{
 const {w,dom,calls}=mount('/admin/templates/',{projects:[{id:'p',name:'DEMO mail',contactId:'c',eventType:'Wedding'}],templates:[{id:'t',name:'Follow up',subject:'Hello {{clientFirstName}}',body:'DEMO message',templateType:'email'}]});await settled(()=>w.document.querySelector('td strong'));[...w.document.querySelectorAll('button')].find(b=>b.textContent==='View').click();await settled(()=>w.document.querySelector('#record-view[open]'));[...w.document.querySelectorAll('button')].find(b=>b.textContent==='Use Template').click();await settled(()=>w.document.querySelector('[aria-label="Create email draft"][open]'));[...w.document.querySelectorAll('button')].find(b=>b.textContent==='Continue').click();await settled(()=>w.document.querySelector('.message-composer[open]'));assert.equal(w.document.querySelector('[aria-label=To]').value,'demo@example.test');assert.equal(w.document.querySelector('[aria-label="Draft subject"]').value,'Hello Demo');w.document.querySelector('[aria-label="Draft signature"]').value='Frank\nGioLina';w.document.querySelector('[aria-label="Include signature"]').checked=true;[...w.document.querySelectorAll('button')].find(b=>b.textContent==='Preview draft').click();assert(w.document.querySelector('.message-preview').textContent.includes('Frank'));w.document.querySelector('.message-composer form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await settled(()=>calls.some(c=>c.route==='messages'&&c.method==='POST'));const payload=JSON.parse(calls.find(c=>c.route==='messages'&&c.method==='POST').body).data;assert.equal(payload.signature,'Frank\nGioLina');assert.equal(payload.status,'Draft');dom.window.close();
});

test('saved default signature is inserted once and can be disabled for one draft',async()=>{
 const {w,dom,calls}=mount('/admin/projects/?record=p&compose=1',{projects:[{id:'p',name:'DEMO signature',contactId:'c',eventType:'Wedding'}],'business-settings':{version:2,data:{...defaultSettings,signature:'Frank\nGioLina Films',includeSignature:true}}});await settled(()=>w.document.querySelector('.message-composer[open]'));assert.equal(w.document.querySelector('[aria-label="Draft signature"]').value,'Frank\nGioLina Films');assert.equal(w.document.querySelector('[aria-label="Include signature"]').checked,true);w.document.querySelector('[aria-label="Draft subject"]').value='DEMO signature draft';w.document.querySelector('[aria-label="Draft body"]').value='Hello';w.document.querySelector('[aria-label="Include signature"]').checked=false;[...w.document.querySelectorAll('button')].find(b=>b.textContent==='Preview draft').click();assert(!w.document.querySelector('.message-preview').textContent.includes('Frank'));w.document.querySelector('.message-composer form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await settled(()=>calls.some(c=>c.route==='messages'&&c.method==='POST'));const data=JSON.parse(calls.find(c=>c.route==='messages'&&c.method==='POST').body).data;assert.equal(data.includeSignature,false);assert.equal(data.signature,'Frank\nGioLina Films');assert.equal(calls.filter(c=>c.route==='business-settings'&&c.method==='PUT').length,0);dom.window.close();
});
test('settings keeps mandatory alert preferences on and exposes reusable template/planning links',async()=>{
 const {w,dom}=mount('/admin/settings/');await settled(()=>w.document.querySelector('.settings-form'));for(const label of ['Security','Delivery failure alerts']){const check=w.document.querySelector('[aria-label="'+label+'"]');assert(check.checked);assert(check.disabled);}assert(w.document.querySelector('a[href="/admin/templates/?type=contract"]'));assert(w.document.querySelector('a[href="/admin/appointment-types/"]'));assert(w.document.querySelector('a[href="/admin/availability/"]'));dom.window.close();
});

test('invoice editor starts with business fields and discloses only relevant pricing inputs',async()=>{
 const {w,dom}=mount('/admin/invoices/');await settled(()=>w.document.querySelector('h1')?.textContent==='Invoices / Payments');[...w.document.querySelectorAll('button')].find(b=>b.textContent==='New Invoice draft').click();await settled(()=>w.document.querySelector('.invoice-summary'));const fields=w.document.querySelector('#fields');assert.equal(fields.querySelector('input,select').name,'name');assert(fields.querySelector('[name=depositCents]').closest('details'));assert(!fields.querySelector('[name=depositCents]').closest('details').open);assert(fields.querySelector('[name=discountPercent]').parentElement.hidden);assert(fields.querySelector('[name=taxRate]').parentElement.hidden);fields.querySelector('[name=discountMode]').value='percentage';fields.querySelector('[name=discountMode]').dispatchEvent(new w.Event('change',{bubbles:true}));assert(!fields.querySelector('[name=discountPercent]').parentElement.hidden);assert(fields.querySelector('[name=discountCents]').parentElement.hidden);dom.window.close();
});

test('saving a contextual invoice review link returns to Project without opening another draft',async()=>{
 const {w,dom,calls}=mount('/admin/projects/?record=p&invoice=1',{projects:[{id:'p',name:'DEMO invoice project',contactId:'c',eventType:'Wedding',status:'Inquiry'}]});await settled(()=>w.document.querySelector('.invoice-summary'));w.document.querySelector('[name=amountCents]').value='100';w.document.querySelector('#record-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await settled(()=>w.document.querySelector('.project-view[open]'));assert.equal(new URLSearchParams(w.location.search).has('invoice'),false);assert.equal(w.document.querySelector('#editor[open]'),null);assert.equal(calls.filter(c=>c.method==='POST'&&c.route==='invoices').length,1);dom.window.close();
});

test('Project operations derives only associated balances, meeting and tasks; task cancel returns to Project',async()=>{
 const {w,dom}=mount('/admin/projects/?record=p',{projects:[{id:'p',name:'DEMO Operations',contactId:'c',eventType:'Wedding',status:'Planning',demo:true}],invoices:[{id:'i',projectId:'p',amountCents:100000,paidCents:25000,installments:[{label:'Deposit',dueAt:'2026-01-01',amountCents:25000},{label:'Final',dueAt:'2027-01-01',amountCents:75000}]},{id:'other',projectId:'other',amountCents:900000}],tasks:[{id:'t',name:'Call DEMO client',projectId:'p',status:'TO DO',priority:'High',dueAt:'2026-10-01'},{id:'secret',name:'Other task secret',projectId:'other'}],appointments:[{id:'a',projectId:'p',status:'Scheduled',startAt:'2030-01-01T15:00:00Z',endAt:'2030-01-01T15:30:00Z'}]});await settled(()=>w.document.querySelector('.project-operations'));const text=w.document.querySelector('.project-operations').textContent;assert(text.includes('$1,000.00'));assert(text.includes('$750.00'));assert(text.includes('2027-01-01'));assert(!text.includes('$9,000'));assert(!w.document.querySelector('.project-view').textContent.includes('Other task secret'));
 [...w.document.querySelectorAll('button')].find(b=>b.textContent==='Add Task').click();await settled(()=>w.document.querySelector('#editor[open]'));assert.equal(w.document.querySelector('[name=projectId]').value,'p');assert(w.document.querySelector('[name=projectId]').disabled);assert.equal(w.document.querySelector('[name=status]').value,'TO DO');w.document.querySelector('#cancel-editor').click();await settled(()=>w.document.querySelector('.project-view[open]'));dom.window.close();
});

test('Tasks navigation, task status controls and open filter exclude completed records',async()=>{
 const {w,dom,calls}=mount('/admin/tasks/',{tasks:[{id:'done',name:'Completed task',status:'DONE',completed:true},{id:'open',name:'Open task',status:'IN PROGRESS',priority:'High'}]});await settled(()=>w.document.querySelector('h1')?.textContent==='Tasks');assert(w.document.querySelector('#navigation a[href="/admin/tasks/"]'));assert(!w.document.querySelector('tbody').textContent.includes('Completed task'));assert(w.document.querySelector('tbody').textContent.includes('Open task'));[...w.document.querySelectorAll('button')].find(b=>b.textContent==='New Task').click();await settled(()=>w.document.querySelector('#editor[open]'));w.document.querySelector('[name=name]').value='Call client';w.document.querySelector('[name=status]').value='IN PROGRESS';w.document.querySelector('[name=priority]').value='High';w.document.querySelector('#record-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await settled(()=>calls.some(c=>c.route==='tasks'&&c.method==='POST'));const data=JSON.parse(calls.find(c=>c.route==='tasks'&&c.method==='POST').body).data;assert.equal(data.status,'IN PROGRESS');assert.equal(data.priority,'High');dom.window.close();
});

test('Finder joins Project and Contact context without reading private message bodies',async()=>{
 const {w,dom,calls}=mount('/admin/finder/',{contacts:[{id:'c',name:'DEMO Jamie',partnerName:'DEMO Taylor',email:'demo@example.test'}],projects:[{id:'p',name:'Wedding Project',contactId:'c',venue:'Demo Garden'}],invoices:[{id:'i',name:'Draft invoice',projectId:'p',invoiceNumber:'GL-DRAFT-i'}],contracts:[{id:'ct',name:'Demo contract',projectId:'p'}]});await settled(()=>w.document.querySelector('[aria-label="Find business records"]'));const input=w.document.querySelector('[aria-label="Find business records"]');input.value='taylor';input.dispatchEvent(new w.Event('input'));assert(w.document.querySelector('main').textContent.includes('Draft invoice'));assert(w.document.querySelector('main').textContent.includes('Demo contract'));assert(w.document.querySelector('a[href="/admin/invoices/?record=i"]'));assert(!calls.some(c=>c.route==='messages'));input.value='unknown';input.dispatchEvent(new w.Event('input'));assert(w.document.querySelector('main').textContent.includes('No matching records'));dom.window.close();
});

test('Dashboard excludes terminal proposals and completed tasks while preserving real empty states',async()=>{
 const {w,dom}=mount('/admin/',{proposals:[{id:'a',name:'Accepted terminal',status:'Accepted (test only)'},{id:'e',name:'Expired terminal',status:'Expired'},{id:'d',name:'DEMO Review draft',status:'Ready for review',totalCents:315000}],tasks:[{id:'t',name:'DEMO Overdue call',status:'TO DO',dueAt:'2020-01-01'},{id:'done',name:'Hidden done task',status:'DONE',completed:true}]});await settled(()=>w.document.querySelector('h1')?.textContent==='Your workspace');const text=w.document.querySelector('main').textContent;assert(text.includes('DEMO Review draft'));assert(!text.includes('Accepted terminal'));assert(!text.includes('Expired terminal'));assert(!text.includes('Hidden done task'));assert(text.includes('OVERDUE'));dom.window.close();
});

test('Tasks DONE filter remains usable and Project invoice Save returns to Documents',async()=>{
 const {w,dom,calls}=mount('/admin/projects/?record=p&section=Documents',{projects:[{id:'p',name:'DEMO Save context',contactId:'c',eventType:'Wedding',status:'Inquiry'}]});await settled(()=>w.document.querySelector('section[aria-label=Documents]'));const docs=w.document.querySelector('section[aria-label=Documents]');[...docs.querySelectorAll('button')].find(b=>b.textContent==='Invoice').click();await settled(()=>w.document.querySelector('#editor[open]'));w.document.querySelector('[name=amountCents]').value='100';w.document.querySelector('#record-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await settled(()=>calls.some(c=>c.route==='invoices'&&c.method==='POST'));await settled(()=>w.document.querySelector('.project-view[open]'));assert.equal(w.document.querySelector('section[aria-label=Documents]').hidden,false);assert.equal(w.document.querySelector('#editor').hasAttribute('open'),false);dom.window.close();
 const second=mount('/admin/tasks/',{tasks:[{id:'done',name:'Completed task',status:'DONE',completed:true},{id:'open',name:'Open task',status:'TO DO'}]});await settled(()=>second.w.document.querySelector('[aria-label="Show Tasks"]'));const filter=second.w.document.querySelector('[aria-label="Show Tasks"]');filter.value='DONE';filter.dispatchEvent(new second.w.Event('change'));assert(second.w.document.querySelector('tbody').textContent.includes('Completed task'));assert(!second.w.document.querySelector('tbody').textContent.includes('Open task'));second.dom.window.close();
});

test('Dashboard derives unpaid installments instead of requiring an invoice-level due date',async()=>{
 const {w,dom}=mount('/admin/',{invoices:[{id:'i',name:'DEMO Installments',projectId:'p',amountCents:100000,paidCents:25000,installments:[{label:'Paid deposit',dueAt:'2020-01-01',amountCents:25000},{label:'Final balance',dueAt:'2030-01-01',amountCents:75000}]}]});await settled(()=>w.document.querySelector('main').textContent.includes('Final balance'));const text=w.document.querySelector('main').textContent;assert(text.includes('$750.00'));assert(!text.includes('Paid deposit'));assert(w.document.querySelector('a[href="/admin/projects/?record=p"]'));dom.window.close();
});
