import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {JSDOM} from 'jsdom';
import {shell} from '../shell.mjs';
import {definitions} from '../model.mjs';
const code=readFileSync(new URL('../client.js',import.meta.url),'utf8');
async function settled(check){for(let i=0;i<100;i++){if(check())return;await new Promise(r=>setTimeout(r,5));}assert.fail('UI did not settle');}
function mount(path,extra={}){
 const calls=[],rows={contacts:[{id:'c',name:'Demo person',email:'demo@example.test'}],projects:[],...extra},dom=new JSDOM(shell,{url:'https://example.workers.dev'+path,runScripts:'outside-only'}),w=dom.window;
 w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');this.dispatchEvent(new w.Event('close'))};
 w.fetch=async(url,options={})=>{const route=url.slice('/api/admin/'.length),kind=route.split('/')[0];calls.push({route,...options});let data=route==='meta'?{definitions,email:'admin@example.test'}:rows[kind]||[];if(options.method==='POST'&&route.endsWith('/convert')){const lead=rows.leads.find(r=>r.id===route.split('/')[1]);const project={...lead,id:'converted',contactId:'c',status:'Inquiry'};rows.projects.push(project);lead.projectId=project.id;lead.archived=false;lead.lifecycle='Active';rows.contacts[0]={...rows.contacts[0],name:lead.name,email:lead.email,partnerName:lead.partnerName};data={id:project.id,contactId:'c'};}else if(options.method==='POST'){data={...JSON.parse(options.body).data,id:'new',version:1};rows[kind]=[...(rows[kind]||[]),data];}return {ok:true,json:async()=>data};};w.eval(code);return {dom,w,calls};
}
test('grouped navigation preserves routes and expands current tools',async()=>{
 const {w,dom}=mount('/admin/templates/');await settled(()=>w.document.querySelector('h1')?.textContent==='Email Templates');assert.equal(w.document.querySelectorAll('.primary-workspace-links a').length,5);assert.equal(w.document.querySelectorAll('#navigation a').length,16);const groups=[...w.document.querySelectorAll('.workspace-nav-group')];assert(groups.find(g=>g.textContent.includes('Email Templates')).open);assert(!groups.find(g=>g.textContent.includes('Automations')).open);assert(w.document.querySelector('[aria-label="Workspace breadcrumbs"]').textContent.includes('Email Templates'));assert.equal(w.document.querySelectorAll('.mobile-workspace-nav optgroup').length,3);dom.window.close();
});
test('project composer scopes context, escapes previews and saves only drafts',async()=>{
 const {w,dom,calls}=mount('/admin/projects/',{projects:[{id:'p',name:'DEMO event',contactId:'c',eventType:'Wedding',status:'Proposal',venue:'Demo venue'}],templates:[{id:'t',name:'Follow-up',subject:'For {{clientFirstName}}',body:'At {{venue}} on {{eventDate}}. Balance {{balance}}. <img src=x onerror=alert(1)>'}],invoices:[{id:'i',projectId:'other',amountCents:900000}],messages:[{id:'other',name:'Other project secret',projectId:'other',body:'PRIVATE OTHER'}]});
 await settled(()=>w.document.querySelector('td strong'));const click=name=>[...w.document.querySelectorAll('button')].find(b=>b.textContent===name).click();click('View');await settled(()=>w.document.querySelector('.project-view[open]'));assert.equal(w.document.querySelector('section[aria-label=Overview]').hidden,false);assert(!w.document.querySelector('.project-view').textContent.includes('PRIVATE OTHER'));click('Draft message');await settled(()=>w.document.querySelector('.message-composer[open]'));
 const template=w.document.querySelector('[aria-label="Email template"]');template.value='t';template.dispatchEvent(new w.Event('change'));const body=w.document.querySelector('[aria-label="Draft body"]');assert(body.value.includes('Demo venue'));assert(body.value.includes('[Confirm event date]'));assert(body.value.includes('[Confirm balance]'));assert(!body.value.includes('$9,000'));click('Preview draft');assert.equal(w.document.querySelectorAll('.message-preview img').length,0);assert(w.document.querySelector('.message-preview').textContent.includes('<img'));
 w.document.querySelector('.message-composer form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await settled(()=>calls.some(c=>c.method==='POST'));const saves=calls.filter(c=>c.method==='POST');assert.equal(saves.length,1);assert.equal(saves[0].route,'messages');assert.equal(JSON.parse(saves[0].body).data.status,'Draft');assert.equal(JSON.parse(saves[0].body).data.projectId,'p');await settled(()=>w.document.querySelector('.project-view[open]'));assert(w.document.querySelector('section[aria-label=Communications]').textContent.includes('For Demo'));dom.window.close();
});
test('project editor preserves stored statuses and advanced values',async()=>{
 const {w,dom}=mount('/admin/projects/',{projects:[{id:'p',name:'Demo project',contactId:'c',eventType:'Wedding',status:'Pre-Event',venue:'Venue',priceCents:10000,tags:'keep'}]});await settled(()=>w.document.querySelector('td strong'));[...w.document.querySelectorAll('button')].find(b=>b.textContent==='Edit').click();await settled(()=>w.document.querySelector('#editor[open]'));assert.equal(w.document.querySelector('[name=status]').value,'Pre-Event');assert.equal([...w.document.querySelector('[name=status]').options].find(o=>o.value==='Pre-Event').textContent,'Pre-event planning');assert.equal(w.document.querySelector('[name=priceCents]').value,'100');assert(w.document.querySelector('[name=tags]').closest('details'));dom.window.close();
});

test('simple Lead entry derives its name, retains advanced data, and conversion opens the Project',async()=>{
 const {w,dom,calls}=mount('/admin/leads/',{leads:[]});await settled(()=>w.document.querySelector('h1')?.textContent==='Leads');const click=name=>[...w.document.querySelectorAll('button')].find(b=>b.textContent===name).click();click('New Lead');await settled(()=>w.document.querySelector('#editor[open]'));
 const form=w.document.querySelector('#record-form'),set=(name,value)=>{const input=form.querySelector('[name='+name+']');input.value=value;input.dispatchEvent(new w.Event('input'));};assert.equal(form.querySelector('[name=name]').type,'hidden');assert(form.querySelector('[name=serviceIds]').closest('details'));assert(!form.querySelector('[name=firstName]').closest('details'));set('firstName','DEMO Jamie');set('lastName','Workflow');set('partnerName','DEMO Taylor');set('email','demo-workflow@example.test');set('eventType','Wedding');set('eventDate','2027-10-05');set('venue','DEMO venue');set('leadSource','DEMO manual review');set('notes','DEMO only; no sending');form.querySelector('[name=demo]').checked=true;form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await settled(()=>w.document.querySelector('td strong'));
 const payload=JSON.parse(calls.find(c=>c.method==='POST').body).data;assert.equal(payload.name,'DEMO Jamie Workflow');assert.equal(payload.status,'New');assert.equal(payload.demo,true);assert.equal(w.document.querySelector('[aria-label="Show Leads"]').selectedOptions[0].textContent,'Active Leads');click('Open Lead');await settled(()=>w.document.querySelector('.lead-view[open]'));w.document.querySelector('.lead-view .primary').click();await settled(()=>w.document.querySelector('.project-view[open]'));assert.equal(w.location.pathname,'/admin/projects/');assert.equal(new URLSearchParams(w.location.search).get('record'),'converted');assert.equal(calls.filter(c=>c.route.endsWith('/convert')).length,1);const project=w.document.querySelector('.project-view');assert(project.textContent.includes('DEMO Jamie Workflow'));assert(project.textContent.includes('DEMO Taylor'));assert(project.textContent.includes('DEMO venue'));assert(project.querySelector('section[aria-label=Notes]').textContent.includes('DEMO only; no sending'));assert.equal(project.querySelector('.project-next-step .primary').textContent,'Create Proposal');dom.window.close();
});
test('linked Lead opens its existing Project without another conversion',async()=>{
 const {w,dom,calls}=mount('/admin/leads/?record=l',{leads:[{id:'l',name:'TEST retained Lead',projectId:'p',archived:true}],projects:[{id:'p',name:'TEST existing Project',contactId:'c',eventType:'Wedding',status:'Inquiry'}],proposals:[{id:'proposal',projectId:'p',name:'TEST proposal',status:'Draft'}]});await settled(()=>w.document.querySelector('.lead-view[open]'));w.document.querySelector('.lead-view .primary').click();await settled(()=>w.document.querySelector('.project-view[open]'));assert.equal(calls.filter(c=>c.method==='POST').length,0);assert.equal(w.document.querySelector('.project-next-step .primary').textContent,'Preview as Client');dom.window.close();
});

test('Project appointment composer carries identity and converts Eastern time correctly',async()=>{
 const types=['Consultation','Client Meeting','Production Meeting','Other'].map((name,i)=>({id:'t'+i,name,durationMinutes:30,bufferMinutes:0})),{w,dom,calls}=mount('/admin/projects/?record=p',{projects:[{id:'p',name:'DEMO schedule',contactId:'c',eventType:'Wedding',status:'Inquiry',demo:true}], 'appointment-types':[...types,{id:'legacy',name:'Client Meeting',durationMinutes:60}]});await settled(()=>w.document.querySelector('.project-view[open]'));[...w.document.querySelectorAll('button')].find(b=>b.textContent==='Schedule Appointment').click();await settled(()=>w.document.querySelector('.appointment-composer[open]'));const composer=w.document.querySelector('.appointment-composer');assert.equal(composer.querySelector('[aria-label=Client]'),null);assert.equal(composer.querySelectorAll('select option').length,4);composer.querySelector('[aria-label="Date & time (Eastern)"]').value='2027-01-05T10:00';composer.querySelector('textarea').value='DEMO consultation notes';composer.querySelector('form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await settled(()=>calls.some(c=>c.route==='appointments'&&c.method==='POST'));const data=JSON.parse(calls.find(c=>c.route==='appointments'&&c.method==='POST').body).data;assert.equal(data.projectId,'p');assert.equal(data.contactId,'c');assert.equal(data.startAt,'2027-01-05T15:00:00.000Z');assert.equal(data.endAt,'2027-01-05T15:30:00.000Z');assert.equal(data.notes,'DEMO consultation notes');dom.window.close();
});

test('advanced Builder adds Sweet Sixteen as separately selectable source services',async()=>{
 const {w,dom,calls}=mount('/admin/proposals/',{packages:[{id:'current-sweet-sixteen',name:'Sweet Sixteen',serviceIds:['hb-1-13','hb-1-17'],priceCents:345000,active:true}],services:[{id:'hb-1-13',name:'Photography Essentials (6hr)',priceCents:165000},{id:'hb-1-17',name:'Feature Film & Edit Services 6hrs',priceCents:180000}]});await settled(()=>w.document.querySelector('h1')?.textContent==='Proposals');[...w.document.querySelectorAll('button')].find(b=>b.textContent==='New Proposal').click();await settled(()=>w.document.querySelector('[aria-label="Add catalog item"]'));const picker=w.document.querySelector('[aria-label="Add catalog item"]');assert(!picker.textContent.includes('$3,450'));picker.value='packages:current-sweet-sixteen';[...w.document.querySelectorAll('button')].find(b=>b.textContent==='Add selected item').click();const lines=[...w.document.querySelectorAll('.proposal-line')];assert.equal(lines.length,2);assert.deepEqual(lines.map(l=>Number(l.querySelector('[data-part=price]').value)),[1650,1800]);assert.deepEqual(lines.map(l=>l.dataset.sourceKind),['services','services']);assert(lines.every(l=>l.querySelector('[data-part=selectionGroupOptional]').checked));assert.notEqual(lines[0].querySelector('[data-part=selectionGroup]').value,lines[1].querySelector('[data-part=selectionGroup]').value);dom.window.close();
});
