import test from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import {hashPassword,verifyPassword,allowed,createDemoAuth} from '../demo-auth.mjs';
const secret=()=>randomBytes(24).toString('base64url');
test('local password hashing uses unique salts, verification and bounded inputs',async()=>{
 const password=secret(),a=await hashPassword(password),b=await hashPassword(password);assert.notEqual(a.salt,b.salt);assert.notEqual(a.hash,b.hash);assert(!JSON.stringify(a).includes(password));assert(await verifyPassword(password,a));assert(!await verifyPassword(secret(),a));await assert.rejects(hashPassword('short'));assert(!await verifyPassword('a'.repeat(1025),a));
});
test('DEMO sessions, CSRF, role boundaries, reset, disable and revocation fail closed',async()=>{
 let time=Date.now();const auth=await createDemoAuth({stage:'local-demo',origin:'https://localhost:9443',now:()=>time}),password=secret();const owner=await auth.createUser({email:'owner@example.test',password,role:'OWNER / ADMIN'}),staff=await auth.createUser({email:'staff@example.test',password}),client=await auth.createUser({email:'client@example.test',password,role:'CLIENT',realm:'client'});
 const login=()=>auth.login({email:owner.email,password});const o=await login(),s=await auth.login({email:staff.email,password,trusted:true});assert(o.cookie.includes('HttpOnly; Secure; SameSite=Strict'));assert(!o.cookie.includes('Domain='));assert(s.cookie.includes('Max-Age=604800'));assert.equal(auth.authorize(s.token,'documents').id,staff.id);assert.throws(()=>auth.authorize(s.token,'users'),/Permission/);assert.throws(()=>auth.authorize(o.token,'documents',{write:true,requestOrigin:'https://attacker.test',csrf:o.csrf}),/Invalid/);assert.throws(()=>auth.authorize(o.token,'documents',{write:true,requestOrigin:'https://localhost:9443',csrf:'wrong'}),/Invalid/);assert(auth.authorize(o.token,'documents',{write:true,requestOrigin:'https://localhost:9443',csrf:o.csrf}));
 await assert.rejects(auth.login({email:client.email,password,realm:'admin'}),/Unable/);const c=await auth.login({email:client.email,password,realm:'client'});assert.throws(()=>auth.authorize(c.token,'workspace'),/Session/);assert.equal(allowed('CLIENT','documents','client'),false);
 const staleReset=auth.requestReset(staff.email);assert.throws(()=>auth.setRole(o.token,owner.id,'STAFF'),/Invalid/);auth.disable(o.token,staff.id);assert.throws(()=>auth.authorize(s.token,'workspace'),/Session/);await assert.rejects(auth.login({email:staff.email,password}),/Unable/);auth.disable(o.token,staff.id,false);await assert.rejects(auth.reset(staleReset.token,secret()),/Reset/);const s2=await auth.login({email:staff.email,password});auth.revoke(o.token,staff.id);assert.throws(()=>auth.authorize(s2.token,'workspace'),/Session/);
 const reset=auth.requestReset(owner.email),next=secret();await auth.reset(reset.token,next);assert.throws(()=>auth.authorize(o.token,'workspace'),/Session/);await assert.rejects(auth.reset(reset.token,next),/Reset/);const fresh=await auth.login({email:owner.email,password:next});auth.logout(fresh.token);assert.throws(()=>auth.authorize(fresh.token,'workspace'),/Session/);const expired=await auth.login({email:owner.email,password:next});time+=3600001;assert.throws(()=>auth.authorize(expired.token,'workspace'),/Session/);const expReset=auth.requestReset(owner.email);time+=1800001;await assert.rejects(auth.reset(expReset.token,secret()),/Reset/);assert(!JSON.stringify(auth.audit()).includes(password));assert(!JSON.stringify(auth.audit()).includes(next));
});
test('local auth demo rejects deployment activation and rate-limits repeated failures',async()=>{
 await assert.rejects(createDemoAuth({stage:'preview',origin:'https://example.workers.dev'}),/local-only/);const auth=await createDemoAuth({stage:'local-demo',origin:'https://localhost'});for(let i=0;i<5;i++)await assert.rejects(auth.login({email:'unknown@example.test',password:secret()}),/Unable/);await assert.rejects(auth.login({email:'unknown@example.test',password:secret()}),/later/);assert.equal(allowed('STAFF','integrations'),false);assert.equal(allowed('OWNER / ADMIN','system-settings'),true);
});
