import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {generateKeyPair,SignJWT,createLocalJWKSet,exportJWK} from 'jose';
import {api} from '../api.mjs';
import {authenticate,verifyIdentity} from '../auth.mjs';
import {handlePrivate} from '../router.mjs';
import worker from '../../worker.js';
import {validate} from '../model.mjs';
import catalog from '../data/catalog.json' with {type:'json'};
class D1Adapter{
 constructor(){this.sqlite=new DatabaseSync(':memory:');this.sqlite.exec(readFileSync(new URL('../migrations/0001_foundation.sql',import.meta.url),'utf8'));}
 prepare(sql){const db=this.sqlite;let args=[];return {bind(...values){args=values;return this},async all(){return {results:db.prepare(sql).all(...args)}},async first(){return db.prepare(sql).get(...args)||null},run(){return db.prepare(sql).run(...args)}};}
 async batch(statements){this.sqlite.exec('BEGIN');try{const result=statements.map(s=>s.run());this.sqlite.exec('COMMIT');return result;}catch(e){this.sqlite.exec('ROLLBACK');throw e;}}
}
const user={email:'admin@example.test',organizationId:'giolina-preview',role:'admin'};
function fixture(){const env={CRM_DB:new D1Adapter()};async function call(path,method='GET',body,userOverride=user,headers={}){const response=await api(new Request('https://preview.example.workers.dev/api/admin/'+path,{method,headers:{Origin:'https://preview.example.workers.dev','Content-Type':'application/json','X-GioLina-Request':'admin',...headers},...(body?{body:JSON.stringify(body)}:{})}),env,userOverride,path);return {status:response.status,data:await response.json()};}return {call,env};}
test('catalog preserves prices, hours, missing prices and historical variants',()=>{assert.equal(catalog.length,47);assert.equal(new Set(catalog.map(r=>r.id)).size,47);for(const row of catalog)assert.deepEqual(validate('services',Object.fromEntries(Object.entries(row).filter(([k])=>k!=='id'))),{...Object.fromEntries(Object.entries(row).filter(([k])=>k!=='id')),active:true});assert.equal(catalog.find(r=>r.category==='Wedding 2026'&&r.conflictGroup==='wedding-feature').priceCents,315000);assert.equal(catalog.find(r=>r.category==='Sweet Sixteen 2024'&&r.conflictGroup==='overtime').priceCents,12500);assert.equal(catalog.filter(r=>r.category.startsWith('Saved')).length,25);assert(catalog.filter(r=>r.conflictGroup==='additional-cinematographer').some(r=>r.coverageHours===10&&r.priceCents===null));});
test('CRUD, optimistic edits, organization isolation, seed idempotency and lead conversion',async()=>{const {call,env}=fixture();assert.equal((await call('seed','POST',{})).status,201);assert.equal((await call('seed','POST',{})).status,200);assert.equal((await call('services')).data.length,47);const contact=(await call('contacts','POST',{data:{name:'Demo contact',email:'demo@example.test',demo:true}})).data;assert(contact.id);assert.equal((await call('contacts/'+contact.id,'PUT',{data:{...contact,id:undefined},version:contact.version})).status,400);const updated=await call('contacts/'+contact.id,'PUT',{data:{name:'Updated demo',email:'demo@example.test',demo:true},version:1});assert.equal(updated.data.version,2);assert.equal((await call('contacts/'+contact.id,'PUT',{data:{name:'Stale',email:'demo@example.test'},version:1})).status,409);assert.deepEqual((await call('contacts','GET',null,{...user,organizationId:'other'})).data,[]);const lead=(await call('leads','POST',{data:{name:'Demo inquiry',contactId:contact.id,eventType:'Wedding',status:'New Inquiry',demo:true}})).data;assert.equal((await call('leads/'+lead.id+'/convert','POST',{version:1})).status,201);assert.equal((await call('leads/'+lead.id+'/convert','POST',{version:1})).status,409);assert.equal((await call('projects')).data.length,1);assert.equal(env.CRM_DB.sqlite.prepare('SELECT COUNT(*) n FROM write_guards').get().n,0);assert((await call('activity')).data.length>=4);});
test('atomic appointment overlaps, buffers, cancellation, rescheduling and blocked dates',async()=>{const {call}=fixture();const contact=(await call('contacts','POST',{data:{name:'Demo',email:'demo@example.test'}})).data;const type=(await call('appointment-types','POST',{data:{name:'Demo consultation',durationMinutes:30,bufferMinutes:10}})).data;const data={name:'Demo meeting',contactId:contact.id,appointmentTypeId:type.id,startAt:'2026-11-05T15:00:00Z',endAt:'2026-11-05T15:30:00Z',status:'Scheduled'};const first=(await call('appointments','POST',{data})).data;assert(first.id);assert.equal((await call('appointments','POST',{data:{...data,startAt:'2026-11-05T15:35:00Z',endAt:'2026-11-05T16:05:00Z'}})).status,409);assert.equal((await call('appointments')).data.length,1);assert.equal((await call('appointments/'+first.id,'PUT',{data:{...data,status:'Cancelled'},version:1})).status,200);assert.equal((await call('appointments','POST',{data})).status,201);await call('availability','POST',{data:{name:'Demo blocked date',dayOfWeek:'Friday',startTime:'09:00',endTime:'17:00',blockedDate:'2026-11-06'}});assert.equal((await call('appointments','POST',{data:{...data,startAt:'2026-11-06T15:00:00Z',endAt:'2026-11-06T15:30:00Z'}})).status,409);});
test('validation and CSRF keep drafts safe',async()=>{const {call}=fixture();assert.equal((await call('contacts','POST',{data:{name:'Demo',email:'demo@example.test'}},user,{Origin:'https://evil.test'})).status,403);assert.throws(()=>validate('contacts',{name:'   ',email:'demo@example.test'}));assert.throws(()=>validate('leads',{name:'Bad date',contactId:'a',eventType:'Wedding',status:'Lead',eventDate:'2026-02-30'}));assert.throws(()=>validate('automations',{name:'Unsafe',enabled:true}));assert.throws(()=>validate('messages',{name:'Message',projectId:'p',status:'Sent'}));assert.throws(()=>validate('contracts',{name:'Sign',projectId:'p',status:'Signed'}));assert.throws(()=>validate('invoices',{name:'Pay',projectId:'p',status:'Paid'}));assert.equal((await call('projects','POST',{data:{name:'Unknown',contactId:'missing',eventType:'Wedding',status:'Lead'}})).status,400);});
test('JWT verifies signature, audience, issuer, expiry and exact administrator allowlist',async()=>{const {privateKey,publicKey}=await generateKeyPair('RS256');const jwk=await exportJWK(publicKey);jwk.kid='test';const keys=createLocalJWKSet({keys:[jwk]});const env={CRM_ACCESS_TEAM:'example.cloudflareaccess.com',CRM_ACCESS_AUD:'admin-audience',CRM_ADMIN_EMAILS:'admin@example.test'};async function token(email='admin@example.test',aud='admin-audience',expires='1h'){return new SignJWT({email}).setProtectedHeader({alg:'RS256',kid:'test'}).setIssuer('https://example.cloudflareaccess.com').setAudience(aud).setSubject('example-subject').setIssuedAt().setExpirationTime(expires).sign(privateKey)}assert.equal((await verifyIdentity(await token(),env,keys)).role,'admin');assert.equal(await verifyIdentity(await token('other@example.test'),env,keys),null);await assert.rejects(verifyIdentity(await token('admin@example.test','wrong'),env,keys));await assert.rejects(verifyIdentity(await token('admin@example.test','admin-audience','-1h'),env,keys));await assert.rejects(verifyIdentity((await token()).slice(0,-3)+'bad',env,keys));assert.equal(await authenticate(new Request('https://giolinafilms.com/admin/'),{...env,CRM_STAGE:'preview',CRM_ORIGIN:'https://example.workers.dev'}),null);});
test('all private resources fail closed; public site and non-GET behavior remain intact',async()=>{for(const path of ['/admin/','/admin/contacts/','/admin/app.js','/admin/app.css','/api/admin/meta','/api/admin/services','/portal/','/api/portal/projects']){const response=await handlePrivate(new Request('https://example.workers.dev'+path),{});assert([401,503].includes(response.status));assert.equal(response.headers.get('Cache-Control'),'no-store');const body=await response.text();assert(!body.includes('Imported 47'));assert(!body.includes('5-Hour Corporate'));assert(!body.includes('record-form'));}let called=0;const env={ASSETS:{async fetch(){called++;return new Response('public content')}}};const publicResponse=await worker.fetch(new Request('https://example.workers.dev/'),env);assert.equal(await publicResponse.text(),'public content');assert.equal(called,1);assert.equal((await worker.fetch(new Request('https://example.workers.dev/',{method:'POST'}),env)).status,405);assert.equal((await worker.fetch(new Request('https://example.workers.dev/admin/',{headers:{'Cf-Access-Authenticated-User-Email':'admin@example.test'}}),env)).status,503);});
test('large service imports and appointments use bounded query counts',async()=>{const {call,env}=fixture();const original=env.CRM_DB.prepare.bind(env.CRM_DB);let queries=0;env.CRM_DB.prepare=sql=>{queries++;return original(sql)};await call('seed','POST',{});assert(queries<10,'Catalog import should not query once per service');const contact=(await call('contacts','POST',{data:{name:'Demo',email:'demo@example.test'}})).data;const type=(await call('appointment-types','POST',{data:{name:'Long demo meeting',durationMinutes:480,bufferMinutes:240}})).data;queries=0;const saved=await call('appointments','POST',{data:{name:'Large appointment',contactId:contact.id,appointmentTypeId:type.id,startAt:'2026-11-10T13:00:00Z',endAt:'2026-11-10T21:00:00Z'}});assert.equal(saved.status,201);assert(queries<20,'Reservation should not query once per minute');assert.equal(env.CRM_DB.sqlite.prepare('SELECT COUNT(*) n FROM appointment_locks').get().n,960);});

test('inherited property names cannot become record kinds or fields',async()=>{assert.throws(()=>validate('constructor',{}));assert.throws(()=>validate('contacts',{name:'Demo',email:'demo@example.test',constructor:'unexpected'}));const {call}=fixture();assert.equal((await call('constructor')).status,404);});


test('catalog edits preserve source facts and package references; legacy rows receive categories without rewriting prices',async()=>{
 const {call}=fixture();await call('seed','POST',{});const imported=(await call('services')).data.find(r=>r.id==='hb-0-01');
 assert.equal(imported.catalogCategory,'Weddings / Cinematography');assert.equal(imported.sourcePriceCents,315000);
 const {id,version,createdAt,updatedAt,...data}=imported;
 const changed=await call('services/'+id,'PUT',{version,data:{...data,priceCents:320000,clientDescription:'Updated client draft',sourcePriceCents:1,sourceDescription:'Altered',active:false}});
 assert.equal(changed.status,200);assert.equal(changed.data.priceCents,320000);assert.equal(changed.data.sourcePriceCents,315000);assert.equal(changed.data.sourceDescription,imported.sourceDescription);assert.equal(changed.data.active,false);
 const pkg=await call('packages','POST',{data:{name:'Demo package',serviceIds:[id],optionalServiceIds:['hb-0-04'],priceCents:370000}});assert.equal(pkg.status,201);
 assert.equal((await call('packages','POST',{data:{name:'Invalid',serviceIds:['missing']}})).status,400);
 await call('seed','POST',{});assert.equal((await call('services/'+id)).data.priceCents,320000);
});

test('contact profile facts survive save and update without cross-organization exposure',async()=>{
 const {call}=fixture();const data={name:'DEMO Contact',firstName:'Demo',lastName:'Contact',partnerName:'Partner',email:'demo@example.test',phone:'555-0100',address:'Preview address',preferredContactMethod:'Email',leadSource:'Referral',importantDates:'Anniversary: November 10',notes:'Private test',demo:true};const saved=await call('contacts','POST',{data});assert.equal(saved.status,201);for(const [key,value]of Object.entries(data))assert.equal(saved.data[key],value);assert.equal((await call('contacts/'+saved.data.id,'PUT',{version:1,data:{...data,archived:true}})).status,200);assert.equal((await call('contacts/'+saved.data.id)).data.archived,true);assert.equal((await call('contacts/'+saved.data.id,'GET',null,{...user,organizationId:'other'})).status,404);
});

test('lead conversion creates contact and project atomically, preserves details and prevents repeat conversion',async()=>{
 const {call}=fixture();const lead=(await call('leads','POST',{data:{name:'Demo wedding',firstName:'Demo',lastName:'Person',partnerName:'Partner',email:'lead@example.test',phone:'555-0101',eventType:'Wedding',status:'New',location:'Preview venue address',message:'Interested in cinema',leadSource:'Referral',demo:true}})).data;const converted=await call('leads/'+lead.id+'/convert','POST',{version:1});assert.equal(converted.status,201);const contact=(await call('contacts/'+converted.data.contactId)).data;assert.equal(contact.partnerName,'Partner');assert.equal(contact.email,'lead@example.test');const project=(await call('projects/'+converted.data.id)).data;assert(project.notes.includes('Interested in cinema'));assert.equal(project.contactId,contact.id);assert.equal((await call('leads/'+lead.id+'/convert','POST',{version:1})).status,409);assert.equal((await call('contacts')).data.length,1);
});

test('project links multiple contacts, validates references and scopes chronological activity',async()=>{
 const {call}=fixture();const c1=(await call('contacts','POST',{data:{name:'Demo one',email:'one@example.test'}})).data;const c2=(await call('contacts','POST',{data:{name:'Demo two',email:'two@example.test'}})).data;const data={name:'Demo job',contactId:c1.id,additionalContactIds:[c2.id],eventType:'Wedding',status:'Booked',location:'Preview location'};const project=(await call('projects','POST',{data})).data;assert(project.id);await call('tasks','POST',{data:{name:'Demo reminder',projectId:project.id}});const timeline=await call('activity?project='+project.id);assert.equal(timeline.status,200);assert.equal(timeline.data.length,2);assert(timeline.data.some(a=>a.record_kind==='tasks'));assert.equal((await call('projects','POST',{data:{...data,additionalContactIds:['missing']}})).status,400);
});

test('proposal snapshots calculate prices server-side and reject missing prices or excessive discounts',async()=>{
 const {call}=fixture();await call('seed','POST',{});const contact=(await call('contacts','POST',{data:{name:'Demo',email:'demo@example.test'}})).data;const project=(await call('projects','POST',{data:{name:'Demo',contactId:contact.id,eventType:'Wedding',status:'Proposal'}})).data;const data={name:'Demo proposal',projectId:project.id,lineItems:[{name:'Cinema',quantity:2,unitPriceCents:315000,sourceKind:'services',sourceId:'hb-0-01'},{name:'Custom',quantity:1,unitPriceCents:10000,sourceKind:'custom'}],discountCents:5000,status:'Draft'};const saved=await call('proposals','POST',{data});assert.equal(saved.status,201);assert.equal(saved.data.subtotalCents,640000);assert.equal(saved.data.totalCents,635000);assert.equal((await call('proposals','POST',{data:{...data,discountCents:640001}})).status,400);assert.equal((await call('proposals','POST',{data:{...data,lineItems:[{name:'Unconfirmed',quantity:1,unitPriceCents:null}]}})).status,400);assert.equal((await call('proposals','POST',{data:{...data,totalCents:1}})).status,400);
});

test('editable appointment defaults are idempotent and private availability includes buffers',async()=>{
 const {call}=fixture();assert.equal((await call('setup-appointment-types','POST',{})).status,200);await call('setup-appointment-types','POST',{});assert.equal((await call('appointment-types')).data.length,6);const contact=(await call('contacts','POST',{data:{name:'Demo',email:'demo@example.test'}})).data;const type=(await call('appointment-types','POST',{data:{name:'Demo buffered',durationMinutes:30,bufferMinutes:15}})).data;await call('availability','POST',{data:{name:'Tuesday office hours',dayOfWeek:'Tuesday',startTime:'09:00',endTime:'17:00'}});const data={name:'Demo consultation',contactId:contact.id,appointmentTypeId:type.id,startAt:'2026-11-10T14:00:00Z',endAt:'2026-11-10T14:30:00Z'};assert.equal((await call('appointments','POST',{data})).status,409);assert.equal((await call('appointments','POST',{data:{...data,startAt:'2026-11-10T15:00:00Z',endAt:'2026-11-10T15:30:00Z'}})).status,201);
});

test('workflow template library has eleven categories and preserves edited drafts on repeat setup',async()=>{
 const {call}=fixture();await call('setup-email-templates','POST',{});const rows=(await call('templates')).data;assert.equal(rows.length,11);assert.equal(new Set(rows.map(r=>r.category)).size,11);const r=rows[0],{id,version,createdAt,updatedAt,...data}=r;await call('templates/'+id,'PUT',{version,data:{...data,subject:'Edited private draft'}});await call('setup-email-templates','POST',{});assert.equal((await call('templates/'+id)).data.subject,'Edited private draft');assert.equal((await call('messages','POST',{data:{name:'Cannot send',projectId:'missing',status:'Sent'}})).status,400);
});

test('manual payment plans derive paid and remaining balance and reject overpayment or live signatures',async()=>{
 const {call}=fixture();const contact=(await call('contacts','POST',{data:{name:'Demo',email:'demo@example.test'}})).data;const project=(await call('projects','POST',{data:{name:'Demo',contactId:contact.id,eventType:'Wedding',status:'Contract'}})).data;const invoice={name:'Demo payment plan',projectId:project.id,amountCents:315000,depositCents:100000,installments:[{label:'Deposit',dueAt:'2026-10-10',amountCents:100000},{label:'Balance',dueAt:'2026-11-10',amountCents:215000}],paymentHistory:[{date:'2026-10-05',amountCents:50000,reference:'Demo manual record only'}],status:'Draft'};const saved=await call('invoices','POST',{data:invoice});assert.equal(saved.status,201);assert.equal(saved.data.paidCents,50000);assert.equal(saved.data.remainingCents,265000);assert.equal((await call('invoices','POST',{data:{...invoice,paymentHistory:[{date:'2026-10-05',amountCents:315001,reference:'Overpayment'}]}})).status,400);assert.equal((await call('invoices','POST',{data:{...invoice,paidCents:1}})).status,400);assert.equal((await call('contracts','POST',{data:{name:'Demo contract',projectId:project.id,priceCents:315000,paymentSchedule:invoice.installments,status:'Draft',signatureStatus:'Not requested'}})).status,201);assert.equal((await call('contracts','POST',{data:{name:'Forbidden signature',projectId:project.id,status:'Draft',signatureStatus:'Signed'}})).status,400);
});

test('DEMO proposal links are isolated snapshots with revocation, expiry, no live acceptance and no private fields',async()=>{
 const {call,env}=fixture();env.CRM_STAGE='preview';env.CRM_ORIGIN='https://preview.example.workers.dev';await call('seed','POST',{});assert.equal((await call('setup-demo-proposals','POST',{})).status,200);const id='demo-presentation-wedding-cinema';let p=(await call('proposals/'+id)).data;assert.equal(p.totalCents,315000);assert.equal(p.lineItems[1].optional,true);
 const {id:pid,version,createdAt,updatedAt,subtotalCents,totalCents,...data}=p;p=(await call('proposals/'+id,'PUT',{version,data:{...data,notes:'SECRET INTERNAL NOTES',clientNames:'DEMO <script>alert(1)</script>'}})).data;
 const created=await call('proposals/'+id+'/share','POST',{action:'create',version:p.version});assert.equal(created.status,200);assert.match(created.data.url,/\/proposal\/[a-f0-9]{64}$/);const publicRead=()=>worker.fetch(new Request(created.data.url),env);let response=await publicRead();assert.equal(response.status,200);let html=await response.text();assert(!html.includes('SECRET INTERNAL'));assert(!html.includes('example.test'));assert(!html.includes('sourcePrice'));assert(!html.includes('projectId'));assert(!html.includes('<script>alert'));assert(html.includes('&lt;script&gt;'));assert(html.includes('$3,150.00'));assert(!html.includes('href="/admin'));assert.equal(response.headers.get('Referrer-Policy'),'no-referrer');assert(response.headers.get('Cache-Control').includes('no-store'));
 let info=(await call('proposals/'+id+'/share')).data;assert.equal(info.current.status,'Viewed');assert(info.current.lastViewed);assert.equal(info.current.views,1);await worker.fetch(new Request(created.data.url,{method:'HEAD'}),env);assert.equal((await call('proposals/'+id+'/share')).data.current.views,1);
 const {id:i2,version:v2,createdAt:c2,updatedAt:u2,subtotalCents:s2,totalCents:t2,...d2}=p;p=(await call('proposals/'+id,'PUT',{version:v2,data:{...d2,clientNames:'DEMO new revision'}})).data;assert(!(await (await publicRead()).text()).includes('DEMO new revision'));assert.equal((await call('proposals/'+id+'/share')).data.current.revision,2);
 const regenerated=await call('proposals/'+id+'/share','POST',{action:'regenerate',version:p.version});assert.equal(regenerated.status,200);assert.notEqual(created.data.url,regenerated.data.url);assert.equal((await publicRead()).status,404);assert((await (await worker.fetch(new Request(regenerated.data.url),env)).text()).includes('DEMO new revision'));assert.equal((await call('proposals/'+id+'/share')).data.history.length,2);
 assert.equal((await worker.fetch(new Request(regenerated.data.url,{method:'POST'}),env)).status,405);assert.equal((await worker.fetch(new Request(regenerated.data.url),{...env,CRM_STAGE:'production'})).status,404);assert.equal((await worker.fetch(new Request(regenerated.data.url.replace('preview.example.workers.dev','giolinafilms.com')),env)).status,404);assert.equal((await call('proposal-shares')).status,404);assert.equal((await call('proposals/'+id+'/share','GET',null,{...user,organizationId:'other'})).status,404);
 await call('proposals/'+id+'/share','POST',{action:'disable',version:p.version});assert.equal((await worker.fetch(new Request(regenerated.data.url),env)).status,404);assert.equal((await call('proposals/'+id+'/share')).data.current,null);
 const newer=await call('proposals/'+id+'/share','POST',{action:'create',version:p.version});env.CRM_DB.sqlite.exec("UPDATE proposal_shares SET data=json_set(data,'$.expiresAt','2000-01-01T00:00:00Z') WHERE kind='proposal-shares'");assert.equal((await worker.fetch(new Request(newer.data.url),env)).status,404);
 const nonDemo=await call('proposals','POST',{data:{...data,name:'Private real record',demo:false}});assert.equal((await call('proposals/'+nonDemo.data.id+'/share','POST',{action:'create',version:1})).status,400);await call('setup-demo-proposals','POST',{});assert.equal((await call('proposals/'+id)).data.clientNames,'DEMO new revision');
});
test('presentation inputs reject active content; sections and optional pricing are validated',()=>{
 for(const field of ['heroImage','thumbnail'])assert.throws(()=>validate('services',{name:'X',[field]:'javascript:alert(1)'}));assert.throws(()=>validate('services',{name:'X',filmUrl:'https://evil.test/embed'}));assert.throws(()=>validate('services',{name:'X',galleryImages:['https://evil.test/pixel']}));assert.throws(()=>validate('proposals',{name:'X',contactId:'c',lineItems:[{name:'X',quantity:1,unitPriceCents:100}],sectionOrder:['services','services','investment']}));assert.throws(()=>validate('proposals',{name:'X',contactId:'c',status:'Accepted (test only)',lineItems:[{name:'X',quantity:1,unitPriceCents:100}]}));
 const row=validate('proposals',{name:'X',contactId:'c',lineItems:[{name:'Base',quantity:2,unitPriceCents:100},{name:'Option',quantity:1,unitPriceCents:900,optional:true}],discountCents:20});assert.equal(row.totalCents,180);
});

test('invoice drafts derive totals and stable unique numbers without payment activation',async()=>{
 const {call}=fixture();const c=(await call('contacts','POST',{data:{name:'Demo',email:'demo@example.test'}})).data;const p=(await call('projects','POST',{data:{name:'Demo',contactId:c.id,eventType:'Wedding',status:'Planning'}})).data;
 const data={name:'Itemized draft',projectId:p.id,status:'Draft',lineItems:[{name:'Coverage',quantity:2,unitPriceCents:10000,sourceKind:'custom'}],discountCents:2000,taxCents:900,amountCents:1,paymentHistory:[{date:'2026-10-05',amountCents:5000,reference:'Manual demo'}]};
 const a=await call('invoices','POST',{data});assert.equal(a.status,201);assert.equal(a.data.subtotalCents,20000);assert.equal(a.data.amountCents,18900);assert.equal(a.data.remainingCents,13900);assert.match(a.data.invoiceNumber,/^GL-DRAFT-/);assert.match(a.data.issueAt,/^\d{4}-\d{2}-\d{2}$/);
 const b=await call('invoices','POST',{data});assert.notEqual(a.data.invoiceNumber,b.data.invoiceNumber);const edit=await call('invoices/'+a.data.id,'PUT',{data,version:1});assert.equal(edit.data.invoiceNumber,a.data.invoiceNumber);
 for(const bad of [{taxCents:-1},{discountCents:20001},{status:'Sent'},{invoiceNumber:'forged'},{lineItems:[{...data.lineItems[0],optional:true}]},{paymentHistory:[{date:'2026-10-05',amountCents:18901,reference:'Too much'}]}])assert.equal((await call('invoices','POST',{data:{...data,...bad}})).status,400);
 assert.equal(validate('invoices',{name:'Legacy',projectId:p.id,amountCents:500,lineItems:[]}).remainingCents,500);
});
