import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {generateKeyPair,SignJWT,createLocalJWKSet,exportJWK} from 'jose';
import {api} from '../api.mjs';
import {authenticate,verifyIdentity} from '../auth.mjs';
import {handlePrivate} from '../router.mjs';
import worker from '../../worker.js';
import {validate} from '../model.mjs';
import catalog from '../data/catalog.json' with {type:'json'};
class D1Adapter{
 constructor(){this.sqlite=new DatabaseSync(':memory:');this.sqlite.exec(readFileSync(new URL('../migrations/0001_foundation.sql',import.meta.url),'utf8'));}
 prepare(sql){const db=this.sqlite;let args=[];return {bind(...values){args=values;return this},async all(){return {results:db.prepare(sql).all(...args)}},async first(){return db.prepare(sql).get(...args)||null},run(){return db.prepare(sql).run(...args)}};}
 async batch(statements){this.sqlite.exec('BEGIN');try{const result=statements.map(s=>s.run());this.sqlite.exec('COMMIT');return result;}catch(e){this.sqlite.exec('ROLLBACK');throw e;}}
}
const user={email:'admin@example.test',organizationId:'giolina-preview',role:'admin'};
function fixture(){const env={CRM_DB:new D1Adapter()};async function call(path,method='GET',body,userOverride=user,headers={}){const response=await api(new Request('https://preview.example.workers.dev/api/admin/'+path,{method,headers:{Origin:'https://preview.example.workers.dev','Content-Type':'application/json','X-GioLina-Request':'admin',...headers},...(body?{body:JSON.stringify(body)}:{})}),env,userOverride,path);return {status:response.status,data:await response.json()};}return {call,env};}
test('catalog preserves prices, hours, missing prices and historical variants',()=>{assert.equal(catalog.length,47);assert.equal(new Set(catalog.map(r=>r.id)).size,47);for(const row of catalog)assert.deepEqual(validate('services',Object.fromEntries(Object.entries(row).filter(([k])=>k!=='id'))),Object.fromEntries(Object.entries(row).filter(([k])=>k!=='id')));assert.equal(catalog.find(r=>r.category==='Wedding 2026'&&r.conflictGroup==='wedding-feature').priceCents,315000);assert.equal(catalog.find(r=>r.category==='Sweet Sixteen 2024'&&r.conflictGroup==='overtime').priceCents,12500);assert.equal(catalog.filter(r=>r.category.startsWith('Saved')).length,25);assert(catalog.filter(r=>r.conflictGroup==='additional-cinematographer').some(r=>r.coverageHours===10&&r.priceCents===null));});
test('CRUD, optimistic edits, organization isolation, seed idempotency and lead conversion',async()=>{const {call,env}=fixture();assert.equal((await call('seed','POST',{})).status,201);assert.equal((await call('seed','POST',{})).status,200);assert.equal((await call('services')).data.length,47);const contact=(await call('contacts','POST',{data:{name:'Demo contact',email:'demo@example.test',demo:true}})).data;assert(contact.id);assert.equal((await call('contacts/'+contact.id,'PUT',{data:{...contact,id:undefined},version:contact.version})).status,400);const updated=await call('contacts/'+contact.id,'PUT',{data:{name:'Updated demo',email:'demo@example.test',demo:true},version:1});assert.equal(updated.data.version,2);assert.equal((await call('contacts/'+contact.id,'PUT',{data:{name:'Stale',email:'demo@example.test'},version:1})).status,409);assert.deepEqual((await call('contacts','GET',null,{...user,organizationId:'other'})).data,[]);const lead=(await call('leads','POST',{data:{name:'Demo inquiry',contactId:contact.id,eventType:'Wedding',status:'New Inquiry',demo:true}})).data;assert.equal((await call('leads/'+lead.id+'/convert','POST',{version:1})).status,201);assert.equal((await call('leads/'+lead.id+'/convert','POST',{version:1})).status,409);assert.equal((await call('projects')).data.length,1);assert.equal(env.CRM_DB.sqlite.prepare('SELECT COUNT(*) n FROM write_guards').get().n,0);assert((await call('activity')).data.length>=4);});
test('atomic appointment overlaps, buffers, cancellation, rescheduling and blocked dates',async()=>{const {call}=fixture();const contact=(await call('contacts','POST',{data:{name:'Demo',email:'demo@example.test'}})).data;const type=(await call('appointment-types','POST',{data:{name:'Demo consultation',durationMinutes:30,bufferMinutes:10}})).data;const data={name:'Demo meeting',contactId:contact.id,appointmentTypeId:type.id,startAt:'2026-11-05T15:00:00Z',endAt:'2026-11-05T15:30:00Z',status:'Scheduled'};const first=(await call('appointments','POST',{data})).data;assert(first.id);assert.equal((await call('appointments','POST',{data:{...data,startAt:'2026-11-05T15:35:00Z',endAt:'2026-11-05T16:05:00Z'}})).status,409);assert.equal((await call('appointments')).data.length,1);assert.equal((await call('appointments/'+first.id,'PUT',{data:{...data,status:'Cancelled'},version:1})).status,200);assert.equal((await call('appointments','POST',{data})).status,201);await call('availability','POST',{data:{name:'Demo blocked date',dayOfWeek:'Friday',startTime:'09:00',endTime:'17:00',blockedDate:'2026-11-06'}});assert.equal((await call('appointments','POST',{data:{...data,startAt:'2026-11-06T15:00:00Z',endAt:'2026-11-06T15:30:00Z'}})).status,409);});
test('validation and CSRF keep drafts safe',async()=>{const {call}=fixture();assert.equal((await call('contacts','POST',{data:{name:'Demo',email:'demo@example.test'}},user,{Origin:'https://evil.test'})).status,403);assert.throws(()=>validate('contacts',{name:'   ',email:'demo@example.test'}));assert.throws(()=>validate('leads',{name:'Bad date',contactId:'a',eventType:'Wedding',status:'Lead',eventDate:'2026-02-30'}));assert.throws(()=>validate('automations',{name:'Unsafe',enabled:true}));assert.throws(()=>validate('messages',{name:'Message',projectId:'p',status:'Sent'}));assert.throws(()=>validate('contracts',{name:'Sign',projectId:'p',status:'Signed'}));assert.throws(()=>validate('invoices',{name:'Pay',projectId:'p',status:'Paid'}));assert.equal((await call('projects','POST',{data:{name:'Unknown',contactId:'missing',eventType:'Wedding',status:'Lead'}})).status,400);});
test('JWT verifies signature, audience, issuer, expiry and exact administrator allowlist',async()=>{const {privateKey,publicKey}=await generateKeyPair('RS256');const jwk=await exportJWK(publicKey);jwk.kid='test';const keys=createLocalJWKSet({keys:[jwk]});const env={CRM_ACCESS_TEAM:'example.cloudflareaccess.com',CRM_ACCESS_AUD:'admin-audience',CRM_ADMIN_EMAILS:'admin@example.test'};async function token(email='admin@example.test',aud='admin-audience',expires='1h'){return new SignJWT({email}).setProtectedHeader({alg:'RS256',kid:'test'}).setIssuer('https://example.cloudflareaccess.com').setAudience(aud).setSubject('example-subject').setIssuedAt().setExpirationTime(expires).sign(privateKey)}assert.equal((await verifyIdentity(await token(),env,keys)).role,'admin');assert.equal(await verifyIdentity(await token('other@example.test'),env,keys),null);await assert.rejects(verifyIdentity(await token('admin@example.test','wrong'),env,keys));await assert.rejects(verifyIdentity(await token('admin@example.test','admin-audience','-1h'),env,keys));await assert.rejects(verifyIdentity((await token()).slice(0,-3)+'bad',env,keys));assert.equal(await authenticate(new Request('https://giolinafilms.com/admin/'),{...env,CRM_STAGE:'preview',CRM_ORIGIN:'https://example.workers.dev'}),null);});
test('all private resources fail closed; public site and non-GET behavior remain intact',async()=>{for(const path of ['/admin/','/admin/contacts/','/admin/app.js','/admin/app.css','/api/admin/meta','/api/admin/services','/portal/','/api/portal/projects']){const response=await handlePrivate(new Request('https://example.workers.dev'+path),{});assert([401,503].includes(response.status));assert.equal(response.headers.get('Cache-Control'),'no-store');const body=await response.text();assert(!body.includes('Imported 47'));assert(!body.includes('5-Hour Corporate'));assert(!body.includes('record-form'));}let called=0;const env={ASSETS:{async fetch(){called++;return new Response('public content')}}};const publicResponse=await worker.fetch(new Request('https://example.workers.dev/'),env);assert.equal(await publicResponse.text(),'public content');assert.equal(called,1);assert.equal((await worker.fetch(new Request('https://example.workers.dev/',{method:'POST'}),env)).status,405);assert.equal((await worker.fetch(new Request('https://example.workers.dev/admin/',{headers:{'Cf-Access-Authenticated-User-Email':'admin@example.test'}}),env)).status,503);});
