import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {generateKeyPair,SignJWT,createLocalJWKSet,exportJWK} from 'jose';
import {api} from '../api.mjs';
import {authenticate,verifyIdentity} from '../auth.mjs';
import {handlePrivate} from '../router.mjs';
import worker from '../../worker.js';
import {validate} from '../model.mjs';
import catalog from '../data/catalog.json' with {type:'json'};
class D1Adapter{
 constructor(){this.sqlite=new DatabaseSync(':memory:');this.sqlite.exec(readFileSync(new URL('../migrations/0001_foundation.sql',import.meta.url),'utf8'));}
 prepare(sql){const db=this.sqlite;let args=[];return {bind(...values){args=values;return this},async all(){return {results:db.prepare(sql).all(...args)}},async first(){return db.prepare(sql).get(...args)||null},run(){return db.prepare(sql).run(...args)}};}
 async batch(statements){this.sqlite.exec('BEGIN');try{const result=statements.map(s=>s.run());this.sqlite.exec('COMMIT');return result;}catch(e){this.sqlite.exec('ROLLBACK');throw e;}}
}
const user={email:'admin@example.test',organizationId:'giolina-preview',role:'admin'};
function fixture(){const env={CRM_DB:new D1Adapter()};async function call(path,method='GET',body,userOverride=user,headers={}){const response=await api(new Request('https://preview.example.workers.dev/api/admin/'+path,{method,headers:{Origin:'https://preview.example.workers.dev','Content-Type':'application/json','X-GioLina-Request':'admin',...headers},...(body?{body:JSON.stringify(body)}:{})}),env,userOverride,path);return {status:response.status,data:await response.json()};}return {call,env};}
test('catalog preserves prices, hours, missing prices and historical variants',()=>{assert.equal(catalog.length,47);assert.equal(new Set(catalog.map(r=>r.id)).size,47);for(const row of catalog)assert.deepEqual(validate('services',Object.fromEntries(Object.entries(row).filter(([k])=>k!=='id'))),{...Object.fromEntries(Object.entries(row).filter(([k])=>k!=='id')),active:true});assert.equal(catalog.find(r=>r.category==='Wedding 2026'&&r.conflictGroup==='wedding-feature').priceCents,315000);assert.equal(catalog.find(r=>r.category==='Sweet Sixteen 2024'&&r.conflictGroup==='overtime').priceCents,12500);assert.equal(catalog.filter(r=>r.category.startsWith('Saved')).length,25);assert(catalog.filter(r=>r.conflictGroup==='additional-cinematographer').some(r=>r.coverageHours===10&&r.priceCents===null));});
test('CRUD, optimistic edits, organization isolation, seed idempotency and lead conversion',async()=>{const {call,env}=fixture();assert.equal((await call('seed','POST',{})).status,201);assert.equal((await call('seed','POST',{})).status,200);assert.equal((await call('services')).data.length,50);const contact=(await call('contacts','POST',{data:{name:'Demo contact',email:'demo@example.test',demo:true}})).data;assert(contact.id);assert.equal((await call('contacts/'+contact.id,'PUT',{data:{...contact,id:undefined},version:contact.version})).status,400);const updated=await call('contacts/'+contact.id,'PUT',{data:{name:'Updated demo',email:'demo@example.test',demo:true},version:1});assert.equal(updated.data.version,2);assert.equal((await call('contacts/'+contact.id,'PUT',{data:{name:'Stale',email:'demo@example.test'},version:1})).status,409);assert.deepEqual((await call('contacts','GET',null,{...user,organizationId:'other'})).data,[]);const lead=(await call('leads','POST',{data:{name:'Demo inquiry',contactId:contact.id,eventType:'Wedding',status:'New Inquiry',demo:true}})).data;assert.equal((await call('leads/'+lead.id+'/convert','POST',{version:1})).status,201);assert.equal((await call('leads/'+lead.id+'/convert','POST',{version:1})).status,409);assert.equal((await call('projects')).data.length,1);assert.equal(env.CRM_DB.sqlite.prepare('SELECT COUNT(*) n FROM write_guards').get().n,0);assert((await call('activity')).data.length>=4);});
test('atomic appointment overlaps, buffers, cancellation, rescheduling and blocked dates',async()=>{const {call}=fixture();const contact=(await call('contacts','POST',{data:{name:'Demo',email:'demo@example.test'}})).data;const type=(await call('appointment-types','POST',{data:{name:'Demo consultation',durationMinutes:30,bufferMinutes:10}})).data;const data={name:'Demo meeting',contactId:contact.id,appointmentTypeId:type.id,startAt:'2026-11-05T15:00:00Z',endAt:'2026-11-05T15:30:00Z',status:'Scheduled'};const first=(await call('appointments','POST',{data})).data;assert(first.id);assert.equal((await call('appointments','POST',{data:{...data,startAt:'2026-11-05T15:35:00Z',endAt:'2026-11-05T16:05:00Z'}})).status,409);assert.equal((await call('appointments')).data.length,1);assert.equal((await call('appointments/'+first.id,'PUT',{data:{...data,status:'Cancelled'},version:1})).status,200);assert.equal((await call('appointments','POST',{data})).status,201);await call('availability','POST',{data:{name:'Demo blocked date',dayOfWeek:'Friday',startTime:'09:00',endTime:'17:00',blockedDate:'2026-11-06'}});assert.equal((await call('appointments','POST',{data:{...data,startAt:'2026-11-06T15:00:00Z',endAt:'2026-11-06T15:30:00Z'}})).status,409);});
test('validation and CSRF keep drafts safe',async()=>{const {call}=fixture();assert.equal((await call('contacts','POST',{data:{name:'Demo',email:'demo@example.test'}},user,{Origin:'https://evil.test'})).status,403);assert.throws(()=>validate('contacts',{name:'   ',email:'demo@example.test'}));assert.throws(()=>validate('leads',{name:'Bad date',contactId:'a',eventType:'Wedding',status:'Lead',eventDate:'2026-02-30'}));assert.throws(()=>validate('automations',{name:'Unsafe',enabled:true}));assert.throws(()=>validate('messages',{name:'Message',projectId:'p',status:'Sent'}));assert.throws(()=>validate('contracts',{name:'Sign',projectId:'p',status:'Signed'}));assert.throws(()=>validate('invoices',{name:'Pay',projectId:'p',status:'Paid'}));assert.equal((await call('projects','POST',{data:{name:'Unknown',contactId:'missing',eventType:'Wedding',status:'Lead'}})).status,400);});
test('JWT verifies signature, audience, issuer, expiry and exact administrator allowlist',async()=>{const {privateKey,publicKey}=await generateKeyPair('RS256');const jwk=await exportJWK(publicKey);jwk.kid='test';const keys=createLocalJWKSet({keys:[jwk]});const env={CRM_ACCESS_TEAM:'example.cloudflareaccess.com',CRM_ACCESS_AUD:'admin-audience',CRM_ADMIN_EMAILS:'admin@example.test'};async function token(email='admin@example.test',aud='admin-audience',expires='1h'){return new SignJWT({email}).setProtectedHeader({alg:'RS256',kid:'test'}).setIssuer('https://example.cloudflareaccess.com').setAudience(aud).setSubject('example-subject').setIssuedAt().setExpirationTime(expires).sign(privateKey)}assert.equal((await verifyIdentity(await token(),env,keys)).role,'admin');assert.equal(await verifyIdentity(await token('other@example.test'),env,keys),null);await assert.rejects(verifyIdentity(await token('admin@example.test','wrong'),env,keys));await assert.rejects(verifyIdentity(await token('admin@example.test','admin-audience','-1h'),env,keys));await assert.rejects(verifyIdentity((await token()).slice(0,-3)+'bad',env,keys));assert.equal(await authenticate(new Request('https://giolinafilms.com/admin/'),{...env,CRM_STAGE:'preview',CRM_ORIGIN:'https://example.workers.dev'}),null);});
test('all private resources fail closed; public site and non-GET behavior remain intact',async()=>{for(const path of ['/admin/','/admin/contacts/','/admin/app.js','/admin/app.css','/api/admin/meta','/api/admin/services','/portal/','/api/portal/projects']){const response=await handlePrivate(new Request('https://example.workers.dev'+path),{});assert([401,503].includes(response.status));assert.equal(response.headers.get('Cache-Control'),'no-store');const body=await response.text();assert(!body.includes('Imported 47'));assert(!body.includes('5-Hour Corporate'));assert(!body.includes('record-form'));}let called=0;const env={ASSETS:{async fetch(){called++;return new Response('public content')}}};const publicResponse=await worker.fetch(new Request('https://example.workers.dev/'),env);assert.equal(await publicResponse.text(),'public content');assert.equal(called,1);assert.equal((await worker.fetch(new Request('https://example.workers.dev/',{method:'POST'}),env)).status,405);assert.equal((await worker.fetch(new Request('https://example.workers.dev/admin/',{headers:{'Cf-Access-Authenticated-User-Email':'admin@example.test'}}),env)).status,503);});
test('large service imports and appointments use bounded query counts',async()=>{const {call,env}=fixture();const original=env.CRM_DB.prepare.bind(env.CRM_DB);let queries=0;env.CRM_DB.prepare=sql=>{queries++;return original(sql)};await call('seed','POST',{});assert(queries<10,'Catalog import should not query once per service');const contact=(await call('contacts','POST',{data:{name:'Demo',email:'demo@example.test'}})).data;const type=(await call('appointment-types','POST',{data:{name:'Long demo meeting',durationMinutes:480,bufferMinutes:240}})).data;queries=0;const saved=await call('appointments','POST',{data:{name:'Large appointment',contactId:contact.id,appointmentTypeId:type.id,startAt:'2026-11-10T13:00:00Z',endAt:'2026-11-10T21:00:00Z'}});assert.equal(saved.status,201);assert(queries<20,'Reservation should not query once per minute');assert.equal(env.CRM_DB.sqlite.prepare('SELECT COUNT(*) n FROM appointment_locks').get().n,960);});

test('inherited property names cannot become record kinds or fields',async()=>{assert.throws(()=>validate('constructor',{}));assert.throws(()=>validate('contacts',{name:'Demo',email:'demo@example.test',constructor:'unexpected'}));const {call}=fixture();assert.equal((await call('constructor')).status,404);});


test('catalog edits preserve source facts and package references; legacy rows receive categories without rewriting prices',async()=>{
 const {call}=fixture();await call('seed','POST',{});const imported=(await call('services')).data.find(r=>r.id==='hb-0-01');
 assert.equal(imported.catalogCategory,'Weddings / Cinematography');assert.equal(imported.sourcePriceCents,315000);
 const {id,version,createdAt,updatedAt,...data}=imported;
 const changed=await call('services/'+id,'PUT',{version,data:{...data,priceCents:320000,clientDescription:'Updated client draft',sourcePriceCents:1,sourceDescription:'Altered',active:false}});
 assert.equal(changed.status,200);assert.equal(changed.data.priceCents,320000);assert.equal(changed.data.sourcePriceCents,315000);assert.equal(changed.data.sourceDescription,imported.sourceDescription);assert.equal(changed.data.active,false);
 const pkg=await call('packages','POST',{data:{name:'Demo package',serviceIds:[id],optionalServiceIds:['hb-0-04'],priceCents:370000}});assert.equal(pkg.status,201);
 assert.equal((await call('packages','POST',{data:{name:'Invalid',serviceIds:['missing']}})).status,400);
 await call('seed','POST',{});assert.equal((await call('services/'+id)).data.priceCents,320000);
});

test('contact profile facts survive save and update without cross-organization exposure',async()=>{
 const {call}=fixture();const data={name:'DEMO Contact',firstName:'Demo',lastName:'Contact',partnerName:'Partner',email:'demo@example.test',phone:'555-0100',address:'Preview address',preferredContactMethod:'Email',leadSource:'Referral',importantDates:'Anniversary: November 10',notes:'Private test',demo:true};const saved=await call('contacts','POST',{data});assert.equal(saved.status,201);for(const [key,value]of Object.entries(data))assert.equal(saved.data[key],value);assert.equal((await call('contacts/'+saved.data.id,'PUT',{version:1,data:{...data,archived:true}})).status,200);assert.equal((await call('contacts/'+saved.data.id)).data.archived,true);assert.equal((await call('contacts/'+saved.data.id,'GET',null,{...user,organizationId:'other'})).status,404);
});

test('lead conversion creates contact and project atomically, preserves details and prevents repeat conversion',async()=>{
 const {call}=fixture();const lead=(await call('leads','POST',{data:{name:'Demo wedding',firstName:'Demo',lastName:'Person',partnerName:'Partner',email:'lead@example.test',phone:'555-0101',eventType:'Wedding',status:'New',location:'Preview venue address',message:'Interested in cinema',leadSource:'Referral',demo:true}})).data;const converted=await call('leads/'+lead.id+'/convert','POST',{version:1});assert.equal(converted.status,201);const contact=(await call('contacts/'+converted.data.contactId)).data;assert.equal(contact.partnerName,'Partner');assert.equal(contact.email,'lead@example.test');const project=(await call('projects/'+converted.data.id)).data;assert(project.notes.includes('Interested in cinema'));assert.equal(project.contactId,contact.id);assert.equal((await call('leads/'+lead.id+'/convert','POST',{version:1})).status,409);assert.equal((await call('contacts')).data.length,1);
});

test('project links multiple contacts, validates references and scopes chronological activity',async()=>{
 const {call}=fixture();const c1=(await call('contacts','POST',{data:{name:'Demo one',email:'one@example.test'}})).data;const c2=(await call('contacts','POST',{data:{name:'Demo two',email:'two@example.test'}})).data;const data={name:'Demo job',contactId:c1.id,additionalContactIds:[c2.id],eventType:'Wedding',status:'Booked',location:'Preview location'};const project=(await call('projects','POST',{data})).data;assert(project.id);await call('tasks','POST',{data:{name:'Demo reminder',projectId:project.id}});const timeline=await call('activity?project='+project.id);assert.equal(timeline.status,200);assert.equal(timeline.data.length,2);assert(timeline.data.some(a=>a.record_kind==='tasks'));assert.equal((await call('projects','POST',{data:{...data,additionalContactIds:['missing']}})).status,400);
});

test('proposal snapshots calculate prices server-side and reject missing prices or excessive discounts',async()=>{
 const {call}=fixture();await call('seed','POST',{});const contact=(await call('contacts','POST',{data:{name:'Demo',email:'demo@example.test'}})).data;const project=(await call('projects','POST',{data:{name:'Demo',contactId:contact.id,eventType:'Wedding',status:'Proposal'}})).data;const data={name:'Demo proposal',projectId:project.id,lineItems:[{name:'Cinema',quantity:2,unitPriceCents:315000,sourceKind:'services',sourceId:'hb-0-01'},{name:'Custom',quantity:1,unitPriceCents:10000,sourceKind:'custom'}],discountCents:5000,status:'Draft'};const saved=await call('proposals','POST',{data});assert.equal(saved.status,201);assert.equal(saved.data.subtotalCents,640000);assert.equal(saved.data.totalCents,635000);assert.equal((await call('proposals','POST',{data:{...data,discountCents:640001}})).status,400);assert.equal((await call('proposals','POST',{data:{...data,lineItems:[{name:'Unconfirmed',quantity:1,unitPriceCents:null}]}})).status,400);assert.equal((await call('proposals','POST',{data:{...data,totalCents:1}})).status,400);
});

test('editable appointment defaults are idempotent and private availability includes buffers',async()=>{
 const {call}=fixture();assert.equal((await call('setup-appointment-types','POST',{})).status,200);await call('setup-appointment-types','POST',{});assert.equal((await call('appointment-types')).data.length,4);const contact=(await call('contacts','POST',{data:{name:'Demo',email:'demo@example.test'}})).data;const type=(await call('appointment-types','POST',{data:{name:'Demo buffered',durationMinutes:30,bufferMinutes:15}})).data;await call('availability','POST',{data:{name:'Tuesday office hours',dayOfWeek:'Tuesday',startTime:'09:00',endTime:'17:00'}});const data={name:'Demo consultation',contactId:contact.id,appointmentTypeId:type.id,startAt:'2026-11-10T14:00:00Z',endAt:'2026-11-10T14:30:00Z'};assert.equal((await call('appointments','POST',{data})).status,409);assert.equal((await call('appointments','POST',{data:{...data,startAt:'2026-11-10T15:00:00Z',endAt:'2026-11-10T15:30:00Z'}})).status,201);
});

test('workflow template library has eleven categories and preserves edited drafts on repeat setup',async()=>{
 const {call}=fixture();await call('setup-email-templates','POST',{});const rows=(await call('templates')).data;assert.equal(rows.length,11);assert.equal(new Set(rows.map(r=>r.category)).size,11);const r=rows[0],{id,version,createdAt,updatedAt,...data}=r;await call('templates/'+id,'PUT',{version,data:{...data,subject:'Edited private draft'}});await call('setup-email-templates','POST',{});assert.equal((await call('templates/'+id)).data.subject,'Edited private draft');assert.equal((await call('messages','POST',{data:{name:'Cannot send',projectId:'missing',status:'Sent'}})).status,400);
});

test('manual payment plans derive paid and remaining balance and reject overpayment or live signatures',async()=>{
 const {call}=fixture();const contact=(await call('contacts','POST',{data:{name:'Demo',email:'demo@example.test'}})).data;const project=(await call('projects','POST',{data:{name:'Demo',contactId:contact.id,eventType:'Wedding',status:'Contract'}})).data;const invoice={name:'Demo payment plan',projectId:project.id,amountCents:315000,depositCents:100000,installments:[{label:'Deposit',dueAt:'2026-10-10',amountCents:100000},{label:'Balance',dueAt:'2026-11-10',amountCents:215000}],paymentHistory:[{date:'2026-10-05',amountCents:50000,reference:'Demo manual record only'}],status:'Draft'};const saved=await call('invoices','POST',{data:invoice});assert.equal(saved.status,201);assert.equal(saved.data.paidCents,50000);assert.equal(saved.data.remainingCents,265000);assert.equal((await call('invoices','POST',{data:{...invoice,paymentHistory:[{date:'2026-10-05',amountCents:315001,reference:'Overpayment'}]}})).status,400);assert.equal((await call('invoices','POST',{data:{...invoice,paidCents:1}})).status,400);assert.equal((await call('contracts','POST',{data:{name:'Demo contract',projectId:project.id,priceCents:315000,paymentSchedule:invoice.installments,status:'Draft',signatureStatus:'Not requested'}})).status,201);assert.equal((await call('contracts','POST',{data:{name:'Forbidden signature',projectId:project.id,status:'Draft',signatureStatus:'Signed'}})).status,400);
});

test('DEMO proposal links are isolated snapshots with revocation, expiry, no live acceptance and no private fields',async()=>{
 const {call,env}=fixture();env.CRM_STAGE='preview';env.CRM_ORIGIN='https://preview.example.workers.dev';await call('seed','POST',{});assert.equal((await call('setup-demo-proposals','POST',{})).status,200);const id='demo-presentation-wedding-cinema';let p=(await call('proposals/'+id)).data;assert.equal(p.totalCents,315000);assert.equal(p.lineItems[1].optional,true);
 const {id:pid,version,createdAt,updatedAt,subtotalCents,totalCents,catalogSnapshot,...data}=p;p=(await call('proposals/'+id,'PUT',{version,data:{...data,notes:'SECRET INTERNAL NOTES',clientNames:'DEMO <script>alert(1)</script>'}})).data;
 const created=await call('proposals/'+id+'/share','POST',{action:'create',version:p.version});assert.equal(created.status,200);assert.match(created.data.url,/\/proposal\/[a-f0-9]{64}$/);const publicRead=()=>worker.fetch(new Request(created.data.url),env);let response=await publicRead();assert.equal(response.status,200);let html=await response.text();assert(!html.includes('SECRET INTERNAL'));assert(!html.includes('example.test'));assert(!html.includes('sourcePrice'));assert(!html.includes('projectId'));assert(!html.includes('<script>alert'));assert(html.includes('&lt;script&gt;'));assert(html.includes('$3,150.00'));assert(!html.includes('href="/admin'));assert.equal(response.headers.get('Referrer-Policy'),'no-referrer');assert(response.headers.get('Cache-Control').includes('no-store'));
 let info=(await call('proposals/'+id+'/share')).data;assert.equal(info.current.status,'Viewed');assert(info.current.lastViewed);assert.equal(info.current.views,1);await worker.fetch(new Request(created.data.url,{method:'HEAD'}),env);assert.equal((await call('proposals/'+id+'/share')).data.current.views,1);
 const {id:i2,version:v2,createdAt:c2,updatedAt:u2,subtotalCents:s2,totalCents:t2,catalogSnapshot:cs2,...d2}=p;p=(await call('proposals/'+id,'PUT',{version:v2,data:{...d2,clientNames:'DEMO new revision'}})).data;assert(!(await (await publicRead()).text()).includes('DEMO new revision'));assert.equal((await call('proposals/'+id+'/share')).data.current.revision,2);
 const regenerated=await call('proposals/'+id+'/share','POST',{action:'regenerate',version:p.version});assert.equal(regenerated.status,200);assert.notEqual(created.data.url,regenerated.data.url);assert.equal((await publicRead()).status,404);assert((await (await worker.fetch(new Request(regenerated.data.url),env)).text()).includes('DEMO new revision'));assert.equal((await call('proposals/'+id+'/share')).data.history.length,2);
 assert.equal((await worker.fetch(new Request(regenerated.data.url,{method:'POST'}),env)).status,405);assert.equal((await worker.fetch(new Request(regenerated.data.url),{...env,CRM_STAGE:'production'})).status,404);assert.equal((await worker.fetch(new Request(regenerated.data.url.replace('preview.example.workers.dev','giolinafilms.com')),env)).status,404);assert.equal((await call('proposal-shares')).status,404);assert.equal((await call('proposals/'+id+'/share','GET',null,{...user,organizationId:'other'})).status,404);
 await call('proposals/'+id+'/share','POST',{action:'disable',version:p.version});assert.equal((await worker.fetch(new Request(regenerated.data.url),env)).status,404);assert.equal((await call('proposals/'+id+'/share')).data.current,null);
 const newer=await call('proposals/'+id+'/share','POST',{action:'create',version:p.version});env.CRM_DB.sqlite.exec("UPDATE proposal_shares SET data=json_set(data,'$.expiresAt','2000-01-01T00:00:00Z') WHERE kind='proposal-shares'");assert.equal((await worker.fetch(new Request(newer.data.url),env)).status,404);
 const nonDemo=await call('proposals','POST',{data:{...data,name:'Private real record',demo:false}});assert.equal((await call('proposals/'+nonDemo.data.id+'/share','POST',{action:'create',version:1})).status,400);await call('setup-demo-proposals','POST',{});assert.equal((await call('proposals/'+id)).data.clientNames,'DEMO new revision');
});
test('presentation inputs reject active content; sections and optional pricing are validated',()=>{
 for(const field of ['heroImage','thumbnail'])assert.throws(()=>validate('services',{name:'X',[field]:'javascript:alert(1)'}));assert.throws(()=>validate('services',{name:'X',filmUrl:'https://evil.test/embed'}));assert.throws(()=>validate('services',{name:'X',galleryImages:['https://evil.test/pixel']}));assert.throws(()=>validate('proposals',{name:'X',contactId:'c',lineItems:[{name:'X',quantity:1,unitPriceCents:100}],sectionOrder:['services','services','investment']}));assert.throws(()=>validate('proposals',{name:'X',contactId:'c',status:'Accepted (test only)',lineItems:[{name:'X',quantity:1,unitPriceCents:100}]}));
 const row=validate('proposals',{name:'X',contactId:'c',lineItems:[{name:'Base',quantity:2,unitPriceCents:100},{name:'Option',quantity:1,unitPriceCents:900,optional:true}],discountCents:20});assert.equal(row.totalCents,180);
});

test('invoice drafts derive totals and stable unique numbers without payment activation',async()=>{
 const {call}=fixture();const c=(await call('contacts','POST',{data:{name:'Demo',email:'demo@example.test'}})).data;const p=(await call('projects','POST',{data:{name:'Demo',contactId:c.id,eventType:'Wedding',status:'Planning'}})).data;
 const data={name:'Itemized draft',projectId:p.id,status:'Draft',lineItems:[{name:'Coverage',quantity:2,unitPriceCents:10000,sourceKind:'custom'}],discountCents:2000,taxCents:900,amountCents:1,paymentHistory:[{date:'2026-10-05',amountCents:5000,reference:'Manual demo'}]};
 const a=await call('invoices','POST',{data});assert.equal(a.status,201);assert.equal(a.data.subtotalCents,20000);assert.equal(a.data.amountCents,18900);assert.equal(a.data.remainingCents,13900);assert.match(a.data.invoiceNumber,/^GL-DRAFT-/);assert.match(a.data.issueAt,/^\d{4}-\d{2}-\d{2}$/);
 const b=await call('invoices','POST',{data});assert.notEqual(a.data.invoiceNumber,b.data.invoiceNumber);const edit=await call('invoices/'+a.data.id,'PUT',{data,version:1});assert.equal(edit.data.invoiceNumber,a.data.invoiceNumber);
 for(const bad of [{taxCents:-1},{discountCents:20001},{status:'Sent'},{invoiceNumber:'forged'},{lineItems:[{...data.lineItems[0],optional:true}]},{paymentHistory:[{date:'2026-10-05',amountCents:18901,reference:'Too much'}]}])assert.equal((await call('invoices','POST',{data:{...data,...bad}})).status,400);
 assert.equal(validate('invoices',{name:'Legacy',projectId:p.id,amountCents:500,lineItems:[]}).remainingCents,500);
});

test('Phase 2 inquiry conversion, PDF baseline isolation, trusted DEMO selection and revocation',async()=>{
 const {call,env}=fixture();env.CRM_STAGE='preview';env.CRM_ORIGIN='https://preview.example.workers.dev';
 await call('seed','POST',{});
 const inquiry={reference:'phase2-synthetic-review',data:{name:'DEMO Jamie + Taylor',email:'phase2@example.test',eventType:'Wedding',venue:'DEMO venue',message:'DEMO only inquiry',tags:'preview-review'}};
 assert.equal((await call('preview-inquiry','POST',{...inquiry,data:{...inquiry.data,email:'real@example.com'}})).status,400);
 const lead=(await call('preview-inquiry','POST',inquiry)).data;assert(lead.id);assert.equal((await call('preview-inquiry','POST',inquiry)).data.id,lead.id);assert.equal((await call('leads')).data.length,1);
 const converted=await call('leads/'+lead.id+'/convert','POST',{version:lead.version});assert.equal(converted.status,201);const project=(await call('projects')).data[0];assert.equal(project.tags,'preview-review');assert.equal(project.status,'Inquiry');assert(project.notes.includes('DEMO only inquiry'));assert.equal((await call('leads/'+lead.id)).data.projectId,project.id);assert.equal((await call('leads/'+lead.id+'/convert','POST',{version:lead.version})).status,409);
 assert.equal((await call('setup-active-packages','POST',{})).status,200);await call('setup-active-packages','POST',{});const packs=(await call('packages')).data;assert.equal(packs.length,10);assert.equal(packs.find(p=>p.id==='baseline-wedding-cinema').priceCents,315000);assert.equal(packs.find(p=>p.id==='baseline-sweet-photo').priceCents,165000);
 const original=packs[0],{id,version,createdAt,updatedAt,baseline,sourceCategory,...editable}=original;assert.equal((await call('packages/'+id,'PUT',{version,data:editable})).status,400);assert.equal((await call('packages','POST',{data:{...editable,name:'DEMO editable copy'}})).status,201);
 const made=await call('projects/'+project.id+'/proposal','POST',{version:project.version,packageIds:['baseline-wedding-cinema','baseline-wedding-micro-cinema','baseline-wedding-photo']});assert.equal(made.status,201);let p=made.data;assert.equal(p.totalCents,545000);assert.equal(p.clientSelection,true);assert(p.catalogSnapshot.length>3);
 const published=await call('proposals/'+p.id+'/share','POST',{version:p.version,action:'create'});assert.equal(published.status,200);const opened=await worker.fetch(new Request(published.data.url),env);assert.equal(opened.status,200);assert((await call('activity')).data.some(a=>a.action==='demo-proposal-viewed'));const url=published.data.url+'/selection';
 const read=()=>worker.fetch(new Request(url),env);let response=await read();assert.equal(response.status,200);let selection=await response.json();assert.equal(selection.totalCents,545000);
 const post=async body=>{const r=await worker.fetch(new Request(url,{method:'POST',headers:{Origin:env.CRM_ORIGIN,'Content-Type':'application/json','X-GioLina-Request':'demo-selection'},body:JSON.stringify(body)}),env);return {status:r.status,data:await r.json()};};
 assert.equal((await post({selected:[1,2],version:selection.version,price:1})).status,400);assert.equal((await post({selected:[0,1,2],version:selection.version})).status,400);assert.equal((await post({selected:[1,2,3],version:selection.version})).status,400);assert.equal((await post({selected:[1,2],version:999})).status,409);
 const picked=await post({selected:[1,2],version:selection.version});assert.equal(picked.status,200);assert.equal(picked.data.totalCents,400000);assert.equal((await (await read()).json()).totalCents,400000);assert.equal((await post({selected:[0,2],version:selection.version})).status,409);
 assert.equal((await call('invoices')).data.length,0);assert((await call('activity')).data.some(a=>a.action==='demo-selection-changed'));
 const removed=await post({selected:[],version:picked.data.version});assert.equal(removed.status,200);assert.equal(removed.data.totalCents,0);assert.deepEqual((await (await read()).json()).selected,[]);assert((await call('activity')).data.some(a=>a.action==='demo-selection-changed'&&JSON.parse(a.details).removed?.length===2));const restored=await post({selected:[0,2,3],version:removed.data.version});assert.equal(restored.status,200);assert.equal(restored.data.totalCents,655000);assert.equal((await (await read()).json()).totalCents,655000);
 const source=(await call('services/hb-0-01')).data;const {id:si,version:sv,createdAt:sc,updatedAt:su,...sd}=source;await call('services/'+si,'PUT',{version:sv,data:{...sd,clientDescription:'CHANGED MASTER COPY',priceCents:999999}});
 const {id:pi,version:pv,createdAt:pc,updatedAt:pu,subtotalCents:ps,totalCents:pt,catalogSnapshot:cs,...pd}=p;const changed=await call('proposals/'+pi,'PUT',{version:pv,data:{...pd,notes:'Private note'}});assert.equal(changed.status,200);assert.equal(changed.data.catalogSnapshot.find(s=>s.id==='hb-0-01').priceCents,315000);
 assert.equal((await call('proposals/'+pi+'/share','POST',{version:changed.data.version,action:'disable'})).status,200);assert.equal((await read()).status,404);
});

test('lead association respects contact boundaries and carries pre-project proposal history',async()=>{
 const {call}=fixture();await call('seed','POST',{});await call('setup-active-packages','POST',{});
 const c=(await call('contacts','POST',{data:{name:'DEMO Existing',email:'existing@example.test',demo:true}})).data;
 const project=(await call('projects','POST',{data:{name:'DEMO Existing project',contactId:c.id,eventType:'Sweet Sixteen',status:'Inquiry',demo:true}})).data;
 const lead=(await call('leads','POST',{data:{name:'DEMO pre-project lead',email:c.email,eventType:'Sweet Sixteen',status:'New',demo:true}})).data;
 const draft=(await call('leads/'+lead.id+'/proposal','POST',{version:lead.version,packageIds:['baseline-sweet-photo']})).data;assert(draft.id);assert.equal(draft.projectId,null);
 const other=(await call('contacts','POST',{data:{name:'DEMO Other',email:'other@example.test',demo:true}})).data;
 const wrong=(await call('projects','POST',{data:{name:'DEMO wrong project',contactId:other.id,eventType:'Sweet Sixteen',status:'Inquiry',demo:true}})).data;
 assert.equal((await call('leads/'+lead.id+'/convert','POST',{version:lead.version,projectId:wrong.id})).status,400);
 assert.equal((await call('leads/'+lead.id+'/convert','POST',{version:lead.version,projectId:project.id})).status,201);
 const linked=(await call('proposals/'+draft.id)).data;assert.equal(linked.projectId,project.id);assert.equal(linked.contactId,c.id);assert.equal(linked.version,2);assert.equal((await call('projects')).data.length,2);
});

test('Corporate historical baseline duplicates safely, offers allowed options and excludes private source records',async()=>{
 const {call,env}=fixture();await call('seed','POST',{});await call('setup-active-packages','POST',{});
 const master=(await call('packages/baseline-corporate-photo')).data;assert.equal(master.priceCents,160000);assert.equal(master.serviceIds[0],'corporate-2025-preferred-photo');
 const {id,version,createdAt,updatedAt,baseline,sourceCategory,...copy}=master;
 const duplicate=(await call('packages','POST',{data:{...copy,name:'DEMO Corporate customized photo',priceCents:165000,clientDescription:copy.clientDescription+' DEMO scope note.'}})).data;assert(duplicate.id);assert.equal((await call('packages/baseline-corporate-photo')).data.priceCents,160000);
 const lead=(await call('preview-inquiry','POST',{reference:'corporate-demo-review',data:{name:'DEMO Example Company',eventType:'Corporate',email:'corporate@example.test',venue:'DEMO venue'}})).data;assert(lead.id);
 const created=await call('leads/'+lead.id+'/proposal','POST',{version:lead.version,packageIds:[duplicate.id,'baseline-corporate-video']});assert.equal(created.status,201);const p=created.data;assert.equal(p.totalCents,435000);assert(p.lineItems.every(i=>i.optional||i.selectionGroupOptional));
 const shareEnv={...env,CRM_STAGE:'preview',CRM_ORIGIN:'https://preview.example.workers.dev'};const made=await api(new Request(shareEnv.CRM_ORIGIN+'/api/admin/proposals/'+p.id+'/share',{method:'POST',headers:{Origin:shareEnv.CRM_ORIGIN,'Content-Type':'application/json','X-GioLina-Request':'admin'},body:JSON.stringify({version:p.version,action:'create'})}),shareEnv,user,'proposals/'+p.id+'/share');const shared=await made.json();assert(shared.url);
 const page=await worker.fetch(new Request(shared.url),shareEnv),html=await page.text();assert(html.includes('Authorized recap examples'));assert(html.includes('hpCgs75ypG'));assert(html.includes('Complete client presentations remain private'));assert(!html.includes('PAYMENT SCHEDULE'));assert(!html.includes('Bill to'));assert(!html.includes('ozzyevents'));
 const response=await worker.fetch(new Request(shared.url+'/selection',{method:'POST',headers:{Origin:shareEnv.CRM_ORIGIN,'Content-Type':'application/json','X-GioLina-Request':'demo-selection'},body:JSON.stringify({version:1,selected:[0,1,2]})}),shareEnv);assert.equal(response.status,200);assert.equal((await response.json()).totalCents,565000);
});


test('Lead Contact reuse, Active conversion, completion and intentional archive isolation',async()=>{
 const {call,env}=fixture(),data={name:'DEMO lifecycle',firstName:'DEMO',lastName:'Lifecycle',email:'lifecycle@example.test',eventType:'Wedding',status:'New',demo:true};const lead=(await call('leads','POST',{data})).data;assert(lead.contactId);const second=(await call('leads','POST',{data:{...data,name:'DEMO second opportunity'}})).data;assert.equal(second.contactId,lead.contactId);assert.equal((await call('contacts')).data.length,1);const converted=await call('leads/'+lead.id+'/convert','POST',{version:lead.version});assert.equal(converted.status,201);const retained=(await call('leads/'+lead.id)).data;assert.equal(retained.archived,false);assert.equal(retained.lifecycle,'Active');const project=(await call('projects/'+converted.data.id)).data;assert.equal(project.contactId,lead.contactId);assert.equal(project.lifecycle,'Active');const {id,version,createdAt,updatedAt,...stored}=project;assert.equal((await call('projects/'+id,'PUT',{version,data:{...stored,lifecycle:'Finished'}})).status,200);assert.equal((await call('leads/'+lead.id)).data.lifecycle,'Finished');assert.equal((await call('leads/'+lead.id+'/convert','POST',{version:retained.version})).status,409);
 const intentional=(await call('leads','POST',{data:{...data,name:'DEMO archived'}})).data;await call('leads/'+intentional.id,'PUT',{version:1,data:{...data,contactId:lead.contactId,archived:true}});assert.equal((await call('recover-converted-leads','POST',{})).status,200);assert.equal((await call('leads/'+intentional.id)).data.archived,true);assert.deepEqual((await call('leads','GET',null,{...user,organizationId:'other'})).data,[]);assert.equal(env.CRM_DB.sqlite.prepare('SELECT COUNT(*) n FROM write_guards').get().n,0);
});

test('current template curation archives history atomically and freezes prior client proposals',async()=>{
 const {call,env}=fixture();await call('seed','POST',{});await call('setup-active-packages','POST',{});const contact=(await call('contacts','POST',{data:{name:'DEMO source review',email:'template@example.test',demo:true}})).data,project=(await call('projects','POST',{data:{name:'DEMO wedding',contactId:contact.id,eventType:'Wedding',status:'Inquiry',demo:true}})).data;
 const old=(await call('projects/'+project.id+'/proposal','POST',{version:1,packageIds:['baseline-wedding-cinema']})).data;
 const legacy=(await call('proposals','POST',{data:{name:'DEMO legacy',projectId:project.id,contactId:contact.id,demo:true,lineItems:[{name:'Original',quantity:1,unitPriceCents:315000,sourceKind:'packages',sourceId:'baseline-wedding-cinema'}]}})).data;
 env.CRM_DB.sqlite.prepare("UPDATE records SET data=json_remove(data,'$.catalogSnapshot') WHERE id=?").run(legacy.id);
 assert.equal((await call('curate-current-packages','POST',{})).status,200);const packs=(await call('packages')).data;assert.deepEqual(packs.filter(p=>!p.archived&&p.active).map(p=>p.name).sort(),['Sweet Sixteen','Wedding Cinematography','Wedding Photography']);assert.equal(packs.filter(p=>p.archived).length,10);assert.equal(packs.find(p=>p.id==='baseline-wedding-cinema').priceCents,315000);
 const recovered=(await call('proposals/'+legacy.id)).data;assert(recovered.catalogSnapshot.some(s=>s.id==='baseline-wedding-cinema'&&!s.archived));assert.equal((await call('projects/'+project.id+'/proposal','POST',{version:1,packageIds:['baseline-wedding-cinema']})).status,400);
 const {id,version,createdAt,updatedAt,catalogSnapshot,subtotalCents,totalCents,...data}=old;data.name='DEMO client-specific edit';assert.equal((await call('proposals/'+old.id,'PUT',{version:old.version,data})).status,200);
 const master=packs.find(p=>p.id==='current-wedding-cinema');const client=(await call('projects/'+project.id+'/proposal','POST',{version:1,packageIds:[master.id]})).data;const {id:mid,version:mv,createdAt:mc,updatedAt:mu,...masterData}=master;masterData.clientDescription='Future master copy';assert.equal((await call('packages/'+mid,'PUT',{version:mv,data:masterData})).status,200);await call('curate-current-packages','POST',{});assert.equal((await call('packages/'+mid)).data.clientDescription,'Future master copy');assert.notEqual((await call('proposals/'+client.id)).data.catalogSnapshot.find(s=>s.id===mid).clientDescription,'Future master copy');assert.deepEqual((await call('packages','GET',null,{...user,organizationId:'other'})).data,[]);
});
test('current Sweet Sixteen presents separate source-priced offerings and dependent add-ons',async()=>{
 const {call,env}=fixture();await call('seed','POST',{});await call('curate-current-packages','POST',{});const contact=(await call('contacts','POST',{data:{name:'DEMO sixteen',email:'sixteen@example.test',demo:true}})).data,project=(await call('projects','POST',{data:{name:'DEMO sixteen',contactId:contact.id,eventType:'Sweet Sixteen',status:'Inquiry',demo:true}})).data;const p=(await call('projects/'+project.id+'/proposal','POST',{version:1,packageIds:['current-sweet-sixteen']})).data;assert.equal(p.lineItems[0].unitPriceCents,165000);assert.equal(p.lineItems[1].unitPriceCents,180000);assert(p.lineItems[0].description.length>100);const {buildSnapshot}=await import('../proposal-share.mjs'),{selectionTotals}=await import('../selection.mjs'),{snapshot}=await buildSnapshot(env.CRM_DB,p.id);assert.equal(selectionTotals(snapshot,[0]).totalCents,165000);assert.equal(selectionTotals(snapshot,[1]).totalCents,180000);assert.equal(selectionTotals(snapshot,[0,1]).totalCents,345000);assert.equal(selectionTotals(snapshot,[]).totalCents,0);assert.deepEqual(snapshot.items[2].allowedChoices,[0]);assert.throws(()=>selectionTotals(snapshot,[1,2]));assert.equal(selectionTotals(snapshot,[0,2]).totalCents,165000+snapshot.items[2].unitPriceCents);
});
test('PDF sharing freezes invoice drafts, excludes private notes, rejects real clients and revokes links',async()=>{
 const {call,env}=fixture();Object.assign(env,{CRM_STAGE:'preview',CRM_ORIGIN:'https://preview.example.workers.dev'});const contact=(await call('contacts','POST',{data:{name:'DEMO PDF',email:'pdf@example.test',demo:true,notes:'PRIVATE CONTACT'}})).data,project=(await call('projects','POST',{data:{name:'DEMO PDF',contactId:contact.id,eventType:'Wedding',status:'Inquiry',demo:true,notes:'PRIVATE PROJECT'}})).data,invoice=(await call('invoices','POST',{data:{name:'DEMO invoice',projectId:project.id,contactId:contact.id,amountCents:100000,lineItems:[{name:'DEMO source service',description:'Client description',quantity:1,unitPriceCents:100000}],notes:'PRIVATE INVOICE',status:'Draft'}})).data;
 const draft=await call('documents/invoices/'+invoice.id+'/email-draft','POST',{});assert.equal(draft.status,201);assert.equal(draft.data.status,'Draft');assert.equal(draft.data.attachmentSnapshot.totalCents,100000);assert(!JSON.stringify(draft.data.attachmentSnapshot).includes('PRIVATE'));const {PDFDocument}=await import('pdf-lib'),{adminPDF,publicDocument}=await import('../documents.mjs');const pdf=await adminPDF(new Request('https://preview.example.workers.dev/admin/messages/'+draft.data.id+'/pdf'),env,'messages',draft.data.id);assert.equal(pdf.headers.get('Content-Type'),'application/pdf');const decoded=await PDFDocument.load(await pdf.arrayBuffer());assert(decoded.getPageCount()>=1);assert.equal(decoded.getAuthor(),'GioLina Films');assert.equal((await handlePrivate(new Request('https://preview.example.workers.dev/admin/invoices/'+invoice.id+'/pdf'),env)).status,503);
 const share=await call('invoices/'+invoice.id+'/share','POST',{action:'create',version:invoice.version});assert.equal(share.status,200);let response=await publicDocument(new Request(share.data.url),env);assert.equal(response.status,200);assert(!(await response.text()).includes('PRIVATE'));
 const data={name:'Updated',projectId:project.id,contactId:contact.id,amountCents:200000,status:'Draft'};await call('invoices/'+invoice.id,'PUT',{version:invoice.version,data});response=await publicDocument(new Request(share.data.url),env);assert((await response.text()).includes('$1,000.00'));const message=(await call('messages/'+draft.data.id)).data;assert.equal(message.attachmentSnapshot.totalCents,100000);
 assert.equal((await publicDocument(new Request(share.data.url+'/pdf'),env)).headers.get('Content-Type'),'application/pdf');assert.equal((await call('invoices/'+invoice.id+'/share','POST',{action:'disable',version:2})).status,200);assert.equal((await publicDocument(new Request(share.data.url),env)).status,404);assert.equal((await publicDocument(new Request(share.data.url+'/pdf'),env)).status,404);assert.equal((await publicDocument(new Request(share.data.url),{...env,CRM_STAGE:'production'})).status,404);
 const real=(await call('contacts','POST',{data:{name:'Example real flag',email:'real@example.test',demo:false}})).data,realProject=(await call('projects','POST',{data:{name:'Example real flag',contactId:real.id,eventType:'Wedding',status:'Inquiry',demo:false}})).data,realInvoice=(await call('invoices','POST',{data:{name:'Example',projectId:realProject.id,contactId:real.id,amountCents:100,status:'Draft'}})).data;assert.equal((await call('invoices/'+realInvoice.id+'/share','POST',{action:'create',version:1})).status,403);
});
test('DEMO project portal states, scoped documents, trusted selections and revocation fail closed',async()=>{
 const {call,env}=fixture();Object.assign(env,{CRM_STAGE:'preview',CRM_ORIGIN:'https://preview.example.workers.dev'});await call('seed','POST',{});await call('curate-current-packages','POST',{});const contact=(await call('contacts','POST',{data:{name:'DEMO Portal',email:'portal@example.test',demo:true,notes:'PRIVATE CONTACT NOTE'}})).data,project=(await call('projects','POST',{data:{name:'DEMO Portal event',contactId:contact.id,eventType:'Wedding',status:'Inquiry',demo:true,notes:'PRIVATE PROJECT NOTE',nextSteps:'PRIVATE INTERNAL ACTION'}})).data,proposal=(await call('projects/'+project.id+'/proposal','POST',{version:1,packageIds:['current-wedding-cinema']})).data,invoice=(await call('invoices','POST',{data:{name:'DEMO draft',projectId:project.id,contactId:contact.id,amountCents:315000,notes:'PRIVATE INVOICE NOTE',status:'Draft'}})).data;
 const otherContact=(await call('contacts','POST',{data:{name:'OTHER CLIENT SECRET',email:'other-portal@example.test',demo:true}})).data,otherProject=(await call('projects','POST',{data:{name:'OTHER PROJECT SECRET',contactId:otherContact.id,eventType:'Wedding',status:'Inquiry',demo:true}})).data,otherProposal=(await call('projects/'+otherProject.id+'/proposal','POST',{version:1,packageIds:['current-wedding-cinema']})).data;
 await call('messages','POST',{data:{name:'PRIVATE DRAFT MESSAGE',projectId:project.id,body:'PRIVATE BODY'}});await call('files','POST',{data:{name:'PRIVATE FILE NAME',projectId:project.id,storageKey:'PRIVATE STORAGE KEY'}});await call('files','POST',{data:{name:'DEMO explicitly shared guide',projectId:project.id,clientVisible:true,clientUrl:'https://example.test/demo-guide',storageKey:'PRIVATE SHARED STORAGE KEY'}});await call('setup-appointment-types','POST',{});await call('appointments','POST',{data:{name:'DEMO Consultation',projectId:project.id,contactId:contact.id,appointmentTypeId:'simple-appointment-0',startAt:'2027-01-06T15:00:00Z',endAt:'2027-01-06T15:30:00Z',notes:'PRIVATE APPOINTMENT NOTE',demo:true,status:'Scheduled'}});
 const accessPath='projects/'+project.id+'/portal-access';assert.equal((await call(accessPath)).data.status,'Not Invited');assert.equal((await call(accessPath,'POST',{action:'invite',version:0})).data.status,'Invited');assert.equal((await call(accessPath,'POST',{action:'activate-demo',version:0})).status,409);const active=await call(accessPath,'POST',{action:'activate-demo',version:1});assert.equal(active.status,200);const url=active.data.url;let res=await worker.fetch(new Request(url),env);assert.equal(res.status,200);let html=await res.text();assert(html.includes('NEXT STEP'));assert(html.includes('DEMO Portal'));assert(html.includes('Your documents'));assert(html.includes('Your schedule'));assert(html.includes('DEMO explicitly shared guide'));for(const forbidden of ['PRIVATE','OTHER CLIENT','OTHER PROJECT','Service Library','Activity','Draft messages'])assert(!html.includes(forbidden));assert.equal(res.headers.get('Cache-Control'),'no-store, private');assert.equal((await worker.fetch(new Request(url),{...env,CRM_STAGE:'production'})).status,404);
 const document=url+'/proposal/'+proposal.id;res=await worker.fetch(new Request(document),env);assert.equal(res.status,200);assert((await res.text()).includes('Back to your event'));assert.equal((await worker.fetch(new Request(url+'/proposal/'+otherProposal.id),env)).status,404);assert.equal((await worker.fetch(new Request(url+'/invoice/'+invoice.id+'/pdf'),env)).headers.get('Content-Type'),'application/pdf');const selection=document+'/selection',get=await worker.fetch(new Request(selection),env),info=await get.json();assert.equal(info.totalCents,315000);
 const submit=(data,origin=env.CRM_ORIGIN)=>worker.fetch(new Request(selection,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','X-GioLina-Request':'demo-selection'},body:JSON.stringify(data)}),env);assert.equal((await submit({selected:[],version:info.version},'https://evil.test')).status,403);assert.equal((await submit({selected:[],version:info.version,totalCents:1})).status,400);res=await submit({selected:[],version:info.version});assert.equal(res.status,200);assert.equal((await res.json()).totalCents,0);assert.equal((await submit({selected:[0],version:info.version})).status,409);const saved=await (await worker.fetch(new Request(selection),env)).json();assert.deepEqual(saved.selected,[]);assert.equal((await submit({selected:[0],version:saved.version})).status,200);
 const beforeRevoke=(await call(accessPath)).data;assert.equal((await call(accessPath,'POST',{action:'disable',version:beforeRevoke.version})).data.status,'Disabled');for(const link of [url,document,document+'/pdf',selection,url+'/invoice/'+invoice.id+'/pdf'])assert.equal((await worker.fetch(new Request(link),env)).status,404);
 const disabled=(await call(accessPath)).data;await call(accessPath,'POST',{action:'reenable',version:disabled.version});const invited=(await call(accessPath)).data;assert.equal(invited.status,'Invited');const renewed=(await call(accessPath,'POST',{action:'activate-demo',version:invited.version})).data;assert.notEqual(renewed.url,url);assert.equal((await worker.fetch(new Request(renewed.url),env)).status,200);assert.equal((await worker.fetch(new Request(url),env)).status,404);
 await call('contacts/'+contact.id,'PUT',{version:contact.version,data:{name:contact.name,email:'new-identity@example.test',demo:true}});assert.equal((await worker.fetch(new Request(renewed.url),env)).status,404);assert.equal((await call(accessPath)).data.status,'Disabled');assert.equal(env.CRM_DB.sqlite.prepare('SELECT COUNT(*) n FROM write_guards').get().n,0);assert.equal((await call(accessPath,'POST',{action:'invite',version:0},user,{Origin:'https://evil.test'})).status,403);
 const real=(await call('contacts','POST',{data:{name:'Non-demo example',email:'real-example@example.test',demo:false}})).data,realProject=(await call('projects','POST',{data:{name:'Non-demo',contactId:real.id,eventType:'Wedding',status:'Inquiry',demo:false}})).data;assert.equal((await call('projects/'+realProject.id+'/portal-access','POST',{action:'invite',version:0})).status,403);assert.equal((await call(accessPath,'GET',null,{...user,organizationId:'other'})).status,404);
});

test('business settings are versioned, organization-scoped and preserve mandatory alerts',async()=>{
 const {call}=fixture();const first=await call('business-settings');assert.equal(first.data.version,0);const data={...first.data.data,signature:'Frank\nGioLina Films',invoiceTaxRate:8.25,invoiceTaxPresets:[{name:'Demo rate',rate:8.25}]};const saved=await call('business-settings','PUT',{data,version:0});assert.equal(saved.status,200);assert.equal(saved.data.version,1);assert.equal((await call('business-settings','PUT',{data,version:0})).status,409);assert.equal((await call('business-settings','GET',null,{...user,organizationId:'other'})).data.data.signature,'');assert.equal((await call('business-settings','PUT',{data:{...data,notifications:{...data.notifications,security:false}},version:1})).status,409);assert.equal((await call('business-settings')).data.data.signature,'Frank\nGioLina Films');
});
test('invoice percentages, fixed discounts, tax rounding and schedules use server calculations',()=>{
 const base={name:'DEMO invoice',projectId:'p',lineItems:[{name:'Demo package',quantity:3,unitPriceCents:10001,sourceKind:'custom'}],discountMode:'percentage',discountPercent:10,taxMode:'percentage',taxRate:8.25,amountCents:1,status:'Draft'};const out=validate('invoices',base);assert.equal(out.subtotalCents,30003);assert.equal(out.discountCents,3000);assert.equal(out.taxCents,2228);assert.equal(out.amountCents,29231);assert.equal(out.remainingCents,29231);assert.throws(()=>validate('invoices',{...base,scheduleComplete:true,installments:[{label:'Deposit',dueAt:'2027-01-01',amountCents:10000}]}),/equal/);assert.equal(validate('invoices',{...base,scheduleComplete:true,installments:[{label:'Deposit',dueAt:'2027-01-01',amountCents:10000},{label:'Final balance',dueAt:'2027-02-01',amountCents:19231}],paymentHistory:[{date:'2026-10-06',amountCents:10000,reference:'DEMO manual'}]}).remainingCents,19231);assert.equal(validate('invoices',{...base,discountMode:'fixed',discountCents:5000,taxMode:'none'}).amountCents,25003);assert.throws(()=>validate('invoices',{...base,discountPercent:101}));assert.throws(()=>validate('invoices',{...base,taxRate:8.255}));assert.throws(()=>validate('invoices',{...base,discountMode:'fixed',discountCents:50000}));assert.throws(()=>validate('invoices',{...base,lineItems:[],discountPercent:10}));
});
test('contract templates merge project data, preserve required fields and keep signing inactive',async()=>{
 const {contractDocument,contractHTML,mergeContract}=await import('../contracts.mjs');const {call,env}=fixture();const contact=(await call('contacts','POST',{data:{name:'DEMO Client',partnerName:'DEMO Partner',email:'contract@example.test',demo:true}})).data;const project=(await call('projects','POST',{data:{name:'DEMO Contract event',contactId:contact.id,eventType:'Wedding',eventDate:'2027-05-12',venue:'DEMO venue',priceCents:315000,status:'Inquiry',demo:true}})).data;const template=(await call('templates','POST',{data:{name:'DEMO contract template',subject:'Draft agreement',templateType:'contract',body:'DEMO ONLY {{clientName}} / {{partnerName}} / {{eventDate}} / {{venue}} / {{price}} / {{services}}',requiredMergeFields:'clientName,services',signatureFields:'Client signature — inactive'}})).data;const contract=(await call('contracts','POST',{data:{name:'DEMO contract',projectId:project.id,contactId:contact.id,contractTemplateId:template.id,body:template.body,requiredMergeFields:template.requiredMergeFields,signatureFields:template.signatureFields,status:'Draft',reviewState:'Viewed'}})).data;assert(contract.id);const doc=await contractDocument(env.CRM_DB,contract.id);assert(doc.body.includes('DEMO Client'));assert(doc.body.includes('$3,150.00'));assert.deepEqual(doc.missingFields,['services']);assert(contractHTML({...doc,body:'<script>alert(1)</script>'},'/pdf').includes('&lt;script&gt;'));assert.equal(mergeContract('Hi {{missing}}',{},null).missing[0],'missing');assert.equal((await call('contracts','POST',{data:{name:'binding',projectId:project.id,status:'Signed'}})).status,400);const real=(await call('projects','POST',{data:{name:'Private draft',contactId:contact.id,eventType:'Wedding',status:'Inquiry'}})).data;assert.equal((await call('contracts','POST',{data:{name:'Unsafe simulation',projectId:real.id,status:'Draft',reviewState:'Signed'}})).status,403);
});
test('PDF email drafts populate recipient/signature and preserve the frozen attachment on edit',async()=>{
 const {call,env}=fixture();const contact=(await call('contacts','POST',{data:{name:'DEMO Person',email:'draft@example.test',demo:true}})).data;const project=(await call('projects','POST',{data:{name:'DEMO email project',contactId:contact.id,eventType:'Wedding',status:'Inquiry',demo:true}})).data;const initial=(await call('business-settings')).data;await call('business-settings','PUT',{version:0,data:{...initial.data,signature:'Frank\nGioLina Films'}});const invoice=(await call('invoices','POST',{data:{name:'DEMO invoice',projectId:project.id,lineItems:[{name:'Sample',description:'Long marketing prose omitted from client invoice',quantity:1,unitPriceCents:10000,sourceKind:'custom'}],status:'Draft'}})).data;const draft=await call('documents/invoices/'+invoice.id+'/email-draft','POST',{});assert.equal(draft.status,201);assert.equal(draft.data.to,'draft@example.test');assert.equal(draft.data.signature,'Frank\nGioLina Films');assert.equal(draft.data.attachmentSnapshot.items[0].description,'');const edited=await call('messages/'+draft.data.id,'PUT',{version:1,data:{name:'Edited subject',projectId:project.id,to:'draft@example.test',subject:'Edited subject',body:'Editable draft',signature:'Frank',includeSignature:false,status:'Draft'}});assert.equal(edited.status,200);assert.deepEqual(edited.data.attachmentSnapshot,draft.data.attachmentSnapshot);assert.equal(edited.data.includeSignature,false);const other=(await call('projects','POST',{data:{name:'Other DEMO',contactId:contact.id,eventType:'Wedding',status:'Inquiry',demo:true}})).data;assert.equal((await call('messages/'+draft.data.id,'PUT',{version:2,data:{name:'Wrong project',projectId:other.id,status:'Draft'}})).status,400);assert(!env.CRM_DB.sqlite.prepare("SELECT action FROM audit_events WHERE action LIKE '%sent%'").get());
});
test('contract shares are DEMO-only, escaped, revocable and contain frozen drafts',async()=>{
 const {publicDocument,adminPDF}=await import('../documents.mjs');const {call,env}=fixture();env.CRM_STAGE='preview';env.CRM_ORIGIN='https://preview.example.workers.dev';const c=(await call('contacts','POST',{data:{name:'DEMO contract',email:'contract@example.test',demo:true}})).data,p=(await call('projects','POST',{data:{name:'DEMO project',contactId:c.id,eventType:'Wedding',status:'Inquiry',demo:true}})).data,contract=(await call('contracts','POST',{data:{name:'DEMO draft',projectId:p.id,body:'DEMO for {{clientName}}',status:'Draft'}})).data;const shared=await call('contracts/'+contract.id+'/share','POST',{action:'create',version:1});assert.equal(shared.status,200);const res=await publicDocument(new Request(shared.data.url),env);assert.equal(res.status,200);assert((await res.text()).includes('No signatures are collected'));const pdf=await adminPDF(new Request(env.CRM_ORIGIN+'/admin/contracts/'+contract.id+'/pdf'),env,'contracts',contract.id);assert.equal(pdf.headers.get('Content-Type'),'application/pdf');assert((await pdf.arrayBuffer()).byteLength>1000);await call('contracts/'+contract.id+'/share','POST',{action:'disable',version:1});assert.equal((await publicDocument(new Request(shared.data.url),env)).status,404);
});

test('project-home portal includes contract drafts, keeps resend access and explicitly refreshes snapshots',async()=>{
 const {call,env}=fixture();Object.assign(env,{CRM_STAGE:'preview',CRM_ORIGIN:'https://preview.example.workers.dev'});const contact=(await call('contacts','POST',{data:{name:'DEMO Project Home',email:'home@example.test',demo:true}})).data,project=(await call('projects','POST',{data:{name:'DEMO Project Home',contactId:contact.id,eventType:'Wedding',venue:'DEMO venue',location:'DEMO location',status:'Inquiry',demo:true,notes:'PRIVATE NOTE'}})).data;const route='projects/'+project.id+'/portal-access';await call(route,'POST',{action:'invite',version:0});let active=(await call(route,'POST',{action:'activate-demo',version:1})).data;let html=await(await worker.fetch(new Request(active.url),env)).text();for(const id of ['overview','documents','schedule','payments','files'])assert(html.includes('id="'+id+'"'));assert(html.includes('DEMO location'));assert(!html.includes('PRIVATE NOTE'));const contractData={name:'DEMO contract',projectId:project.id,body:'DEMO draft for {{clientName}}',status:'Draft',notes:'PRIVATE CONTRACT NOTE'};const contract=(await call('contracts','POST',{data:contractData})).data;assert.equal((await worker.fetch(new Request(active.url+'/contract/'+contract.id),env)).status,404);let info=(await call(route)).data;const resent=await call(route,'POST',{action:'resend',version:info.version});assert.equal(resent.data.status,'Active');assert.equal(resent.data.url,active.url);info=(await call(route)).data;assert.equal((await call(route,'POST',{action:'refresh-documents',version:info.version})).status,200);const contractUrl=active.url+'/contract/'+contract.id;const preview=await worker.fetch(new Request(contractUrl),env);assert.equal(preview.status,200);html=await preview.text();assert(html.includes('DEMO draft for DEMO Project Home'));assert(!html.includes('PRIVATE CONTRACT NOTE'));assert(html.includes('Back to your event'));assert.equal((await worker.fetch(new Request(contractUrl+'/pdf'),env)).headers.get('Content-Type'),'application/pdf');await call('contracts/'+contract.id,'PUT',{version:1,data:{...contractData,body:'Updated DEMO draft'}});assert((await(await worker.fetch(new Request(contractUrl),env)).text()).includes('DEMO draft for'));const current=(await call(route)).data;await call(route,'POST',{action:'disable',version:current.version});assert.equal((await worker.fetch(new Request(contractUrl),env)).status,404);assert.equal((await call(route,'POST',{action:'refresh-documents',version:current.version+1})).status,409);
});

test('tasks persist status, trusted completion time, project identity, reopen and organization isolation',async()=>{
 const {call}=fixture();const contact=(await call('contacts','POST',{data:{name:'DEMO Task Client',email:'task@example.test',demo:true}})).data,other=(await call('contacts','POST',{data:{name:'Other',email:'other@example.test',demo:true}})).data,project=(await call('projects','POST',{data:{name:'DEMO Task Project',contactId:contact.id,eventType:'Wedding',status:'Inquiry',demo:true}})).data;
 const create=await call('tasks','POST',{data:{name:'Call client',projectId:project.id,status:'TO DO',priority:'High',dueAt:'2027-01-10',notes:'Demo only'}});assert.equal(create.status,201);const row=create.data;assert.equal(row.contactId,contact.id);assert.equal(row.demo,true);assert.equal(row.completed,false);assert.equal(row.completedAt,null);
 const data={name:row.name,projectId:project.id,status:'IN PROGRESS',priority:'High',dueAt:row.dueAt};let saved=await call('tasks/'+row.id,'PUT',{version:row.version,data});assert.equal(saved.status,200);assert.equal(saved.data.completed,false);
 saved=await call('tasks/'+row.id,'PUT',{version:saved.data.version,data:{...data,status:'DONE'}});assert.equal(saved.data.completed,true);assert(Number.isFinite(Date.parse(saved.data.completedAt)));const timestamp=saved.data.completedAt;
 const again=await call('tasks/'+row.id,'PUT',{version:saved.data.version,data:{...data,status:'DONE',notes:'Done note'}});assert.equal(again.data.completedAt,timestamp);
 const history=(await call('activity?project='+project.id)).data;assert.equal(history.filter(a=>a.action==='task-completed').length,1);
 saved=await call('tasks/'+row.id,'PUT',{version:again.data.version,data:{...data,status:'TO DO'}});assert.equal(saved.data.completedAt,null);assert.equal(saved.data.completed,false);
 assert.equal((await call('tasks/'+row.id,'PUT',{version:1,data})).status,409);assert.equal((await call('tasks','POST',{data:{...data,contactId:other.id}})).status,400);assert.equal((await call('tasks','POST',{data:{...data,status:'Fake'}})).status,400);assert.equal((await call('tasks','POST',{data:{...data,completedAt:'2020-01-01'}})).status,400);
 assert.deepEqual((await call('tasks','GET',null,{...user,organizationId:'other-org'})).data,[]);
 saved=await call('tasks/'+row.id,'PUT',{version:saved.data.version,data:{...data,archived:true}});assert.equal(saved.data.archived,true);
});

test('same client and dated event conversion requires association instead of duplicate Project',async()=>{
 const {call}=fixture();const base={name:'DEMO Repeat Inquiry',firstName:'DEMO',partnerName:'Partner',email:'repeat@example.test',phone:'555-0100',eventType:'Wedding',eventDate:'2027-06-12',venue:'Demo venue',location:'Demo location',message:'Original inquiry',notes:'Private note',leadSource:'Preview intake',status:'New',demo:true};
 const a=(await call('leads','POST',{data:base})).data,b=(await call('leads','POST',{data:{...base,name:'Second inquiry'}})).data;assert.equal(a.contactId,b.contactId);assert.equal((await call('contacts')).data.length,1);
 const converted=await call('leads/'+a.id+'/convert','POST',{version:a.version});assert.equal(converted.status,201);const project=(await call('projects/'+converted.data.id)).data;assert(project.notes.includes('Original inquiry'));assert(project.notes.includes('Private note'));assert.equal(project.venue,base.venue);assert.equal(project.location,base.location);assert.equal(project.leadSource,base.leadSource);
 assert.equal((await call('leads/'+a.id+'/convert','POST',{version:a.version})).status,409);assert.equal((await call('leads/'+b.id+'/convert','POST',{version:b.version})).status,409);assert.equal((await call('projects')).data.length,1);
 assert.equal((await call('leads/'+b.id+'/convert','POST',{version:b.version,projectId:project.id})).status,201);assert.equal((await call('projects')).data.length,1);assert.equal((await call('contacts')).data.length,1);assert((await call('activity?project='+project.id)).data.some(a=>a.action==='lead-associated'));
});

test('communication contact association is trusted, Draft only, and invoice changes create specific audit entries',async()=>{
 const {call}=fixture();const contact=(await call('contacts','POST',{data:{name:'DEMO History',email:'history@example.test'}})).data,project=(await call('projects','POST',{data:{name:'DEMO History Project',contactId:contact.id,eventType:'Wedding',status:'Inquiry'}})).data;
 const draft=await call('messages','POST',{data:{name:'Planning draft',projectId:project.id,subject:'Planning',body:'Demo draft'}});assert.equal(draft.status,201);assert.equal(draft.data.contactId,contact.id);assert.equal(draft.data.status,'Draft');assert(draft.data.createdAt);assert.equal((await call('messages','POST',{data:{name:'Fake sent',projectId:project.id,status:'Sent'}})).status,400);
 const invoice=(await call('invoices','POST',{data:{name:'DEMO Bill',projectId:project.id,amountCents:100000}})).data;
 const update=await call('invoices/'+invoice.id,'PUT',{version:invoice.version,data:{name:invoice.name,projectId:project.id,amountCents:100000,paymentHistory:[{date:'2026-10-06',amountCents:20000,reference:'DEMO manual'}],installments:[{label:'Balance',dueAt:'2027-01-01',amountCents:100000}],scheduleComplete:true}});assert.equal(update.status,200);assert.equal(update.data.remainingCents,80000);
 const actions=(await call('activity?project='+project.id)).data.map(a=>a.action);assert(actions.includes('manual-payment-history-updated'));assert(actions.includes('payment-schedule-updated'));assert(actions.includes('created'));
});

test('document workflow state audits are explicit and signing/delivery stay inactive',async()=>{
 const {call}=fixture();const contact=(await call('contacts','POST',{data:{name:'DEMO States',email:'states@example.test',demo:true}})).data,project=(await call('projects','POST',{data:{name:'DEMO States',contactId:contact.id,eventType:'Wedding',status:'Inquiry',demo:true}})).data;
 const contract=(await call('contracts','POST',{data:{name:'DEMO Contract',projectId:project.id,status:'Draft',reviewState:'Draft'}})).data;
 const updated=await call('contracts/'+contract.id,'PUT',{version:contract.version,data:{name:contract.name,projectId:project.id,status:'Draft',reviewState:'Viewed'}});assert.equal(updated.status,200);assert.equal(updated.data.status,'Draft');const activity=(await call('activity?project='+project.id)).data,entry=activity.find(a=>a.action==='demo-document-state-changed');assert(entry);assert.deepEqual(JSON.parse(entry.details),{from:'Draft',to:'Viewed',simulation:true});assert.equal((await call('contracts/'+contract.id,'PUT',{version:updated.data.version,data:{name:contract.name,projectId:project.id,status:'Signed'}})).status,400);
 const invoice=(await call('invoices','POST',{data:{name:'DEMO Invoice',projectId:project.id,amountCents:100}})).data;assert.equal((await call('invoices/'+invoice.id,'PUT',{version:invoice.version,data:{name:invoice.name,projectId:project.id,amountCents:100,status:'Sent'}})).status,400);
});

test('connected DEMO Lead to Project document/PDF/portal/scheduler QA preserves context and resets links',async()=>{
 const {call,env}=fixture();Object.assign(env,{CRM_STAGE:'preview',CRM_ORIGIN:'https://preview.example.workers.dev'});await call('seed','POST',{});await call('curate-current-packages','POST',{});
 const lead=(await call('leads','POST',{data:{name:'DEMO Connected QA',firstName:'DEMO Jamie',partnerName:'DEMO Taylor',email:'connected@example.test',eventType:'Wedding',eventDate:'2027-06-10',venue:'DEMO Garden',message:'DEMO inquiry',notes:'PRIVATE INQUIRY NOTE',status:'New',demo:true}})).data;
 const converted=await call('leads/'+lead.id+'/convert','POST',{version:lead.version});assert.equal(converted.status,201);const project=(await call('projects/'+converted.data.id)).data;
 const proposal=(await call('projects/'+project.id+'/proposal','POST',{version:project.version,packageIds:['current-wedding-cinema']})).data;assert.equal(proposal.projectId,project.id);assert(proposal.clientNames.includes('DEMO Taylor'));assert.equal(proposal.totalCents,315000);
 const contract=(await call('contracts','POST',{data:{name:'DEMO Connected Contract',projectId:project.id,body:'DEMO ONLY {{clientName}} / {{partnerName}} / {{eventDate}} / {{venue}}',status:'Draft',reviewState:'Draft'}})).data;
 const invoice=(await call('invoices','POST',{data:{name:'DEMO Connected Invoice',projectId:project.id,amountCents:0,lineItems:[{name:'Feature Film',quantity:1,unitPriceCents:315000}],discountMode:'percentage',discountPercent:10,taxMode:'none',installments:[{label:'Retainer',dueAt:'2026-12-01',amountCents:100000},{label:'Final',dueAt:'2027-06-01',amountCents:183500}],scheduleComplete:true}})).data;assert.equal(invoice.amountCents,283500);
 const {adminPDF,publicDocument}=await import('../documents.mjs'),{PDFDocument}=await import('pdf-lib');for(const [kind,row]of [['proposals',proposal],['contracts',contract],['invoices',invoice]]){const response=await adminPDF(new Request(env.CRM_ORIGIN+'/admin/'+kind+'/'+row.id+'/pdf'),env,kind,row.id);assert.equal(response.status,200);assert.equal(response.headers.get('Content-Type'),'application/pdf');assert((await PDFDocument.load(await response.arrayBuffer())).getPageCount()>0);const draft=(await call('documents/'+kind+'/'+row.id+'/email-draft','POST',{})).data;assert.equal(draft.projectId,project.id);assert.equal(draft.contactId,project.contactId);assert.equal(draft.to,'connected@example.test');assert.equal(draft.status,'Draft');assert(draft.attachmentSnapshot);}
 const first=(await call('invoices/'+invoice.id+'/share','POST',{action:'create',version:invoice.version})).data;assert.equal((await publicDocument(new Request(first.url),env)).status,200);const reset=(await call('invoices/'+invoice.id+'/share','POST',{action:'regenerate',version:invoice.version})).data;assert.notEqual(reset.url,first.url);assert.equal((await publicDocument(new Request(first.url),env)).status,404);assert.equal((await publicDocument(new Request(reset.url),env)).status,200);
 await call('setup-appointment-types','POST',{});const appointment=await call('appointments','POST',{data:{name:'DEMO Planning Call',projectId:project.id,contactId:project.contactId,appointmentTypeId:'simple-appointment-1',startAt:'2027-01-06T15:00:00Z',endAt:'2027-01-06T15:30:00Z',status:'Scheduled',demo:true}});assert.equal(appointment.status,201);assert.equal(appointment.data.projectId,project.id);
 const route='projects/'+project.id+'/portal-access';await call(route,'POST',{action:'invite',version:0});const active=(await call(route,'POST',{action:'activate-demo',version:1})).data;const portal=await worker.fetch(new Request(active.url),env);assert.equal(portal.status,200);const html=await portal.text();assert(html.includes('DEMO Jamie'));assert(html.includes('DEMO Taylor'));assert(html.includes('DEMO Garden'));assert(!html.includes('PRIVATE INQUIRY NOTE'));assert.equal((await worker.fetch(new Request(active.url+'/invoice/'+invoice.id+'/pdf'),env)).status,200);
 const info=(await call(route)).data;await call(route,'POST',{action:'disable',version:info.version});assert.equal((await worker.fetch(new Request(active.url),env)).status,404);assert.equal(env.CRM_DB.sqlite.prepare('SELECT COUNT(*) n FROM write_guards').get().n,0);
});

test('editing a legacy completed reminder does not invent a completion timestamp',async()=>{
 const {call,env}=fixture();const now='2026-01-01T00:00:00Z';env.CRM_DB.sqlite.prepare('INSERT INTO records(organization_id,kind,id,data,created_at,updated_at) VALUES(?,?,?,?,?,?)').run(user.organizationId,'tasks','legacy-done',JSON.stringify({name:'DEMO old reminder',completed:true,demo:true}),now,now);
 const saved=await call('tasks/legacy-done','PUT',{version:1,data:{name:'DEMO old reminder',status:'DONE',completed:true,demo:true,notes:'Edited only'}});assert.equal(saved.status,200);assert.equal(saved.data.completedAt,null);assert.equal((await call('activity')).data.filter(e=>e.action==='task-completed').length,0);
});
