import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {JSDOM} from 'jsdom';
import {shell} from '../shell.mjs';
import {definitions} from '../model.mjs';
const code=readFileSync(new URL('../client.js',import.meta.url),'utf8');
async function settled(check){for(let i=0;i<100;i++){if(check())return;await new Promise(r=>setTimeout(r,5));}assert.fail('UI did not settle');}
function mount(path='/admin/',extra={}){const calls=[],rows={contacts:[{id:'c',version:1,name:'<img src=x onerror=alert(1)>',email:'demo@example.test',demo:true}],services:[],projects:[],leads:[],appointments:[],tasks:[],...extra};const dom=new JSDOM(shell,{url:'https://example.workers.dev'+path,runScripts:'outside-only'});const w=dom.window;w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open')};w.fetch=async(url,options={})=>{const route=url.slice('/api/admin/'.length),[kind,id]=route.split('/');calls.push({route,...options});let data=route==='meta'?{definitions,email:'admin@example.test'}:route==='activity'?[]:rows[kind]||[];if(options.method==='POST'){const input=JSON.parse(options.body);const record={...input.data,id:'new',version:1};rows[kind]=[...(rows[kind]||[]),record];data=record;}return {ok:true,json:async()=>data};};w.eval(code);return {dom,w,calls,rows};}
test('dashboard has all 15 navigation areas and real empty totals',async()=>{const {w,dom}=mount();await settled(()=>w.document.querySelector('h1')?.textContent==='Your workspace');assert.equal(w.document.querySelectorAll('nav a').length,15);assert.equal(w.document.querySelectorAll('.metric').length,9);assert(!w.document.body.textContent.includes('Awaiting signature: 3'));dom.window.close();});
test('contact editor saves structured data and renders hostile text safely',async()=>{const {w,dom,calls}=mount('/admin/contacts/');await settled(()=>w.document.querySelector('td strong'));assert.equal(w.document.querySelector('td strong').textContent,'<img src=x onerror=alert(1)>');assert.equal(w.document.querySelectorAll('td img').length,0);Array.from(w.document.querySelectorAll('button')).find(b=>b.textContent==='New record').click();await settled(()=>w.document.querySelector('dialog[open]'));w.document.querySelector('[name=name]').value='Safe demo';w.document.querySelector('[name=email]').value='safe@example.test';w.document.querySelector('[name=demo]').checked=true;w.document.querySelector('#record-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await settled(()=>calls.some(c=>c.method==='POST'));const save=calls.find(c=>c.method==='POST');assert.equal(JSON.parse(save.body).data.demo,true);assert.equal(save.headers['X-GioLina-Request'],'admin');dom.window.close();});
test('calendar, service editor and portal foundation are reachable',async()=>{for(const [route,title]of [['calendar','Calendar / Scheduler'],['services','Services & Packages'],['client-portal','Client Portal preview'],['templates','Email Templates'],['settings','Settings']]){const {w,dom}=mount('/admin/'+route+'/');await settled(()=>w.document.querySelector('h1')?.textContent===title);assert(w.document.querySelector('nav a[aria-current=page]'));if(route==='services')assert(w.document.body.textContent.includes('Import supplied catalog'));if(route==='client-portal')assert(w.document.body.textContent.includes('Client login and invitations are not enabled'));dom.window.close();}});


test('package editor supports touch-friendly service selection and inactive catalog filtering',async()=>{
 const {w,dom,calls}=mount('/admin/services/',{services:[{id:'s1',name:'Demo cinema',category:'Wedding 2026',catalogCategory:'Weddings / Cinematography',priceCents:315000},{id:'s2',name:'Inactive demo',active:false,priceCents:null}]});
 await settled(()=>w.document.querySelector('td strong'));const buttons=()=>Array.from(w.document.querySelectorAll('button'));
 buttons().find(b=>b.textContent==='New package').click();await settled(()=>w.document.querySelector('[name=serviceIds] input'));
 assert.equal(w.document.querySelectorAll('[name=serviceIds] input').length,1);
 w.document.querySelector('[name=name]').value='Demo package';w.document.querySelector('[name=serviceIds] input').checked=true;
 w.document.querySelector('#record-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await settled(()=>calls.some(c=>c.method==='POST'));
 assert.deepEqual(JSON.parse(calls.find(c=>c.method==='POST').body).data.serviceIds,['s1']);
 dom.window.close();
});

test('private proposal builder edits quantity and price, submits snapshots and renders safe preview',async()=>{
 const {w,dom,calls}=mount('/admin/proposals/',{projects:[{id:'p',name:'Demo job',contactId:'c'}]});await settled(()=>w.document.querySelector('h1')?.textContent==='Proposals');Array.from(w.document.querySelectorAll('button')).find(b=>b.textContent==='New record').click();await settled(()=>w.document.querySelector('.line-builder'));w.document.querySelector('[name=name]').value='Demo proposal';w.document.querySelector('[name=projectId]').value='p';Array.from(w.document.querySelectorAll('button')).find(b=>b.textContent==='Add custom item').click();w.document.querySelector('[data-part=name]').value='Demo line';w.document.querySelector('[data-part=quantity]').value='2';w.document.querySelector('[data-part=price]').value='12.50';w.document.querySelector('#record-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await settled(()=>calls.some(c=>c.method==='POST'));assert.equal(JSON.parse(calls.find(c=>c.method==='POST').body).data.lineItems[0].unitPriceCents,1250);dom.window.close();
});

test('calendar switches month, week and day without losing project events',async()=>{
 const {w,dom}=mount('/admin/calendar/',{projects:[{id:'p',name:'Demo event',eventDate:new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}]});await settled(()=>w.document.querySelector('.calendar-day'));assert.equal(w.document.querySelectorAll('.calendar-day').length,42);const buttons=()=>Array.from(w.document.querySelectorAll('button'));buttons().find(b=>b.textContent==='Week').click();assert.equal(w.document.querySelectorAll('.calendar-day').length,7);assert(w.document.querySelector('.calendar-grid').textContent.includes('Demo event'));buttons().find(b=>b.textContent==='Day').click();assert.equal(w.document.querySelectorAll('.calendar-day').length,1);dom.window.close();
});

test('portal assembles only selected project records and excludes internal project notes',async()=>{
 const {w,dom}=mount('/admin/client-portal/',{projects:[{id:'p',name:'Demo event',contactId:'c',eventType:'Wedding',status:'Booked',notes:'INTERNAL SECRET',nextSteps:'Confirm schedule'}],proposals:[{id:'proposal',name:'Demo proposal',projectId:'p',totalCents:315000}],messages:[{id:'m',name:'Other client draft',projectId:'other',body:'OTHER PROJECT PRIVATE'}]});await settled(()=>w.document.querySelector('[aria-label="Preview a project"]')?.options.length===2);const select=w.document.querySelector('[aria-label="Preview a project"]');select.value='p';select.dispatchEvent(new w.Event('change'));assert(w.document.querySelector('.portal-view').textContent.includes('Demo proposal'));assert(w.document.querySelector('.portal-view').textContent.includes('Confirm schedule'));assert(!w.document.querySelector('.portal-view').textContent.includes('INTERNAL SECRET'));assert(!w.document.querySelector('.portal-view').textContent.includes('OTHER PROJECT PRIVATE'));dom.window.close();
});

test('manual bookkeeping form uses structured dates and dollar amounts rather than JSON inputs',async()=>{
 const {w,dom,calls}=mount('/admin/invoices/',{projects:[{id:'p',name:'Demo job'}]});await settled(()=>w.document.querySelector('h1')?.textContent==='Invoices / Payments');Array.from(w.document.querySelectorAll('button')).find(b=>b.textContent==='New record').click();await settled(()=>w.document.querySelector('[name=paymentHistory]'));const history=w.document.querySelector('[name=paymentHistory]');history.querySelector('button').click();history.querySelector('[data-part=date]').value='2026-10-05';history.querySelector('[data-part=amountCents]').value='125';history.querySelector('[data-part=reference]').value='Demo manual only';w.document.querySelector('[name=name]').value='Demo plan';w.document.querySelector('[name=projectId]').value='p';w.document.querySelector('[name=amountCents]').value='500';w.document.querySelector('#record-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await settled(()=>calls.some(c=>c.method==='POST'));assert.equal(JSON.parse(calls.find(c=>c.method==='POST').body).data.paymentHistory[0].amountCents,12500);dom.window.close();
});
