import {readFileSync,writeFileSync} from 'node:fs';
const root=new URL('../',import.meta.url);
const source='// Generated by admin/scripts/build-assets.mjs. Both resources are authenticated Worker responses.\nexport const client='+JSON.stringify(readFileSync(new URL('client.js',root),'utf8'))+';\nexport const styles='+JSON.stringify(readFileSync(new URL('styles.css',root),'utf8'))+';\n';
const target=new URL('assets.mjs',root);
if(process.argv.includes('--check')){if(readFileSync(target,'utf8')!==source)throw new Error('Admin assets need rebuilding');}else writeFileSync(target,source);
