import {readSettings,saveSettings} from './business-settings.mjs';
import {contractDocument} from './contracts.mjs';
import {portalAccess} from './client-portal.mjs';
import {invoiceShare,invoiceDocument} from './documents.mjs';
import {catalogSeed as baselineServices} from './catalog.mjs';
import {initializeBaselines,curateCurrentTemplates,templateLines,currentTemplateIds} from './active-packages.mjs';
import {presentation} from './presentation.mjs';
import {seedDemoProposals} from './proposal-demos.mjs';
import {selectionTotals,defaultSelection} from './selection.mjs';
import {shareAPI,buildSnapshot} from './proposal-share.mjs';
import {templateDefaults,templateCategories,templateVariables} from './templates.mjs';
import {definitions,validate,lifecycle} from './model.mjs';
import {catalogRecord,catalogSeed,catalogCategories} from './catalog.mjs';
export function json(body,status=200){return new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store','X-Robots-Tag':'noindex, nofollow','X-Content-Type-Options':'nosniff'}});}
export async function list(db,org,kind){const r=await db.prepare('SELECT id,data,version,created_at,updated_at FROM records WHERE organization_id=? AND kind=? ORDER BY updated_at DESC LIMIT 500').bind(org,kind).all();return r.results.map(r=>{const row={...JSON.parse(r.data),id:r.id,version:r.version,createdAt:r.created_at,updatedAt:r.updated_at};return kind==='services'?catalogRecord(row):row;});}
export async function get(db,org,kind,id){const r=await db.prepare('SELECT * FROM records WHERE organization_id=? AND kind=? AND id=?').bind(org,kind,id).first();if(!r)return null;const row={...JSON.parse(r.data),id:r.id,version:r.version,createdAt:r.created_at,updatedAt:r.updated_at};return kind==='services'?catalogRecord(row):row;}
function audit(db,user,action,kind,id,details={}){return db.prepare('INSERT INTO audit_events VALUES(?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),user.organizationId,user.email,action,kind,id,new Date().toISOString(),JSON.stringify(details));}
function insert(db,org,kind,id,data){const now=new Date().toISOString();return db.prepare('INSERT INTO records(organization_id,kind,id,data,created_at,updated_at) VALUES(?,?,?,?,?,?)').bind(org,kind,id,JSON.stringify(data),now,now);}
async function references(db,org,data){for(const item of data.lineItems||[]){if(item.sourceKind!=='custom'&&!await get(db,org,item.sourceKind,item.sourceId))throw new Error('Proposal catalog item does not exist');}for(const [field,kind] of Object.entries({leadId:'leads',contactId:'contacts',projectId:'projects',packageId:'packages',templateId:'packages',appointmentTypeId:'appointment-types'})){if(data[field]&&!await get(db,org,kind,data[field]))throw new Error('Referenced '+kind+' record does not exist');}const contacts=[...new Set(data.additionalContactIds||[])];if(contacts.length){const result=await db.prepare("SELECT COUNT(*) AS count FROM records WHERE organization_id=? AND kind='contacts' AND id IN (SELECT value FROM json_each(?))").bind(org,JSON.stringify(contacts)).first();if(result.count!==contacts.length)throw new Error('Selected contact does not exist');}const ids=[...new Set([...(data.serviceIds||[]),...(data.optionalServiceIds||[])])];if(ids.length){const result=await db.prepare("SELECT COUNT(*) AS count FROM records WHERE organization_id=? AND kind='services' AND id IN (SELECT value FROM json_each(?))").bind(org,JSON.stringify(ids)).first();if(result.count!==ids.length)throw new Error('Selected service does not exist');}}
async function appointmentLocks(db,org,id,data){
 const statements=[db.prepare('DELETE FROM appointment_locks WHERE organization_id=? AND appointment_id=?').bind(org,id)];
 if(data.status==='Cancelled'||data.status==='Completed')return statements;
 const type=await get(db,org,'appointment-types',data.appointmentTypeId);const start=Date.parse(data.startAt),end=Date.parse(data.endAt),buffer=(type?.bufferMinutes||0)*60000;
 if(end-start>480*60000||end-start<5*60000)throw new Error('Appointments must last 5–480 minutes');
 const localDay=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(start));
 const availability=await list(db,org,'availability');if(availability.some(a=>a.blockedDate===localDay&&!a.archived))throw new Error('That date is blocked');
 const zone='America/New_York',weekday=new Intl.DateTimeFormat('en-US',{timeZone:zone,weekday:'long'}).format(new Date(start));const windows=availability.filter(a=>!a.archived&&!a.blockedDate);if(windows.length){const dateEnd=new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(end));const clock=time=>new Intl.DateTimeFormat('en-GB',{timeZone:zone,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(time));if(dateEnd!==localDay||!windows.some(a=>a.dayOfWeek===weekday&&new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(start-buffer))===localDay&&new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(end+buffer))===localDay&&a.startTime<=clock(start-buffer)&&a.endTime>=clock(end+buffer)))throw new Error('Appointment and buffer must fit configured availability hours');}
 const minutes=[];for(let slot=Math.floor((start-buffer)/60000);slot<Math.ceil((end+buffer)/60000);slot++)minutes.push(slot);
 statements.push(db.prepare('INSERT INTO appointment_locks(organization_id,minute,appointment_id) SELECT ?,value,? FROM json_each(?)').bind(org,id,JSON.stringify(minutes)));
 return statements;
}
export async function api(request,env,user,path){
 const db=env.CRM_DB,org=user.organizationId;
 if(!db)return json({error:'Private preview database is not connected. No records are stored.'},503);
 if(!['GET','POST','PUT'].includes(request.method))return json({error:'Method not allowed'},405);
 if(request.method!=='GET'){
  if(request.headers.get('Origin')!==new URL(request.url).origin||request.headers.get('X-GioLina-Request')!=='admin'||!request.headers.get('Content-Type')?.startsWith('application/json'))return json({error:'Invalid request origin or content type'},403);
  if(Number(request.headers.get('Content-Length')||0)>65536)return json({error:'Request too large'},413);
 }
 if(path==='business-settings'){try{if(request.method==='GET')return json(await readSettings(db,org));if(request.method!=='PUT')return json({error:'Method not allowed'},405);const raw=await request.text();if(raw.length>12000)return json({error:'Settings too large'},413);return json(await saveSettings(db,user,JSON.parse(raw)));}catch(e){return json({error:/CHECK|UNIQUE/.test(e.message)?'Settings changed. Reload before saving.':e.message},409);}}
 if(/^projects\/[^/]+\/portal-access$/.test(path))return portalAccess(request,env,user,path.split('/')[1]);
 if(/^(invoices|contracts)\/[^/]+\/share$/.test(path))return invoiceShare(request,env,user,path.split('/')[1],path.split('/')[0]);
 if(/^documents\/(proposals|invoices|contracts)\/[^/]+\/email-draft$/.test(path)&&request.method==='POST'){try{if(org!=='giolina-preview')return json({error:'Document unavailable'},404);const [,kind,id]=path.split('/'),doc=kind==='proposals'?{...(await buildSnapshot(db,id)).snapshot,type:'Proposal'}:kind==='contracts'?await contractDocument(db,id):await invoiceDocument(db,id),row=await get(db,org,kind,id);if(!row?.projectId)throw new Error('Associate this document with a Project before drafting email');const project=await get(db,org,'projects',row.projectId);if(!project||project.archived)throw new Error('Project unavailable');const contact=await get(db,org,'contacts',project.contactId),settings=(await readSettings(db,org)).data;const recordId=crypto.randomUUID(),data={to:contact?.email||null,includeSignature:settings.includeSignature,signature:settings.signature,name:'Draft email - '+doc.type,contactId:project.contactId,projectId:project.id,subject:'Your GioLina '+doc.type,body:'Hello '+doc.clientNames+',\n\nYour '+doc.type.toLowerCase()+' is prepared as a PDF for review.',status:'Draft',documentKind:kind,documentId:id,documentRevision:row.version,attachmentSnapshot:doc};await db.batch([insert(db,org,'messages',recordId,data),audit(db,user,'document-email-drafted','messages',recordId)]);return json(await get(db,org,'messages',recordId),201);}catch(e){return json({error:e.message},400);}}
 if(/^proposals\/[^/]+\/share$/.test(path))return shareAPI(request,env,user,path.split('/')[1]);
 if(/^proposals\/[^/]+\/selection-preview$/.test(path)){
  try{const {snapshot}=await buildSnapshot(db,path.split('/')[1]);if(request.method==='GET')return json({...selectionTotals(snapshot,defaultSelection(snapshot.items)),version:0});const raw=await request.text();if(raw.length>4096)return json({error:'Selection too large'},413);const input=JSON.parse(raw);return json({...selectionTotals(snapshot,input.selected),version:0});}catch(err){return json({error:err.message},400);}
 }
 if(path==='setup-demo-proposals'&&request.method==='POST'){try{return json(await seedDemoProposals(db,org,user));}catch(e){return json({error:e.message},400);}}
 if(path==='meta'&&request.method==='GET')return json({projectStages:lifecycle,presentationDefaults:{weddingPhoto:presentation({catalogCategory:'Weddings / Photography'}),wedding:presentation({eventType:'Wedding'}),sweet:presentation({eventType:'Sweet Sixteen'}),event:presentation({eventType:'Corporate'})},definitions,catalogCategories,templateCategories,templateVariables,timezone:'America/New_York',stage:'preview',email:user.email});
 if(path.split('?')[0]==='activity'&&request.method==='GET'){const project=new URL(request.url).searchParams.get('project');if(project){if(!await get(db,org,'projects',project))return json({error:'Project not found'},404);const r=await db.prepare("SELECT action,record_kind,record_id,occurred_at,details FROM audit_events WHERE organization_id=? AND (record_id=? OR record_id IN (SELECT id FROM records WHERE organization_id=? AND json_extract(data,'$.projectId')=?)) ORDER BY occurred_at ASC LIMIT 500").bind(org,project,org,project).all();return json(r.results);}const r=await db.prepare('SELECT action,record_kind,record_id,occurred_at,details FROM audit_events WHERE organization_id=? ORDER BY occurred_at DESC LIMIT 50').bind(org).all();return json(r.results);}
 if(path==='curate-current-packages'&&request.method==='POST'){try{return json(await curateCurrentTemplates(db,org,user));}catch(e){return json({error:e.message},409);}}
 if(path==='setup-active-packages'&&request.method==='POST'){try{return json(await initializeBaselines(db,org,user));}catch(e){return json({error:e.message},400);}}
 if(path==='seed'&&request.method==='POST'){
  if(await db.prepare("SELECT value FROM migration_state WHERE key='catalog-v1'").first())return json({message:'Catalog already imported; existing edits preserved.'});
  const now=new Date().toISOString();
  const operations=[db.prepare("INSERT INTO records(organization_id,kind,id,data,created_at,updated_at) SELECT ?,'services',json_extract(value,'$.id'),json_remove(value,'$.id'),?,? FROM json_each(?)").bind(org,now,now,JSON.stringify(catalogSeed))];
  operations.push(db.prepare("INSERT INTO migration_state VALUES('catalog-v1','imported')"),audit(db,user,'seed-services','services','catalog-v1'));await db.batch(operations);return json({message:'Imported '+catalogSeed.length+' source-backed service versions.'},201);
 }
 if(path==='setup-email-templates'&&request.method==='POST'){const now=new Date().toISOString();await db.batch([db.prepare("INSERT OR IGNORE INTO records(organization_id,kind,id,data,created_at,updated_at) SELECT ?,'templates',json_extract(value,'$.id'),json_remove(value,'$.id'),?,? FROM json_each(?)").bind(org,now,now,JSON.stringify(templateDefaults)),audit(db,user,'setup-templates','templates','defaults')]);return json({message:'Workflow drafts ready. Existing template edits preserved.'});}
 if(path==='recover-converted-leads'&&request.method==='POST'){
  const now=new Date().toISOString();await db.batch([db.prepare("UPDATE records SET data=json_set(data,'$.archived',json('false'),'$.lifecycle','Active'),version=version+1,updated_at=? WHERE organization_id=? AND kind='leads' AND json_extract(data,'$.archived')=1 AND json_extract(data,'$.projectId') IS NOT NULL AND (SELECT action FROM audit_events WHERE organization_id=? AND record_kind='leads' AND record_id=records.id ORDER BY occurred_at DESC LIMIT 1)='lead-project-linked'").bind(now,org,org),audit(db,user,'automatic-conversion-archive-recovered','leads','conversion-history')]);return json({message:'Automatically archived converted Leads restored. Intentional archives preserved.'});
 }
 if(path==='setup-appointment-types'&&request.method==='POST'){
  const names=['Consultation Call','Client Meeting','Planning Call','Other'];const now=new Date().toISOString();const defaults=names.map((name,i)=>({id:'simple-appointment-'+i,name,durationMinutes:30,bufferMinutes:0,description:'Editable private scheduler default; confirm duration and buffers before use.'}));await db.batch([db.prepare("INSERT OR IGNORE INTO records(organization_id,kind,id,data,created_at,updated_at) SELECT ?,'appointment-types',json_extract(value,'$.id'),json_remove(value,'$.id'),?,? FROM json_each(?)").bind(org,now,now,JSON.stringify(defaults)),audit(db,user,'setup-types','appointment-types','defaults')]);return json({message:'Appointment types ready. Existing edits preserved.'});
 }
 if(path==='preview-inquiry'&&request.method==='POST'){
  try{const raw=await request.text();if(raw.length>8192)return json({error:'Inquiry too large'},413);const input=JSON.parse(raw);
   if(!/^[a-z0-9-]{8,80}$/.test(input.reference||'')||!input.data?.email?.endsWith('@example.test'))return json({error:'Use a unique preview reference and a DEMO @example.test email'},400);
   const id='preview-inquiry-'+input.reference,existing=await get(db,org,'leads',id);if(existing)return json(existing);
   const data=validate('leads',{...input.data,demo:true,status:'New',leadSource:'Preview website simulator',inquiryDate:new Date().toISOString().slice(0,10)});await references(db,org,data);
   await db.batch([insert(db,org,'leads',id,data),audit(db,user,'preview-inquiry-created','leads',id)]);return json(await get(db,org,'leads',id),201);
  }catch{return json({error:'Invalid DEMO inquiry or duplicate request. No email was sent.'},400);}
 }
 const [kind,id,action]=path.split('/');if(!Object.hasOwn(definitions,kind))return json({error:'Not found'},404);
 if(request.method==='GET'){if(id){const record=await get(db,org,kind,id);return json(record||{error:'Not found'},record?200:404);}return json(await list(db,org,kind));}
 const text=await request.text();if(text.length>65536)return json({error:'Request too large'},413);let input;try{input=JSON.parse(text)}catch{return json({error:'Invalid JSON'},400);}
 if(['leads','projects'].includes(kind)&&id&&action==='proposal'&&request.method==='POST'){
  const context=await get(db,org,kind,id);if(!context||context.version!==input.version)return json({error:'Context changed. Reload before creating a proposal.'},409);
  if(!Array.isArray(input.packageIds)||!input.packageIds.length||input.packageIds.length>8||new Set(input.packageIds).size!==input.packageIds.length)return json({error:'Choose 1–8 active package templates'},400);
  if(await db.prepare('SELECT value FROM migration_state WHERE key=?').bind('current-selling-templates:'+org).first()&&input.packageIds.some(id=>!currentTemplateIds.includes(id)))return json({error:'Choose one of the three current selling templates'},400);
  const packs=await Promise.all(input.packageIds.map(id=>get(db,org,'packages',id))),category=context.eventType==='Wedding'?'Weddings /':context.eventType==='Sweet Sixteen'?'Sweet Sixteen /':context.eventType==='Corporate'?'Events & Corporate /':null;
  if(packs.some(p=>!p||p.archived||p.active===false||p.priceCents==null||!category||!p.catalogCategory?.startsWith(category)))return json({error:'Choose priced active packages for this event category'},400);
  let lines;try{lines=templateLines(packs,await list(db,org,'services'),context.eventType);}catch(e){return json({error:e.message},400);}
  const contact=await get(db,org,'contacts',context.contactId||''),projectId=kind==='projects'?context.id:context.projectId||null;
  const data={name:(context.demo?'DEMO draft — ':'Draft — ')+context.name,projectId,contactId:context.contactId||null,leadId:kind==='leads'?id:null,templateId:packs[0].id,clientSelection:!!context.demo,eventType:context.eventType,clientNames:contact?[contact.firstName||contact.name,contact.partnerName].filter(Boolean).join(' + '):[context.firstName||context.name,context.partnerName].filter(Boolean).join(' + '),eventDate:context.eventDate||null,venue:context.venue||null,status:'Draft',demo:!!context.demo,lineItems:lines};
  return api(new Request(new URL('/api/admin/proposals',request.url),{method:'POST',headers:request.headers,body:JSON.stringify({data})}),env,user,'proposals');
 }
 if(kind==='leads'&&id&&action==='convert'&&request.method==='POST'){
  const lead=await get(db,org,'leads',id);if(!lead)return json({error:'Lead not found'},404);if(lead.archived||lead.projectId)return json({error:'This lead was already archived or converted'},409);
  let projectId=input.projectId||crypto.randomUUID();let contactId=lead.contactId;let contactData=null;
  if(contactId&&!await get(db,org,'contacts',contactId))return json({error:'Contact no longer exists'},400);
  if(!contactId){const matched=(await list(db,org,'contacts')).find(c=>!c.archived&&!!c.demo===!!lead.demo&&c.email?.toLowerCase()===lead.email?.toLowerCase());contactId=matched?.id||crypto.randomUUID();if(!matched)contactData=validate('contacts',{name:[lead.firstName,lead.lastName].filter(Boolean).join(' ')||lead.name,firstName:lead.firstName||null,lastName:lead.lastName||null,partnerName:lead.partnerName||null,email:lead.email,phone:lead.phone||null,leadSource:lead.leadSource||null,notes:[lead.message,lead.notes].filter(Boolean).join('\n\n')||null,demo:!!lead.demo});}
  const data=validate('projects',{name:lead.name,contactId,eventType:lead.eventType,eventDate:lead.eventDate||null,venue:lead.venue||null,location:lead.location||null,status:'Inquiry',lifecycle:'Active',leadSource:lead.leadSource||null,tags:lead.tags||null,serviceIds:lead.serviceIds||[],notes:[lead.location,lead.message,lead.notes,lead.leadSource?'Lead source: '+lead.leadSource:null].filter(Boolean).join('\n')||null,demo:!!lead.demo});
  if(!input.projectId&&lead.eventDate){const matches=(await list(db,org,'projects')).filter(p=>!p.archived&&p.contactId===contactId&&!!p.demo===!!lead.demo&&p.eventType===lead.eventType&&p.eventDate===lead.eventDate);if(matches.length)return json({error:'A project already exists for this contact, event type and date. Use Associate existing project.'},409);}
  let associated=null;if(input.projectId){associated=await get(db,org,'projects',input.projectId);if(!associated||associated.archived||associated.contactId!==contactId||!!associated.demo!==!!lead.demo)return json({error:'Choose a current project with the same contact and DEMO status'},400);}
  const update=db.prepare("UPDATE records SET data=json_set(data,'$.archived',json('false'),'$.lifecycle','Active','$.projectId',?,'$.contactId',?),version=version+1,updated_at=? WHERE organization_id=? AND kind='leads' AND id=? AND version=?").bind(projectId,contactId,new Date().toISOString(),org,id,input.version);
  // A failed optimistic update aborts via the CHECK constraint rather than duplicating a project.
  try{await db.batch([db.prepare("INSERT INTO write_guards(token,valid) SELECT ?,COUNT(*) FROM records WHERE organization_id=? AND kind='leads' AND id=? AND version=?").bind(projectId,org,id,input.version),...(contactData?[insert(db,org,'contacts',contactId,contactData),audit(db,user,'created-from-lead','contacts',contactId)]:[]),...(!associated&&lead.eventDate?[db.prepare("INSERT INTO write_guards(token,valid) SELECT ?,CASE WHEN COUNT(*)=0 THEN 1 ELSE 0 END FROM records WHERE organization_id=? AND kind='projects' AND json_extract(data,'$.contactId')=? AND json_extract(data,'$.eventType')=? AND json_extract(data,'$.eventDate')=? AND COALESCE(json_extract(data,'$.demo'),0)=? AND COALESCE(json_extract(data,'$.archived'),0)=0").bind(projectId+'-event',org,contactId,lead.eventType,lead.eventDate,lead.demo?1:0),db.prepare('DELETE FROM write_guards WHERE token=?').bind(projectId+'-event')]:[]),...(associated?[]:[insert(db,org,'projects',projectId,data)]),update,db.prepare("UPDATE records SET data=json_set(data,'$.projectId',?,'$.contactId',COALESCE(json_extract(data,'$.contactId'),?)),version=version+1,updated_at=? WHERE organization_id=? AND kind='proposals' AND json_extract(data,'$.leadId')=? AND json_extract(data,'$.projectId') IS NULL").bind(projectId,contactId,new Date().toISOString(),org,id),db.prepare("UPDATE records SET data=json_set(data,'$.projectId',?,'$.contactId',?),version=version+1,updated_at=? WHERE organization_id=? AND kind='messages' AND json_extract(data,'$.leadId')=? AND json_extract(data,'$.projectId') IS NULL").bind(projectId,contactId,new Date().toISOString(),org,id),audit(db,user,associated?'lead-associated':'lead-converted','projects',projectId),audit(db,user,'lead-project-linked','leads',id),db.prepare('DELETE FROM write_guards WHERE token=?').bind(projectId)]);return json({id:projectId,contactId},201);}catch{return json({error:'Lead changed. Reload before converting.'},409);}
 }
 let data;try{data=validate(kind,input.data);if(['tasks','messages'].includes(kind)&&data.projectId){const project=await get(db,org,'projects',data.projectId);if(project){if(data.contactId&&data.contactId!==project.contactId)throw Error('Contact must match the project');data.contactId=project.contactId;if(kind==='tasks')data.demo=!!project.demo;}}if(kind==='services'&&id){const {id:sourceId,...stamped}=catalogRecord({...data,id});data=stamped;}await references(db,org,data)}catch(e){return json({error:e.message},400);}
 if((id&&request.method!=='PUT')||(!id&&request.method!=='POST')||action)return json({error:'Unsupported record action'},405);
 if(kind==='packages'&&id?.startsWith('baseline-'))return json({error:'Original PDF baseline is preserved. Duplicate it to make an editable version.'},400);
 const recordId=id||crypto.randomUUID();
 if(kind==='proposals'){
  const current=id?await get(db,org,kind,id):null;const needed=new Set(data.lineItems.filter(i=>i.sourceKind!=='custom').map(i=>i.sourceKind+':'+i.sourceId));
  if(data.templateId)needed.add('packages:'+data.templateId);const baseline=data.templateId?.startsWith('baseline-')||currentTemplateIds.includes(data.templateId);
  const sources=[...(await list(db,org,'packages')).map(r=>({...r,kind:'packages'})),...(await list(db,org,'services')).map(r=>({...r,...(baseline?baselineServices.find(s=>s.id===r.id):{}),kind:'services'}))];
  for(const source of sources)if(needed.has(source.kind+':'+source.id))for(const component of source.serviceIds||[])needed.add('services:'+component);
  data.catalogSnapshot=[...needed].map(key=>current?.catalogSnapshot?.find(r=>r.kind+':'+r.id===key)||sources.find(r=>r.kind+':'+r.id===key)).filter(Boolean).map(({notes,...row})=>row);
  const offered=data.catalogSnapshot.filter(s=>s.kind==='packages'&&data.lineItems.some(i=>i.sourceKind==='packages'&&i.sourceId===s.id));for(const item of data.lineItems)if(item.optional&&item.sourceKind==='services'&&!item.allowedPackageIds){const allowed=offered.filter(p=>(p.optionalServiceIds||[]).includes(item.sourceId)).map(p=>p.id);if(allowed.length)item.allowedPackageIds=allowed;}
  if(data.templateId){const template=await get(db,org,'packages',data.templateId);if((template.archived||template.active===false)&&(!current||current.templateId!==data.templateId)) return json({error:'Choose an active template'},400);}
 }
 if(kind==='messages'&&id){const previous=await get(db,org,'messages',id);if(previous?.attachmentSnapshot&&previous.projectId!==data.projectId)return json({error:'An attached draft cannot move to another project'},400);}
 if(kind==='contracts'){const project=await get(db,org,'projects',data.projectId);if(data.reviewState&&data.reviewState!=='Draft'&&project?.demo!==true)return json({error:'Workflow state simulation is DEMO-only'},403);if(data.contractTemplateId){const template=await get(db,org,'templates',data.contractTemplateId);if(!template||template.templateType!=='contract')return json({error:'Select a contract template'},400);}}
 if(kind==='messages'&&id){const previous=await get(db,org,'messages',id);if(previous?.attachmentSnapshot){data.attachmentSnapshot=previous.attachmentSnapshot;data.documentKind=previous.documentKind;data.documentId=previous.documentId;data.documentRevision=previous.documentRevision;}}
 if(kind==='invoices'){data.invoiceNumber='GL-DRAFT-'+recordId;data.issueAt||=new Date().toISOString().slice(0,10);}
 try{
  let operations=[];
  if(id){const current=await get(db,org,kind,id);if(!current)return json({error:'Not found'},404);if(current.version!==input.version)return json({error:'Record changed. Reload before saving.'},409);
   const guard=crypto.randomUUID();
   operations.push(db.prepare('INSERT INTO write_guards(token,valid) SELECT ?,COUNT(*) FROM records WHERE organization_id=? AND kind=? AND id=? AND version=?').bind(guard,org,kind,id,input.version));
   operations.push(db.prepare('DELETE FROM write_guards WHERE token=?').bind(guard));
   if(kind==='tasks')data.completedAt=data.completed?(current.completed?(current.completedAt||null):new Date().toISOString()):null;
   operations.push(db.prepare('UPDATE records SET data=?,version=version+1,updated_at=? WHERE organization_id=? AND kind=? AND id=? AND version=?').bind(JSON.stringify(data),new Date().toISOString(),org,kind,id,input.version));
  }else if(kind==='leads'&&!data.contactId){
   const contactId=crypto.randomUUID(),contact=validate('contacts',{name:[data.firstName,data.lastName].filter(Boolean).join(' ')||data.name,firstName:data.firstName||null,lastName:data.lastName||null,partnerName:data.partnerName||null,email:data.email,phone:data.phone||null,demo:!!data.demo,leadSource:data.leadSource||null,notes:[data.message,data.notes].filter(Boolean).join('\n\n')||null}),now=new Date().toISOString();
   operations.push(db.prepare("INSERT INTO records(organization_id,kind,id,data,created_at,updated_at) SELECT ?,'contacts',?,?,?,? WHERE NOT EXISTS (SELECT 1 FROM records WHERE organization_id=? AND kind='contacts' AND lower(json_extract(data,'$.email'))=lower(?) AND COALESCE(json_extract(data,'$.demo'),0)=? AND COALESCE(json_extract(data,'$.archived'),0)=0)").bind(org,contactId,JSON.stringify(contact),now,now,org,data.email,data.demo?1:0));
   operations.push(db.prepare("INSERT INTO audit_events SELECT ?,?,?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM records WHERE organization_id=? AND kind='contacts' AND id=?)").bind(crypto.randomUUID(),org,user.email,'created-from-lead','contacts',contactId,now,'{}',org,contactId));
   operations.push(db.prepare("INSERT INTO records(organization_id,kind,id,data,created_at,updated_at) VALUES(?,'leads',?,json_set(?,'$.contactId',(SELECT id FROM records WHERE organization_id=? AND kind='contacts' AND lower(json_extract(data,'$.email'))=lower(?) AND COALESCE(json_extract(data,'$.demo'),0)=? AND COALESCE(json_extract(data,'$.archived'),0)=0 LIMIT 1)),?,?)").bind(org,recordId,JSON.stringify({...data,lifecycle:data.lifecycle||'Lead'}),org,data.email,data.demo?1:0,now,now));
  }else{if(kind==='tasks')data.completedAt=data.completed?new Date().toISOString():null;operations.push(insert(db,org,kind,recordId,data));}
  if(kind==='projects'&&id)operations.push(db.prepare("UPDATE records SET data=json_set(data,'$.lifecycle',? ),version=version+1,updated_at=? WHERE organization_id=? AND kind='leads' AND json_extract(data,'$.projectId')=? AND COALESCE(json_extract(data,'$.archived'),0)=0").bind(data.lifecycle==='Finished'||data.status==='Completed'?'Finished':'Active',new Date().toISOString(),org,id));
  if(kind==='appointments')operations.push(...await appointmentLocks(db,org,recordId,data));
  operations.push(audit(db,user,id?'updated':'created',kind,recordId));if(kind==='tasks'&&data.completed&&(!id||!(await get(db,org,kind,id))?.completed))operations.push(audit(db,user,'task-completed',kind,recordId));if(['proposals','contracts','invoices'].includes(kind)&&id){const previous=await get(db,org,kind,id);if(previous.status!==data.status)operations.push(audit(db,user,'document-status-changed',kind,recordId,{from:previous.status||'Draft',to:data.status||'Draft'}));if(kind==='contracts'&&(previous.reviewState||'Draft')!==(data.reviewState||'Draft'))operations.push(audit(db,user,'demo-document-state-changed',kind,recordId,{from:previous.reviewState||'Draft',to:data.reviewState||'Draft',simulation:true}));}if(kind==='invoices'&&id){const before=await get(db,org,kind,id);if(JSON.stringify(before.paymentHistory||[])!==JSON.stringify(data.paymentHistory||[]))operations.push(audit(db,user,'manual-payment-history-updated',kind,recordId));if(JSON.stringify(before.installments||[])!==JSON.stringify(data.installments||[]))operations.push(audit(db,user,'payment-schedule-updated',kind,recordId));}await db.batch(operations);
  return json(await get(db,org,kind,recordId),id?200:201);
 }catch(e){return json({error:/UNIQUE|CHECK/.test(e.message)?'Record conflict or appointment already reserved. Reload and try another time.':'Save failed; no change was committed.'},409);}
}
