'use strict';
const routes=[['dashboard','Dashboard'],['leads','Leads / Inquiries'],['contacts','Contacts'],['projects','Projects'],['services','Services & Packages'],['proposals','Proposals'],['contracts','Contracts'],['invoices','Invoices / Payments'],['calendar','Calendar / Scheduler'],['messages','Messages'],['templates','Email Templates'],['files','Files'],['automations','Automations'],['client-portal','Client Portal'],['settings','Settings']];
const stages=['New Inquiry','Lead','Consultation','Proposal','Contract','Deposit / Payment Schedule','Booked','Pre-Event','Event','Post-Production','Delivery','Completed'];
const leadStages=['New','Contacted','Consultation Scheduled','Proposal Needed','Proposal Sent','Follow-Up','Booked','Lost / Declined'];
const eventTypes=['Wedding','Sweet Sixteen','Private Event','Corporate','Live Event','Other / Custom'];
const catalogCategories=['Weddings / Cinematography','Weddings / Photography','Weddings / Add-ons','Weddings / Micro Weddings','Sweet Sixteen / Cinematography','Sweet Sixteen / Photography','Sweet Sixteen / Add-ons','Events & Corporate / Photography','Events & Corporate / Cinematography','Events & Corporate / Other','General / Add-ons & Fees','Needs classification'];
const sourceFields=['sourceName','sourceDescription','sourcePriceCents','sourceCoverageHours','sourceCategory','source','sourcePages'];
const state={meta:null,records:{},kind:null,editing:null};
const main=document.querySelector('main'),dialog=document.querySelector('dialog'),fields=document.querySelector('#fields');
function el(tag,text,attrs={}){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;for(const [k,v]of Object.entries(attrs))node.setAttribute(k,v);return node;}
function notice(text){document.querySelector('#notice').textContent=text;}
async function request(path,method='GET',body){const response=await fetch('/api/admin/'+path,{method,credentials:'same-origin',headers:method==='GET'?{}:{'Content-Type':'application/json','X-GioLina-Request':'admin'},body:body?JSON.stringify(body):undefined});let data;try{data=await response.json()}catch{throw new Error('Private session unavailable. Sign in again.')}if(!response.ok)throw new Error(data.error||'Request failed');return data;}
async function records(kind,refresh=false){if(refresh||!state.records[kind])state.records[kind]=await request(kind);return state.records[kind];}
function button(text,callback,primary=false){const node=el('button',text,{type:'button',...(primary?{class:'primary'}:{})});node.addEventListener('click',()=>Promise.resolve(callback()).catch(e=>notice(e.message)));return node;}
function money(value){return value==null?'Price needs confirmation':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value/100);}
function label(field){return ({discountCents:'Discount (USD)',clientDescription:'Client-facing description',description:'Working description',catalogCategory:'Catalog category',active:'Available for new packages',sourceDescription:'Original source description',sourcePriceCents:'Original source price (USD)',sourceName:'Original source name',priceCents:'Price (USD)',amountCents:'Planned total (USD)',depositCents:'Planned deposit (USD)',paymentHistory:'Manual payment history',installments:'Planned installments',paymentSchedule:'Planned payment schedule',serviceIds:'Included services',optionalServiceIds:'Optional add-ons',contactId:'Contact',projectId:'Project',packageId:'Package',appointmentTypeId:'Appointment type',reviewRequired:'Requires source review',startAt:'Starts (your device timezone)',endAt:'Ends (your device timezone)',sourcePages:'Source pages',followUpAt:'Follow-up date',dueAt:'Due date',storageKey:'Private storage reference (upload not enabled)',externalProviderId:'Future signature provider reference'})[field]||field.replace(/([A-Z])/g,' $1').replace(/^./,s=>s.toUpperCase());}
function header(title,copy,actions=[]){const top=el('div',undefined,{class:'topline'}),text=el('div');text.append(el('h1',title),el('p',copy,{class:'quiet'}));top.append(text);const group=el('div',undefined,{class:'actions'});group.append(...actions);top.append(group);main.replaceChildren(top);}
function panel(title,text){const p=el('section',undefined,{class:'panel'});p.append(el('h2',title),el('p',text));main.append(p);return p;}
const referenceKinds={lead:'leads',contact:'contacts',project:'projects',package:'packages','appointment-type':'appointment-types'};
async function edit(kind,record=null,duplicate=false){
 state.kind=kind;state.editing=duplicate?null:record?.id?record:null;fields.replaceChildren();document.querySelector('#form-error').textContent='';
 document.querySelector('#editor-title').textContent=(duplicate?'Duplicate':record?.id?'Edit':'New')+' '+(routes.find(r=>r[0]===kind)?.[1]||kind);
 document.querySelector('#editor-help').textContent='Private preview record. No email, signature or payment is sent. Dates use your device timezone; the scheduler displays America/New_York.';
 const def=state.meta.definitions[kind];
 for(const [field,type]of Object.entries(def.fields)){
  const fieldLabel=label(field)+(def.required.includes(field)?' *':''),composite=['array','contact-array','line-items','schedule','payment-history','section-order'].includes(type);const wrap=el(composite?'fieldset':'label',composite?undefined:fieldLabel,{class:type==='long'||composite?'wide':''});if(composite)wrap.append(el('legend',fieldLabel));let input;
  if(type==='section-order')input=sectionOrderControl(record?.[field]||['introduction','services','investment']);
  else if(type==='image-list')input=el('textarea',undefined,{placeholder:'/assets/photo.jpg — one image per line'});
  else if(type==='schedule'||type==='payment-history')input=financialControl(record?.[field]||[],type);
  else if(type==='line-items')input=await lineItemsControl(record?.lineItems||[]);
  else if(type==='long')input=el('textarea');
  else if(type==='boolean')input=el('input',undefined,{type:'checkbox'});
  else if((type==='array'||type==='contact-array')){
   input=el('div',undefined,{class:'service-picker'});input.dataset.field=field;
   for(const row of (await records(type==='contact-array'?'contacts':'services')).filter(r=>(!r.archived&&r.active!==false)||(record?.[field]||[]).includes(r.id))){const option=el('label',undefined,{class:'pick-option'}),check=el('input',undefined,{type:'checkbox',value:row.id});check.checked=(record?.[field]||[]).includes(row.id);option.append(check,el('span',row.name+(type==='contact-array'?' · '+row.email:' · '+money(row.priceCents))));input.append(option);}
  }
  else if(referenceKinds[type]||['signature-status','template-category','proposal-status','lead-status','contact-method','catalog-category','event','status','weekday','appointment-status'].includes(type)){
   input=el('select');if((type==='array'||type==='contact-array'))input.multiple=true;else input.append(el('option','Select…',{value:''}));
   const options=(type==='array'||type==='contact-array')?(await records('services')).filter(r=>!r.archived||(record?.[field]||[]).includes(r.id)).map(r=>[r.id,r.name+' · '+r.category+' · '+money(r.priceCents)]):referenceKinds[type]?(await records(referenceKinds[type])).filter(r=>!r.archived||r.id===record?.[field]).map(r=>[r.id,r.name]):(type==='signature-status'?['Not requested','Provider selection pending']:type==='template-category'?(state.meta.templateCategories||[]):type==='proposal-status'?['Draft','Ready for review','Accepted (test only)','Declined','Expired']:type==='lead-status'?[...new Set([...leadStages,...(record?.status?[record.status]:[])])]:type==='contact-method'?['Email','Phone','Text','Other']:type==='catalog-category'?(state.meta.catalogCategories||catalogCategories):type==='event'?eventTypes:type==='status'?stages:type==='weekday'?['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']:['Scheduled','Cancelled','Completed']).map(v=>[v,v]);
   for(const [value,text]of options)input.append(el('option',text,{value}));
  }else input=el('input',undefined,{type:({money:'number',number:'number',date:'date',time:'time',datetime:'datetime-local',email:'email',url:'url'})[type]||'text'});
  input.setAttribute('name',field);input.required=def.required.includes(field);if(type==='money'){input.step='0.01';input.min='0';}if(type==='number'){input.step=field==='coverageHours'?'0.5':'1';input.min='0';}
  const value=record?.[field];
  if(type==='line-items'||type==='schedule'||type==='payment-history'||type==='section-order'){}else if(type==='image-list')input.value=(value||[]).join('\n');else if(type==='boolean')input.checked=field==='active'?value!==false:!!value;else if((type==='array'||type==='contact-array')){}
  else if(type==='datetime'&&value){const d=new Date(value);input.value=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
  else input.value=value==null?'':type==='money'?value/100:value;
  if(duplicate&&field==='name')input.value+=' (copy)';
  if(['messages','contracts','invoices'].includes(kind)&&field==='status'){input.value='Draft';input.readOnly=true;}
  if(kind==='automations'&&field==='enabled'){input.checked=false;input.disabled=true;}
  wrap.append(input);if((type==='array'||type==='contact-array'))wrap.append(el('small','Select included items. Source variants remain distinct.'));
  if(type==='money')wrap.append(el('small','Leave blank if no confirmed price is available. Zero means free.'));
  if(kind==='services'&&record&&sourceFields.includes(field)){input.disabled=true;wrap.append(el('small','Preserved source reference. Edit the working or client-facing fields above.'));}fields.append(wrap);
 }
 if(kind==='proposals')fields.prepend(el('p','Select a client, lead or project. Optional add-ons do not contribute to totals. Notes remain internal. Client introduction and item descriptions appear in the presentation.',{class:'wide quiet'}));
 if(kind==='appointments'){const type=fields.querySelector('[name=appointmentTypeId]'),start=fields.querySelector('[name=startAt]'),end=fields.querySelector('[name=endAt]');const update=()=>{const selected=state.records['appointment-types']?.find(r=>r.id===type.value);if(selected&&start.value){const date=new Date(start.value);date.setMinutes(date.getMinutes()+selected.durationMinutes);end.value=new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);}};type.addEventListener('change',update);start.addEventListener('change',update);}
 dialog.showModal();
}
document.querySelector('#record-form').addEventListener('submit',async event=>{
 event.preventDefault();const submit=event.submitter||event.target.querySelector('button[type=submit]');submit.disabled=true;
 try{const data={};for(const [field,type]of Object.entries(state.meta.definitions[state.kind].fields)){const input=fields.querySelector('[name="'+field+'"]');data[field]=type==='section-order'?Array.from(input.querySelectorAll('[data-section]'),r=>r.dataset.section):type==='image-list'?input.value.split(/\n/).map(s=>s.trim()).filter(Boolean):type==='schedule'||type==='payment-history'?readFinancialRows(input,type):type==='line-items'?readLineItems(input):type==='boolean'?input.checked:(type==='array'||type==='contact-array')?Array.from(input.querySelectorAll('input:checked'),o=>o.value):input.value===''?null:type==='money'?Math.round(Number(input.value)*100):type==='number'?Number(input.value):type==='datetime'?new Date(input.value).toISOString():input.value;}
  await request(state.kind+(state.editing?'/'+state.editing.id:''),state.editing?'PUT':'POST',{data,...(state.editing?{version:state.editing.version}:{})});delete state.records[state.kind];dialog.close();notice('Record saved to private preview database.');await render();
 }catch(e){document.querySelector('#form-error').textContent=e.message;}finally{submit.disabled=false;}
});
for(const selector of ['#close-editor','#cancel-editor'])document.querySelector(selector).addEventListener('click',()=>dialog.close());
function clean(record){const {id,version,createdAt,updatedAt,subtotalCents,totalCents,paidCents,remainingCents,paymentState,...data}=record;return data;}
async function archive(kind,record){await request(kind+'/'+record.id,'PUT',{data:{...clean(record),archived:!record.archived},version:record.version});delete state.records[kind];await render();notice(record.archived?'Record restored.':'Record archived; history retained.');}
async function collection(kind,target=main){
 const all=await records(kind),filter=el('input',undefined,{type:'search',placeholder:'Search names, notes, sources…','aria-label':'Search '+kind,class:'filter'});const area=el('div',undefined,{class:'table-wrap'}),tools=el('div',undefined,{class:'filterbar'}),statusFilter=el('select',undefined,{'aria-label':'Filter record state'}),categoryFilter=el('select',undefined,{'aria-label':'Filter category'});
 for(const [value,text]of [['current','Current records'],['active','Active'],['inactive','Inactive'],['archived','Archived'],['all','All records'],['review','Needs source review']])statusFilter.append(el('option',text,{value}));categoryFilter.append(el('option','All categories',{value:''}));for(const cat of [...new Set(all.map(r=>r.catalogCategory||r.category).filter(Boolean))].sort())categoryFilter.append(el('option',cat,{value:cat}));const sort=el('select',undefined,{'aria-label':'Sort '+kind});for(const [value,text]of [['updated','Recently updated'],['name','Name A–Z'],['price','Price low–high'],['hours','Coverage hours']])sort.append(el('option',text,{value}));tools.append(filter,statusFilter,sort);if(['services','packages','templates'].includes(kind))tools.append(categoryFilter);if(kind==='contacts'){categoryFilter.replaceChildren(el('option','All contact methods',{value:''}));for(const method of ['Email','Phone','Text','Other'])categoryFilter.append(el('option',method,{value:method}));categoryFilter.setAttribute('aria-label','Filter contact method');tools.append(categoryFilter);}target.append(tools,area);
 function draw(){const q=filter.value.toLowerCase(),visible=all.filter(r=>JSON.stringify(r).toLowerCase().includes(q)&&(!categoryFilter.value||(kind==='contacts'?r.preferredContactMethod:kind==='leads'?r.status:r.catalogCategory||r.category)===categoryFilter.value)&&(statusFilter.value==='all'||statusFilter.value==='archived'?statusFilter.value==='all'||r.archived:statusFilter.value==='review'?r.reviewRequired&&!r.archived:!r.archived&&(statusFilter.value==='current'||statusFilter.value==='active'&&r.active!==false||statusFilter.value==='inactive'&&r.active===false)));visible.sort((a,b)=>sort.value==='name'?a.name.localeCompare(b.name):sort.value==='price'?(a.priceCents??Infinity)-(b.priceCents??Infinity):sort.value==='hours'?(a.coverageHours??Infinity)-(b.coverageHours??Infinity):String(b.updatedAt||'').localeCompare(String(a.updatedAt||'')));area.replaceChildren();if(!visible.length){area.append(el('p','No matching records. Create your first private preview record.',{class:'empty'}));return;}
 const table=el('table'),head=el('thead'),tr=el('tr');for(const title of ['Record','Details','State','Actions'])tr.append(el('th',title,{scope:'col'}));head.append(tr);table.append(head);const body=el('tbody');
 for(const row of visible){const tr=el('tr'),name=el('td');if(['services','packages'].includes(kind)){const v=catalogVisual(row);if(v.thumbnail)name.append(el('img',undefined,{src:v.thumbnail,alt:'',loading:'lazy',class:'catalog-thumb'}));name.append(el('small',/add-on|fee/i.test(row.catalogCategory||row.name)?'ADD-ON / FEE':kind==='packages'?'PACKAGE':'PRIMARY SERVICE',{class:'catalog-type'}));}name.append(el('strong',row.name));if(['services','packages'].includes(kind))name.append(el('p',(row.clientShortDescription||row.clientDescription||row.description||'').slice(0,160),{class:'catalog-summary'}));if(row.demo)name.append(el('span','DEMO',{class:'tag'}));const detail=el('td');detail.append(el('div',kind==='services'?money(row.priceCents)+(row.coverageHours?' · '+row.coverageHours+' hours':''):kind==='proposals'?money(row.totalCents)+' · '+(row.lineItems||[]).length+' items':kind==='packages'?money(row.priceCents)+' · '+(row.serviceIds||[]).length+' included services':kind==='appointments'?new Date(row.startAt).toLocaleString('en-US',{timeZone:'America/New_York'})+' ET':row.eventDate||row.email||row.subject||row.description?.slice(0,90)||'—'));
 if(kind==='services'){detail.append(el('small',(row.catalogCategory||row.category||'Uncategorized')+' · '+(row.source||'Custom service')+(row.sourcePages?' · p. '+row.sourcePages:''),{class:'quiet'}));}
 const status=el('td');status.append(el('span',row.archived?'Archived':row.status||(row.active===false?'Inactive':row.completed?'Completed':'Active'),{class:'tag'}));if(row.reviewRequired)status.append(el('span','Confirm source',{class:'tag warn'}));const actions=el('td'),group=el('div',undefined,{class:'actions'});group.append(button(kind==='proposals'?'Preview as Client':'View',()=>viewRecord(kind,row)),button('Edit',()=>edit(kind,row)));if(['services','packages'].includes(kind)&&!row.archived)group.append(button(row.active===false?'Activate':'Deactivate',async()=>{await request(kind+'/'+row.id,'PUT',{data:{...clean(row),active:row.active===false},version:row.version});delete state.records[kind];await render();}));
 if(state.meta.definitions[kind].fields.archived)group.append(button('Duplicate',()=>edit(kind,row,true)),button(row.archived?'Restore':'Archive',()=>archive(kind,row)));
 if(kind==='leads'&&!row.archived)group.append(button('Create project',async()=>{await request('leads/'+row.id+'/convert','POST',{version:row.version});delete state.records.leads;delete state.records.projects;delete state.records.contacts;notice('Contact linked and project created; original lead archived.');await render();}));
 actions.append(group);tr.append(name,detail,status,actions);body.append(tr);}table.append(body);area.append(table);}
 sort.addEventListener('change',draw);filter.addEventListener('input',draw);statusFilter.addEventListener('change',draw);categoryFilter.addEventListener('change',draw);draw();
}
async function viewRecord(kind,row){if(kind==='proposals')return proposalPreview(row);
 let viewer=document.querySelector('#record-view');if(viewer)viewer.remove();viewer=el('dialog',undefined,{id:'record-view','aria-label':row.name});viewer.append(el('h2',row.name),el('p',row.archived?'Archived':row.active===false?'Inactive':'Active',{class:'badge'}));const dl=el('dl');
 for(const [key,type]of Object.entries(state.meta.definitions[kind].fields)){let value=row[key];if(value==null||value==='')continue;if(type==='schedule'||type==='payment-history'){value=value.map(r=>[r.label||r.reference||'Manual payment',r.dueAt||r.date,money(r.amountCents)].join(' · ')).join('\n');}if((type==='array'||type==='contact-array')){const services=await records(type==='contact-array'?'contacts':'services');value=value.map(id=>services.find(s=>s.id===id)?.name||id).join('\n');}else if(referenceKinds[type])value=(await records(referenceKinds[type])).find(r=>r.id===value)?.name||value;else if(type==='money')value=money(value);else if(type==='boolean')value=value?'Yes':'No';dl.append(el('dt',label(key)),el('dd',String(value)));}if(kind==='contacts'){dl.append(el('dt','Created'),el('dd',row.createdAt||'Not recorded'),el('dt','Last record activity'),el('dd',row.updatedAt||'Not recorded'));const related=(await records('projects')).filter(p=>p.contactId===row.id);dl.append(el('dt','Associated projects'),el('dd',related.map(p=>p.name+' · '+p.status).join('\n')||'No projects yet'));const activity=await request('activity');dl.append(el('dt','Recent contact activity'),el('dd',activity.filter(a=>a.record_kind==='contacts'&&a.record_id===row.id).map(a=>a.occurred_at+' · '+a.action).join('\n')||'No recent changes'));}if(kind==='invoices'){for(const [title,value]of [['Manually recorded paid',money(row.paidCents||0)],['Remaining planned balance',money(row.remainingCents??row.amountCents)],['Payment state',row.paymentState||'Planned / unpaid']])dl.append(el('dt',title),el('dd',value));}viewer.append(dl);if(kind==='templates'){const demo={clientFirstName:'Demo',partnerName:'Demo partner',eventDate:'November 10, 2026',eventType:'Wedding',venue:'Demo venue',balance:'$1,000.00',dueDate:'October 30, 2026',appointmentDateTime:'October 12, 2026 at 10:00 AM ET'};const substitute=text=>(text||'').replace(/\{\{(\w+)\}\}/g,(all,key)=>demo[key]||all);viewer.append(el('h3','DEMO variable preview'),el('p',substitute(row.subject)),el('pre',substitute(row.body),{class:'template-preview'}));}if(kind==='projects')await projectRelations(viewer,row);viewer.append(button('Close',()=>viewer.close()),button('Edit',()=>{viewer.close();return edit(kind,row);}));document.body.append(viewer);viewer.showModal();
}
function readFinancialRows(box,type){return Array.from(box.querySelectorAll('.financial-row'),row=>{const values={};for(const input of row.querySelectorAll('[data-part]'))values[input.dataset.part]=input.dataset.part==='amountCents'?(input.value===''?null:Math.round(Number(input.value)*100)):input.value;return values;});}
function financialControl(rows,type){const box=el('div',undefined,{class:'financial-builder'});function add(row={}){const line=el('div',undefined,{class:'financial-row'});const parts=type==='schedule'?[['label','Installment / deposit label','text'],['dueAt','Planned due date','date'],['amountCents','Planned amount (USD)','number']]:[['date','Manual payment date','date'],['amountCents','Manually received amount (USD)','number'],['reference','Manual reference / note','text']];for(const [key,title,inputType]of parts){const label=el('label',title),input=el('input',undefined,{type:inputType,'aria-label':title});input.dataset.part=key;input.value=row[key]==null?'':key==='amountCents'?row[key]/100:row[key];if(key==='amountCents'){input.step='0.01';input.min='0';}label.append(input);line.append(label);}line.append(button('Remove payment row',()=>line.remove()));box.append(line);}box.append(el('p',type==='schedule'?'Planning records only. No payment request is issued.':'Manual bookkeeping only. Recording an amount does not process a payment.',{class:'quiet'}),button('Add payment row',()=>add()));for(const row of rows)add(row);return box;}
function readLineItems(container){return Array.from(container.querySelectorAll('.proposal-line'),line=>({name:line.querySelector('[data-part=name]').value,description:line.querySelector('[data-part=description]').value,quantity:Number(line.querySelector('[data-part=quantity]').value),unitPriceCents:line.querySelector('[data-part=price]').value===''?null:Math.round(Number(line.querySelector('[data-part=price]').value)*100),sourceKind:line.dataset.sourceKind,sourceId:line.dataset.sourceId||null,optional:line.querySelector('[data-part=optional]').checked}));}
async function lineItemsControl(items){
 const box=el('div',undefined,{class:'line-builder wide'}),picker=el('select',undefined,{'aria-label':'Add catalog item'});picker.append(el('option','Choose service or package…',{value:''}));const catalog=[];
 for(const kind of ['packages','services'])for(const row of (await records(kind)).filter(r=>!r.archived&&r.active!==false)){catalog.push({kind,row});picker.append(el('option',kind.slice(0,-1)+' · '+row.name+' · '+money(row.priceCents)+' · '+(row.category||row.catalogCategory||''),{value:kind+':'+row.id}));}
 const lines=el('div');function add(item){const line=el('div',undefined,{class:'proposal-line'});line.dataset.sourceKind=item.sourceKind||'custom';line.dataset.sourceId=item.sourceId||'';for(const [key,title,type,value]of [['name','Item name','text',item.name||''],['description','Client-facing item description','textarea',item.description||''],['quantity','Quantity','number',item.quantity||1],['price','Unit price (USD)','number',item.unitPriceCents==null?'':item.unitPriceCents/100]]){const wrap=el('label',title),input=el(type==='textarea'?'textarea':'input',undefined,type==='textarea'?{}:{type});input.dataset.part=key;input.value=value;input.setAttribute('aria-label',title);if(key==='quantity'){input.min='1';input.step='1';input.max='1000';}if(key==='price'){input.min='0';input.step='0.01';}wrap.append(input);line.append(wrap);}const optional=el('label','Optional add-on (excluded from total)'),check=el('input',undefined,{type:'checkbox','data-part':'optional'});check.checked=!!item.optional;optional.append(check);line.append(optional,button('Move item up',()=>{const before=line.previousElementSibling;if(before)lines.insertBefore(line,before);}),button('Move item down',()=>{const after=line.nextElementSibling;if(after)lines.insertBefore(after,line);}));line.append(el('small','Saved catalog snapshot; price changes here do not change the catalog.'),button('Remove item',()=>{line.remove();update();}));lines.append(line);update();}
 const total=el('p',undefined,{class:'proposal-total',role:'status'});function update(){const rows=readLineItems(lines);total.textContent=rows.some(r=>r.unitPriceCents==null)?'Confirm every item price before saving.':'Line subtotal: '+money(rows.reduce((sum,r)=>sum+(r.optional?0:r.quantity*r.unitPriceCents),0));}
 box.append(picker,button('Add selected item',()=>{const selected=catalog.find(c=>c.kind+':'+c.row.id===picker.value);if(!selected)return;const r=selected.row;add({name:r.name,description:r.clientShortDescription||r.clientDescription||r.description||'',quantity:1,unitPriceCents:r.priceCents,sourceKind:selected.kind,sourceId:r.id});}),button('Add custom item',()=>add({quantity:1,sourceKind:'custom'})),lines,total);box.addEventListener('input',update);for(const item of items)add(item);update();return box;
}
function catalogVisual(row){const category=row.catalogCategory||row.category||'',theme=/Sweet/.test(category)?'sweet':/Event|Corporate/.test(category)?'event':'wedding';return {...(state.meta.presentationDefaults?.[theme]||{}),...(row.thumbnail?{thumbnail:row.thumbnail}:{})};}
function sectionOrderControl(order){const box=el('div');for(const key of order){const row=el('div',undefined,{'data-section':key,class:'section-order-row'});row.append(el('span',label(key)),button('Move '+key+' up',()=>{if(row.previousElementSibling)box.insertBefore(row,row.previousElementSibling);}),button('Move '+key+' down',()=>{if(row.nextElementSibling)box.insertBefore(row.nextElementSibling,row);}));box.append(row);}return box;}
async function proposalPreview(row){
 let viewer=document.querySelector('#record-view');viewer?.remove();viewer=el('dialog',undefined,{id:'record-view',class:'proposal-preview','aria-label':row.name});
 const top=el('div',undefined,{class:'preview-toolbar'}),devices=el('select',undefined,{'aria-label':'Preview device'});for(const [value,text]of [['desktop','Desktop · 1280'],['laptop','Laptop · 1100'],['landscape','Tablet landscape · 1024'],['portrait','Tablet portrait · 768'],['mobile','Mobile · 375']])devices.append(el('option',text,{value}));
 top.append(el('h2',row.name),button('Back to proposals',()=>viewer.close()),button('Edit proposal',()=>{viewer.close();return edit('proposals',row);}),devices);
 const frame=el('iframe',undefined,{src:'/admin/proposals/'+encodeURIComponent(row.id)+'/preview',title:'Client presentation',class:'client-preview-frame desktop'}),canvas=el('div',undefined,{class:'preview-canvas'});canvas.append(frame);devices.addEventListener('change',()=>frame.className='client-preview-frame '+devices.value);
 const sharing=el('section',undefined,{class:'share-controls'});viewer.append(top,sharing,canvas);document.body.append(viewer);viewer.showModal();
 async function refreshShare(){const info=await request('proposals/'+row.id+'/share');sharing.replaceChildren(el('p','Current revision '+info.revision+' · Created '+(info.createdAt||'—')+' · Modified '+(info.updatedAt||'—')));if(info.current){sharing.append(el('p',info.current.status+' · Published revision '+info.current.revision+(info.current.revision!==info.revision?' · Unpublished changes: regenerate to publish this revision.':'')+' · Last viewed '+(info.current.lastViewed||'Not yet viewed')+' · Expires '+info.current.expiresAt));const url=el('input',undefined,{type:'text',readonly:'',value:info.current.url,'aria-label':'Test share link'});sharing.append(url,button('Copy Link',async()=>{try{await navigator.clipboard.writeText(url.value);notice('Test share link copied.');}catch{url.focus();url.select();notice('Select and copy the test link above.');}}),el('a','Open test proposal ↗',{href:info.current.url,target:'_blank',rel:'noopener noreferrer'}));}
 const action=async what=>{const result=await request('proposals/'+row.id+'/share','POST',{action:what,version:row.version});notice(result.message);await refreshShare();};sharing.append(button(info.current?'Regenerate Link':'Create Share Link',()=>action(info.current?'regenerate':'create')),button('Disable Link',()=>action('disable')),button('Refresh share status',refreshShare),el('small','DEMO links only · expire after 30 days · anyone holding the link can view this one snapshot. Views do not identify a recipient.'));
 if(info.history?.length){const history=el('details');history.append(el('summary','Published revision history'));for(const r of info.history)history.append(el('p','Revision '+r.revision+' · '+r.createdAt+' · '+r.status));sharing.append(history);}}
 await refreshShare();
}
async function projectRelations(target,project){
 const kinds=['proposals','contracts','invoices','appointments','messages','files','tasks'];const sets=await Promise.all(kinds.map(k=>records(k)));const linkedIds=new Set([project.id]);
 for(let i=0;i<kinds.length;i++){const kind=kinds[i],rows=sets[i].filter(r=>r.projectId===project.id);const section=el('section',undefined,{class:'related-section'});section.append(el('h3',routes.find(r=>r[0]===kind)?.[1]||kind));for(const row of rows){linkedIds.add(row.id);const line=el('div',undefined,{class:'related-row'});line.append(el('span',row.name+' · '+(row.status||row.dueAt||(row.completed?'Completed':'Open'))),button('View '+row.name,()=>{target.close?.();return viewRecord(kind,row);}));section.append(line);}if(!rows.length)section.append(el('p','No linked records yet.',{class:'quiet'}));section.append(button('Add '+kind,()=>{target.close?.();return edit(kind,{projectId:project.id,contactId:project.contactId,demo:!!project.demo});}));target.append(section);}
 const section=el('section',undefined,{class:'related-section'});section.append(el('h3','Activity timeline'));const activity=await request('activity?project='+encodeURIComponent(project.id));for(const item of activity)section.append(el('p',new Date(item.occurred_at).toLocaleString()+' · '+item.record_kind+' · '+item.action));if(!activity.length)section.append(el('p','No recent activity recorded.'));target.append(section);
}
async function dashboard(){
 const kinds=['leads','projects','appointments','tasks','proposals','contracts','invoices'];const [leads,projects,appointments,tasks,proposals,contracts,invoices]=await Promise.all(kinds.map(k=>records(k)));const activity=await request('activity');header('Your workspace','Private preview · counts come from stored records. DEMO items are marked.',[button('New inquiry',()=>edit('leads'),true),button('Add reminder',()=>edit('tasks'))]);const today=nyDate(),openLeads=leads.filter(r=>!r.archived&&!['Lost / Declined','Booked'].includes(r.status)),followUps=openLeads.filter(r=>r.followUpAt&&r.followUpAt<=today),consultations=appointments.filter(r=>r.status==='Scheduled'&&Date.parse(r.startAt)>=Date.now()),events=projects.filter(r=>!r.archived&&r.eventDate&&r.eventDate>=today).sort((a,b)=>a.eventDate.localeCompare(b.eventDate)),proposalActions=proposals.filter(r=>!r.archived),contractDrafts=contracts.filter(r=>!r.archived),unpaid=invoices.filter(r=>!r.archived&&(r.amountCents||0)>(r.paidCents||0)),upcoming=unpaid.filter(r=>r.dueAt&&r.dueAt>=today),overdue=unpaid.filter(r=>r.dueAt&&r.dueAt<today);const metrics=el('div',undefined,{class:'metrics'});
 for(const [name,value]of [['New inquiries',openLeads.filter(r=>['New','New Inquiry'].includes(r.status)).length],['Follow-ups needed',followUps.length],['Upcoming consultations / meetings',consultations.length],['Upcoming events',events.length],['Active projects',projects.filter(r=>!r.archived&&r.status!=='Completed').length],['Proposals awaiting review',proposalActions.length],['Contract drafts to review',contractDrafts.length],['Planned upcoming payments',upcoming.length],['Past-due payment plans',overdue.length]]){const box=el('div',undefined,{class:'metric'});box.append(el('strong',String(value)),el('span',name));metrics.append(box);}main.append(metrics);
 function rowsPanel(title,copy,kind,rows,detail){const p=panel(title,copy);for(const row of rows.slice(0,8)){const line=el('div',undefined,{class:'related-row'});line.append(el('span',(row.demo?'DEMO · ':'')+row.name+' · '+detail(row)),button('Open '+row.name,()=>viewRecord(kind,row)));p.append(line);}if(!rows.length)p.append(el('p','No records needing attention.',{class:'quiet'}));}
 rowsPanel('Follow-ups needed','Manual inquiries awaiting attention.','leads',followUps,r=>r.followUpAt);rowsPanel('Upcoming consultations / meetings','Scheduled appointments in Eastern time.','appointments',consultations.sort((a,b)=>a.startAt.localeCompare(b.startAt)),r=>new Date(r.startAt).toLocaleString('en-US',{timeZone:'America/New_York'})+' ET');rowsPanel('Upcoming events','Project event dates.','projects',events,r=>r.eventDate);rowsPanel('Proposal actions','Private drafts only. No proposal was sent.','proposals',proposalActions,r=>(r.status||'Draft')+' · '+money(r.totalCents));rowsPanel('Contract review','No signature requests are active.','contracts',contractDrafts,r=>r.status||'Draft');rowsPanel('Planned payments','Draft obligations and manually recorded history; no processor is connected.','invoices',[...overdue,...upcoming],r=>r.dueAt+' · planned balance '+money(Math.max(0,(r.amountCents||0)-(r.paidCents||0))));
 const reminder=panel('Tasks & reminders','Manual reminders only.');for(const row of tasks.filter(r=>!r.completed)){reminder.append(el('p',(row.demo?'DEMO · ':'')+row.name+(row.dueAt?' · '+row.dueAt:'')),button('Complete '+row.name,async()=>{await request('tasks/'+row.id,'PUT',{data:{...clean(row),completed:true},version:row.version});delete state.records.tasks;await render();}));}if(!tasks.some(r=>!r.completed))reminder.append(el('p','No open reminders.',{class:'quiet'}));
 const history=panel('Recent activity','Private changes to records.');for(const item of activity.slice(0,12))history.append(el('p',item.action+' · '+item.record_kind+' · '+new Date(item.occurred_at).toLocaleString()));
}
function nyDate(value=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value));}
function shiftDay(day,count){const d=new Date(day+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+count);return d.toISOString().slice(0,10);}
async function calendar(){
 header('Calendar / Scheduler','Private calendar · America/New_York. No public booking or notifications.',[button('Add appointment',()=>edit('appointments'),true),button('Set up appointment types',async()=>{const r=await request('setup-appointment-types','POST',{});delete state.records['appointment-types'];notice(r.message);await render();})]);
 const [appointments,projects,availability]=await Promise.all(['appointments','projects','availability'].map(k=>records(k)));let anchor=nyDate(),mode='Month';const controls=el('div',undefined,{class:'calendar-controls'}),date=el('input',undefined,{type:'date','aria-label':'Calendar date'}),heading=el('h2'),grid=el('div',undefined,{class:'calendar-grid','aria-label':'Visual calendar'});date.value=anchor;
 function draw(){grid.replaceChildren();grid.dataset.mode=mode.toLowerCase();heading.textContent=mode+' · '+new Date(anchor+'T12:00:00Z').toLocaleDateString('en-US',{timeZone:'UTC',month:'long',day:'numeric',year:'numeric'});let start=anchor,count=1;if(mode==='Month'){const first=anchor.slice(0,8)+'01';start=shiftDay(first,-new Date(first+'T12:00:00Z').getUTCDay());count=42;}else if(mode==='Week'){start=shiftDay(anchor,-new Date(anchor+'T12:00:00Z').getUTCDay());count=7;}
  for(let i=0;i<count;i++){const day=shiftDay(start,i),cell=el('section',undefined,{class:'calendar-day'+(day===nyDate()?' today':''),'aria-label':day});cell.append(el('h3',new Date(day+'T12:00:00Z').toLocaleDateString('en-US',{timeZone:'UTC',weekday:'short',month:'short',day:'numeric'})));
   for(const row of availability.filter(r=>!r.archived&&r.blockedDate===day))cell.append(el('p','Blocked · '+row.name,{class:'calendar-blocked'}));
   for(const row of projects.filter(r=>!r.archived&&r.eventDate===day))cell.append(button('Event · '+row.name,()=>viewRecord('projects',row)));
   for(const row of appointments.filter(r=>r.status!=='Cancelled'&&nyDate(r.startAt)===day).sort((a,b)=>a.startAt.localeCompare(b.startAt))){const time=new Date(row.startAt).toLocaleTimeString('en-US',{timeZone:'America/New_York',hour:'numeric',minute:'2-digit'});const entry=button(time+' · '+row.name+' · '+row.status,()=>viewRecord('appointments',row));entry.classList.add('calendar-entry');cell.append(entry);}
   if(count===1&&!cell.querySelector('button'))cell.append(el('p','No appointments or events on this day.',{class:'quiet'}));grid.append(cell);
  }
 }
 const previous=button('Previous',()=>{anchor=mode==='Month'?shiftMonth(anchor,-1):shiftDay(anchor,mode==='Week'?-7:-1);date.value=anchor;draw();}),next=button('Next',()=>{anchor=mode==='Month'?shiftMonth(anchor,1):shiftDay(anchor,mode==='Week'?7:1);date.value=anchor;draw();});controls.append(previous,button('Today',()=>{anchor=nyDate();date.value=anchor;draw();}),next,date);for(const view of ['Month','Week','Day'])controls.append(button(view,()=>{mode=view;draw();}));date.addEventListener('change',()=>{if(date.value){anchor=date.value;draw();}});main.append(controls,heading,grid);draw();
 const tabs=el('div',undefined,{class:'actions'}),body=el('section',undefined,{class:'panel'});for(const [kind,title]of [['appointments','Appointment list'],['appointment-types','Appointment types'],['availability','Hours / blocked dates']])tabs.append(button(title,async()=>{body.replaceChildren();body.append(button('New '+title,()=>edit(kind)));await collection(kind,body);}));main.append(tabs,body);await collection('appointments',body);panel('Scheduling rules','Reservations include buffers and reject overlaps. Blocked dates and configured availability hours are enforced. Event dates appear from projects. External calendar sync and public slots remain unavailable.');
}
function shiftMonth(day,count){const d=new Date(day.slice(0,8)+'01T12:00:00Z');d.setUTCMonth(d.getUTCMonth()+count);return d.toISOString().slice(0,10);}
async function portal(){
 header('Client Portal preview','Private admin-only preview. Client login and invitations are not enabled.');const kinds=['projects','contacts','services','packages','proposals','contracts','invoices','appointments','messages','files','tasks'];await Promise.all(kinds.map(k=>records(k)));const select=el('select',undefined,{'aria-label':'Preview a project'});select.append(el('option','Choose a project',{value:''}));for(const row of state.records.projects.filter(r=>!r.archived))select.append(el('option',(row.demo?'DEMO · ':'')+row.name,{value:row.id}));main.append(select);const body=el('section',undefined,{class:'portal-view'});main.append(body);
 select.addEventListener('change',()=>{body.replaceChildren();const project=state.records.projects.find(r=>r.id===select.value);if(!project)return;const contact=state.records.contacts.find(c=>c.id===project.contactId),pack=state.records.packages.find(p=>p.id===project.packageId);const hero=el('section',undefined,{class:'portal-hero'});hero.append(el('p','GIOLINA · PRIVATE ADMIN PREVIEW',{class:'eyebrow'}),el('h2','Welcome, '+(contact?.firstName||contact?.name||'client')),el('p','Your event, thoughtfully organized.'),el('p',[project.eventType,project.eventDate||'Date to be confirmed',project.venue||'Venue to be confirmed'].join(' · ')));body.append(hero);
 const grid=el('div',undefined,{class:'portal-panels'});function section(title){const panel=el('section',undefined,{class:'portal-panel'});panel.append(el('h3',title));grid.append(panel);return panel;}
 const info=section('Your event');for(const [title,value]of [['Event',project.name],['Location',project.location||project.venue||'To be confirmed'],['Stage',project.status],['Important dates',project.importantDates||'No additional dates recorded']])info.append(el('p',title+' · '+value));const servicePanel=section('Selected experience');if(pack)servicePanel.append(el('h4',pack.name),el('p',pack.clientDescription||pack.description||''));const serviceIds=[...new Set([...(pack?.serviceIds||[]),...(project.serviceIds||[])])];for(const id of serviceIds){const service=state.records.services.find(r=>r.id===id);if(service)servicePanel.append(el('p',service.name));}if(!pack&&!serviceIds.length)servicePanel.append(el('p','Your services will appear here after selection.'));
 for(const [kind,title]of [['proposals','Proposal'],['contracts','Contract'],['invoices','Invoices & payment plans'],['appointments','Appointments'],['messages','Messages'],['files','Files']]){const p=section(title),rows=state.records[kind].filter(r=>r.projectId===project.id&&!r.archived);for(const row of rows){p.append(el('h4',row.name));if(kind==='proposals')p.append(el('p',(row.status||'Draft')+' · '+money(row.totalCents)),button('Preview '+row.name,()=>viewRecord(kind,row)));else if(kind==='invoices')p.append(el('p','Planned total '+money(row.amountCents)+' · balance '+money(row.remainingCents??Math.max(0,(row.amountCents||0)-(row.paidCents||0)))+(row.dueAt?' · due '+row.dueAt:'')));else if(kind==='appointments')p.append(el('p',new Date(row.startAt).toLocaleString('en-US',{timeZone:'America/New_York'})+' ET · '+row.status));else if(kind==='messages')p.append(el('p',row.subject||''),el('p',row.body||''),el('small','Private draft; not sent'));else p.append(el('p',row.status||'Private record'));}if(!rows.length)p.append(el('p','No '+title.toLowerCase()+' recorded yet.',{class:'quiet'}));}
 const steps=section('Next steps');steps.append(el('p',project.nextSteps||'Next steps will be confirmed as your project progresses.'));for(const task of state.records.tasks.filter(t=>t.projectId===project.id&&!t.completed))steps.append(el('p',task.name+(task.dueAt?' · '+task.dueAt:'')));const delivery=section('Final delivery');if(project.deliveryUrl)delivery.append(el('a','Open your delivery',{href:project.deliveryUrl,target:'_blank',rel:'noopener noreferrer'}));else delivery.append(el('p','Your delivery link will appear here when ready.'));body.append(grid,el('p','Private preview only. No client access, invitations, signature requests or payment processing are active.',{class:'quiet'}));});
}
async function render(){
 const slug=location.pathname.startsWith('/portal')?'client-portal':location.pathname.split('/')[2]||'dashboard';
 document.querySelectorAll('nav a').forEach(a=>{if(a.getAttribute('href')==='/admin/'+(slug==='dashboard'?'':slug+'/'))a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
 if(slug==='dashboard')return dashboard();if(slug==='calendar')return calendar();if(slug==='client-portal')return portal();
 if(slug==='settings'){header('Settings','Private preview configuration. Secrets are managed outside the application.');panel('Signed in',state.meta.email);panel('Storage & security','Cloudflare Access verifies administrator identity; D1 stores organization-scoped records. No real clients have been imported. Client grants are reserved for Phase 2.');const lifecycle=panel('Project lifecycle','One status system across leads and projects.');const ol=el('ol',undefined,{class:'timeline'});for(const stage of stages)ol.append(el('li',stage));lifecycle.append(ol);panel('Services still to connect','Client authentication, private document storage, transactional email, payment processor and e-signature provider. None is enabled by this preview.');return;}
 if(slug==='services'){header('Services & Packages','Source-backed service versions. Missing prices remain unset; historical/clipped variants are flagged.',[button('Import supplied catalog',async()=>{const result=await request('seed','POST',{});delete state.records.services;notice(result.message);await render();},true),button('New service',()=>edit('services')),button('New package',()=>edit('packages'))]);const tabs=el('div',undefined,{class:'actions'}),body=el('section');for(const [kind,title]of [['services','Services'],['packages','Packages']])tabs.append(button(title,async()=>{body.replaceChildren();await collection(kind,body);}));main.append(tabs,body);await collection('services',body);return;}
 if(slug==='templates'){header('Email Templates','Editable workflow drafts. Variable previews use labeled demo values. Nothing is sent.',[button('Create workflow drafts',async()=>{const result=await request('setup-email-templates','POST',{});delete state.records.templates;notice(result.message);await render();},true),button('New template',()=>edit('templates'))]);const p=panel('Available variables','Use double braces: '+(state.meta.templateVariables||[]).map(v=>'{{'+v+'}}').join(', '));await collection('templates');return;}
 if(!state.meta.definitions[slug]){header('Page not found','Choose an area from the admin navigation.');return;}
 const foundation=['contracts','invoices','messages','files','automations'].includes(slug);const copy=foundation?'Foundation records only. No sending, signing, processing payments, uploads or automation execution.':slug==='proposals'?'Private proposal drafts with catalog snapshots, price overrides and calculated totals. No client sending.':slug==='templates'?'Reusable email drafts. Templates can be edited, duplicated and archived; sending is disabled.':'Private records with manual editing, archive history and explicit demo labels.';
 header(routes.find(r=>r[0]===slug)?.[1]||slug,copy,[button('New record',()=>edit(slug),true),...(slug==='proposals'?[button('Create DEMO presentations',async()=>{const result=await request('setup-demo-proposals','POST',{});state.records={};notice(result.message);await render();})]:[])]);await collection(slug);
}
async function init(){for(const [slug,title]of routes)document.querySelector('nav').append(el('a',title,{href:'/admin/'+(slug==='dashboard'?'':slug+'/')}));try{state.meta=await request('meta');await render();}catch(e){header('Workspace unavailable',e.message);notice(e.message);}}
init();
