import fontkit from '@pdf-lib/fontkit';
import {pdfFont} from './pdf-font.mjs';
import {PDFDocument,StandardFonts,rgb} from 'pdf-lib';
const money=value=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format((value||0)/100);
const printable=value=>String(value||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[\u2010-\u2015]/g,'-').replace(/[\u2018\u2019]/g,"'").replace(/[\u201c\u201d]/g,'"').replace(/[^\x20-\x7e\n]/g,' ');
export async function brandedPDF(doc){
 const pdf=await PDFDocument.create();pdf.registerFontkit(fontkit);pdf.setTitle('GioLina Films - '+doc.type);pdf.setAuthor('GioLina Films');const regular=await pdf.embedFont(pdfFont,{subset:true}),bold=regular,display=regular,teal=rgb(.07,.36,.38),ink=rgb(.13,.18,.19),muted=rgb(.36,.42,.43);let page,y;
 const newPage=()=>{page=pdf.addPage([612,792]);page.drawRectangle({x:0,y:770,width:612,height:22,color:teal});page.drawText('GioLina Films',{x:48,y:729,size:27,font:display,color:teal});page.drawText(doc.type.toUpperCase()+' / '+(doc.demo?'DEMO':'DRAFT'),{x:48,y:708,size:9,font:bold,color:muted});y=677;};newPage();
 function lines(text,size,font,width){const out=[];for(const para of printable(text).split('\n')){let line='';for(const word of para.split(/\s+/)){if(!word)continue;let parts=[word];if(font.widthOfTextAtSize(word,size)>width){parts=[];let part='';for(const ch of word){if(part&&font.widthOfTextAtSize(part+ch,size)>width){parts.push(part);part='';}part+=ch;}if(part)parts.push(part);}for(const part of parts){const candidate=line?line+' '+part:part;if(line&&font.widthOfTextAtSize(candidate,size)>width){out.push(line);line=part;}else line=candidate;}}out.push(line);}return out;}
 function text(value,{size=10,font=regular,color=ink,gap=5}={}){for(const line of lines(value,size,font,516)){if(y<size+72)newPage();page.drawText(line,{x:48,y,size,font,color});y-=size*1.45;}y-=gap;}
 const section=name=>{if(y<120)newPage();y-=8;text(name,{size:15,font:bold,color:teal,gap:9});};
 text(doc.clientNames,{size:22,font:display,gap:10});text([doc.eventType,doc.eventDate,doc.venue].filter(Boolean).join(' | '),{color:muted});if(doc.number)text('Reference: '+doc.number,{color:muted});if(doc.dueAt)text('Planned due date: '+doc.dueAt,{color:muted});
 if(doc.introduction){section('Your collection');text(doc.introduction);}
 section('Services & investment');for(const item of doc.items){text(item.name,{size:12,font:bold,gap:2});text((item.optional?'Optional add-on':item.selectionGroup?'Selectable offering':'Included service')+' | '+item.quantity+' x '+money(item.unitPriceCents)+' = '+money(item.quantity*item.unitPriceCents),{color:muted});if(item.description)text(item.description);if(item.details&&item.details!==item.description)text(item.details);if(item.inclusions)text(item.inclusions);if(item.coverageHours)text('Coverage: '+item.coverageHours+' hours');y-=6;}
 section(doc.type==='Proposal'?'Investment summary':'Draft invoice summary');if(doc.type==='Proposal'&&doc.items.some(i=>i.optional||i.selectionGroup))text('Offered amounts are options. This PDF does not record acceptance; final services and total require review.',{color:muted});text('Subtotal: '+money(doc.subtotalCents));if(doc.discountCents)text('Discount: -'+money(doc.discountCents));if(doc.taxCents)text('Tax: '+money(doc.taxCents));text((doc.type==='Proposal'?'Offered total':'Planned total')+': '+money(doc.totalCents),{size:16,font:bold,color:teal});
 if(doc.type==='Invoice Draft'){text('Manually recorded paid: '+money(doc.paidCents));text('Planned remaining balance: '+money(doc.remainingCents));if(doc.installments?.length){section('Planned payment schedule');for(const r of doc.installments)text([r.label,r.dueAt,money(r.amountCents)].filter(Boolean).join(' | '));}}
 text('Preview / draft only. No payment is requested or processed. No contract, signature or booking is created.',{size:9,color:muted});const pages=pdf.getPages();pages.forEach((p,i)=>{p.drawLine({start:{x:48,y:49},end:{x:564,y:49},thickness:.5,color:rgb(.8,.85,.85)});p.drawText('GIOLINA FILMS  |  '+(doc.demo?'DEMO / TEST':'DRAFT')+'  |  '+(i+1)+' / '+pages.length,{x:48,y:34,size:8,font:regular,color:muted});});return pdf.save();
}
export async function pdfResponse(doc,head=false){const bytes=await brandedPDF(doc);return new Response(head?null:bytes,{headers:{'Content-Type':'application/pdf','Content-Disposition':'attachment; filename="giolina-'+(doc.type==='Proposal'?'proposal':'invoice-draft')+'.pdf"','Cache-Control':'no-store, private','X-Robots-Tag':'noindex, nofollow, noarchive','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'}});}
