import {proposalTotals} from './model.mjs';
import {selectionTotals,defaultSelection} from './selection.mjs';
import {proposalSnapshot,proposalDocument} from './proposal-view.mjs';
import {catalogRecord} from './catalog.mjs';
import {proposalStyles,proposalClient} from './assets.mjs';
const ORG='giolina-preview';
export const proposalHeaders={'Cache-Control':'no-store, private','X-Robots-Tag':'noindex, nofollow, noarchive','Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff','X-Frame-Options':'SAMEORIGIN','Content-Security-Policy':"default-src 'none'; script-src 'self'; connect-src 'self'; style-src 'self'; img-src 'self'; frame-src https://player.vimeo.com https://mediazilla.com; frame-ancestors 'self'; base-uri 'none'; form-action 'self'"};
const response=(body,status=200,type='text/html;charset=utf-8')=>new Response(body,{status,headers:{...proposalHeaders,'Content-Type':type}});
const json=(body,status=200)=>response(JSON.stringify(body),status,'application/json');
export function proposalEnabled(request,env){const u=new URL(request.url);return env.CRM_STAGE==='preview'&&env.CRM_ORIGIN===u.origin&&u.hostname.endsWith('.workers.dev')&&!!env.CRM_DB;}
async function load(db,kind,id){const row=await db.prepare('SELECT * FROM '+(kind==='proposal-shares'?'proposal_shares':'records')+' WHERE organization_id=? AND kind=? AND id=?').bind(ORG,kind,id).first();return row?{...JSON.parse(row.data),id:row.id,version:row.version,createdAt:row.created_at,updatedAt:row.updated_at}:null;}
export async function buildSnapshot(db,id){const p=await load(db,'proposals',id);if(!p||p.archived)throw new Error('Proposal unavailable');const project=p.projectId?await load(db,'projects',p.projectId):{},lead=p.leadId?await load(db,'leads',p.leadId):{},contact=await load(db,'contacts',p.contactId||project?.contactId||lead?.contactId||'')||lead||{};if(project?.archived||contact?.archived)throw new Error('Linked record archived');const rows=await db.prepare("SELECT id,kind,data FROM records WHERE organization_id=? AND kind IN ('services','packages') LIMIT 1000").bind(ORG).all();const catalog=rows.results.map(r=>({...r.kind==='services'?catalogRecord({...JSON.parse(r.data),id:r.id}):{...JSON.parse(r.data),id:r.id},kind:r.kind}));const frozen=p.catalogSnapshot||catalog;for(const item of p.lineItems||[]){if(item.sourceKind!=='custom'){const source=frozen.find(r=>r.kind===item.sourceKind&&r.id===item.sourceId);if(!source||source.archived)throw new Error('Selected catalog item unavailable');for(const id of source.serviceIds||[]){if(!frozen.some(r=>r.kind==='services'&&r.id===id&&!r.archived))throw new Error('Package component unavailable');}}}return {proposal:p,snapshot:proposalSnapshot(p,{...lead,...project},contact,p.catalogSnapshot||catalog),demo:!!p.demo&&(!p.projectId||!!project?.demo)&&(!p.contactId||!!contact.demo)&&(!p.leadId||!!lead?.demo)};}
async function digest(token){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token))),n=>n.toString(16).padStart(2,'0')).join('');}
export async function ensureProposalSchema(db){await db.batch([db.prepare(`CREATE TABLE IF NOT EXISTS proposal_shares (organization_id TEXT NOT NULL,kind TEXT NOT NULL DEFAULT 'proposal-shares' CHECK(kind='proposal-shares'),id TEXT NOT NULL,data TEXT NOT NULL CHECK(json_valid(data)),version INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(organization_id,kind,id))`),db.prepare("CREATE INDEX IF NOT EXISTS proposal_shares_project ON proposal_shares(organization_id,json_extract(data,'$.proposalId'),created_at)")]);}
async function shares(db,id){const exists=await db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='proposal_shares'").first();if(!exists)return [];const r=await db.prepare("SELECT * FROM proposal_shares WHERE organization_id=? AND kind='proposal-shares' AND json_extract(data,'$.proposalId')=? ORDER BY created_at DESC LIMIT 100").bind(ORG,id).all();return r.results.map(r=>({...JSON.parse(r.data),id:r.id,createdAt:r.created_at}));}
function shareStatus(s){return s.disabled?'Disabled':Date.parse(s.expiresAt)<=Date.now()?'Expired':s.lastViewed?'Viewed':'Shared';}
export async function shareAPI(request,env,user,id){if(user.organizationId!==ORG||!proposalEnabled(request,env))return json({error:'Preview sharing unavailable'},404);const db=env.CRM_DB,p=await load(db,'proposals',id);if(!p)return json({error:'Not found'},404);if(request.method==='GET'){const rows=await shares(db,id),current=rows.find(s=>!s.disabled);return json({revision:p.version,createdAt:p.createdAt,updatedAt:p.updatedAt,current:current?{url:env.CRM_ORIGIN+'/proposal/'+current.token,revision:current.snapshot.revision,status:p.archived?'Archived':shareStatus(current),lastViewed:current.lastViewed||null,views:current.views||0,expiresAt:current.expiresAt}:null,history:rows.map(s=>({revision:s.snapshot.revision,createdAt:s.createdAt,status:shareStatus(s),lastViewed:s.lastViewed||null}))});}if(request.method!=='POST')return json({error:'Method not allowed'},405);const raw=await request.text();if(raw.length>2048)return json({error:'Request too large'},413);let input;try{input=JSON.parse(raw);}catch{return json({error:'Invalid JSON'},400);}if(!['create','regenerate','disable'].includes(input.action))return json({error:'Unknown sharing action'},400);if(input.version!==p.version)return json({error:'Proposal changed. Reload before sharing.'},409);const now=new Date().toISOString();let built;try{built=await buildSnapshot(db,id);if(!built.demo)throw new Error('This phase only permits sharing explicitly labeled DEMO proposals linked to DEMO records.');}catch(err){if(input.action!=='disable')return json({error:err.message},400);}if(input.action==='create'&&(await shares(db,id)).some(s=>!s.disabled&&Date.parse(s.expiresAt)>Date.now()))return json({error:'A link already exists. Copy it or regenerate explicitly.'},409);
await ensureProposalSchema(db);const guard=crypto.randomUUID(),ops=[db.prepare("INSERT INTO write_guards(token,valid) SELECT ?,COUNT(*) FROM records WHERE organization_id=? AND kind='proposals' AND id=? AND version=?").bind(guard,ORG,id,p.version),db.prepare("UPDATE proposal_shares SET data=json_set(data,'$.disabled',json('true')),updated_at=? WHERE organization_id=? AND kind='proposal-shares' AND json_extract(data,'$.proposalId')=?").bind(now,ORG,id)];let url=null;
if(input.action!=='disable'){const token=Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('');const hash=await digest(token),data={proposalId:id,token,snapshot:built.snapshot,disabled:false,expiresAt:new Date(Date.now()+30*86400000).toISOString(),views:0};if(JSON.stringify(data).length>750000)return json({error:'Presentation is too large to share'},400);ops.push(db.prepare("INSERT INTO proposal_shares(organization_id,kind,id,data,created_at,updated_at) VALUES(?,'proposal-shares',?,?,?,?)").bind(ORG,hash,JSON.stringify(data),now,now));url=env.CRM_ORIGIN+'/proposal/'+token;}
ops.push(db.prepare('INSERT INTO audit_events VALUES(?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),ORG,user.email,'proposal-link-'+input.action,'proposals',id,now,JSON.stringify({revision:p.version})),db.prepare('DELETE FROM write_guards WHERE token=?').bind(guard));try{await db.batch(ops);}catch(err){return json({error:'Proposal changed. Reload before sharing.'},409);}return json({url,message:input.action==='disable'?'All links disabled.':'Test link ready. Published snapshot is fixed until you regenerate; old links are revoked.'});}
export async function adminProposalPreview(request,env,id){try{const {snapshot}=await buildSnapshot(env.CRM_DB,id);return response(request.method==='HEAD'?null:proposalDocument(snapshot));}catch{return response('Proposal unavailable',404,'text/plain');}}
export async function adminPackagePreview(request,env,id){try{
 const pack=await load(env.CRM_DB,'packages',id);if(!pack||pack.archived)return response('Template unavailable',404,'text/plain');
 const rows=await env.CRM_DB.prepare("SELECT id,kind,data FROM records WHERE organization_id=? AND kind IN ('services','packages') LIMIT 1000").bind(ORG).all(),catalog=rows.results.map(r=>({...JSON.parse(r.data),id:r.id,kind:r.kind}));
 const items=[{name:pack.name,description:pack.clientDescription||pack.description||'',quantity:1,unitPriceCents:pack.priceCents,sourceKind:'packages',sourceId:id},...(pack.optionalServiceIds||[]).map(id=>{const source=catalog.find(r=>r.id===id&&r.kind==='services');if(!source||source.priceCents==null)throw new Error('Unpriced add-on');return {name:source.name,description:source.clientDescription||source.description||'',quantity:1,unitPriceCents:source.priceCents,sourceKind:'services',sourceId:id,optional:true};})];
 const snapshot=proposalSnapshot({name:pack.name,clientNames:'DEMO · Template preview',eventType:pack.catalogCategory?.startsWith('Sweet')?'Sweet Sixteen':'Wedding',demo:true,version:pack.version,lineItems:items,...proposalTotals(items)}, {}, {}, catalog);
 return response(request.method==='HEAD'?null:proposalDocument(snapshot));
}catch{return response('Template unavailable: confirm included service and add-on prices',400,'text/plain');}}
export async function publicProposal(request,env){const path=new URL(request.url).pathname;if(!/^\/(proposal|proposal-assets)(\/|$)/.test(path))return null;if(!proposalEnabled(request,env))return response('Not found',404,'text/plain');if(!['GET','HEAD','POST'].includes(request.method))return response('Method not allowed',405,'text/plain');if(path.startsWith('/proposal-assets/')&&!['GET','HEAD'].includes(request.method))return response('Method not allowed',405,'text/plain');if(path==='/proposal-assets/style.css')return response(request.method==='HEAD'?null:proposalStyles,200,'text/css');if(path==='/proposal-assets/viewer.js')return response(request.method==='HEAD'?null:proposalClient,200,'text/javascript');const match=path.match(/^\/proposal\/([a-f0-9]{64})(\/selection)?$/);if(!match)return response('Proposal unavailable',404,'text/plain');try{const s=await load(env.CRM_DB,'proposal-shares',await digest(match[1]));if(!s||s.disabled||Date.parse(s.expiresAt)<=Date.now())return response('Proposal unavailable',404,'text/plain');const p=await load(env.CRM_DB,'proposals',s.proposalId);if(!p||p.archived||p.status==='Expired'||p.status==='Declined')return response('Proposal unavailable',404,'text/plain');if(match[2]){
 if(!s.snapshot.demo||!s.snapshot.clientSelection)return json({error:'DEMO selection unavailable'},404);
 const current=s.selection||selectionTotals(s.snapshot,defaultSelection(s.snapshot.items));
 if(request.method==='GET')return json({...current,version:s.version});
 if(request.method!=='POST')return json({error:'Method not allowed'},405);
 if(request.headers.get('Origin')!==env.CRM_ORIGIN||!request.headers.get('Content-Type')?.startsWith('application/json')||request.headers.get('X-GioLina-Request')!=='demo-selection')return json({error:'Invalid selection origin'},403);
 const reader=request.body?.getReader();if(!reader)return json({error:'Invalid selection'},400);let parts=[],size=0;while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>4096){await reader.cancel();return json({error:'Selection too large'},413);}parts.push(value);}const bytes=new Uint8Array(size);let offset=0;for(const part of parts){bytes.set(part,offset);offset+=part.length;}
 let input,totals;try{input=JSON.parse(new TextDecoder().decode(bytes));if(Object.keys(input).some(k=>!['selected','version','preview'].includes(k)))throw new Error('Only offered-item indices are accepted');totals=selectionTotals(s.snapshot,input.selected);}catch(err){return json({error:err.message},400);}
 if(input.version!==s.version)return json({error:'Selections changed in another window. Reload and try again.'},409);
 if(input.preview===true)return json({...totals,version:s.version});
 const now=new Date().toISOString(),guard=crypto.randomUUID();try{await env.CRM_DB.batch([
 env.CRM_DB.prepare("INSERT INTO write_guards(token,valid) SELECT ?,COUNT(*) FROM proposal_shares WHERE organization_id=? AND id=? AND version=? AND json_extract(data,'$.disabled')=0 AND json_extract(data,'$.expiresAt')>?").bind(guard,ORG,s.id,input.version,now),
 env.CRM_DB.prepare("UPDATE proposal_shares SET data=json_set(data,'$.selection',json(?)),version=version+1,updated_at=? WHERE organization_id=? AND id=? AND version=?").bind(JSON.stringify(totals),now,ORG,s.id,input.version),
 env.CRM_DB.prepare('INSERT INTO audit_events VALUES(?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),ORG,'DEMO link holder','demo-selection-changed','proposals',s.proposalId,now,JSON.stringify({revision:s.snapshot.revision,selected:totals.selected,totalCents:totals.totalCents})),
 env.CRM_DB.prepare('DELETE FROM write_guards WHERE token=?').bind(guard)]);}catch{return json({error:'Link or selections changed. Reload before selecting.'},409);}
 return json({...totals,version:s.version+1,message:'DEMO selections saved. No acceptance, contract, invoice or payment was created.'});
 }
 if(request.method==='POST')return response('Method not allowed',405,'text/plain');
 if(request.method==='GET'){const now=new Date().toISOString();await env.CRM_DB.batch([env.CRM_DB.prepare("INSERT INTO audit_events SELECT ?,?,'DEMO link viewer','demo-proposal-viewed','proposals',?,?,? FROM proposal_shares WHERE organization_id=? AND id=? AND COALESCE(json_extract(data,'$.views'),0)=0 AND json_extract(data,'$.disabled')=0").bind(crypto.randomUUID(),ORG,s.proposalId,now,JSON.stringify({revision:s.snapshot.revision}),ORG,s.id),env.CRM_DB.prepare("UPDATE proposal_shares SET data=json_set(data,'$.lastViewed',?,'$.views',COALESCE(json_extract(data,'$.views'),0)+1) WHERE organization_id=? AND kind='proposal-shares' AND id=? AND json_extract(data,'$.disabled')=0").bind(now,ORG,s.id)]);}return response(request.method==='HEAD'?null:proposalDocument(s.snapshot));}catch{return response('Proposal unavailable',404,'text/plain');}}
