import {catalogRecord} from './catalog.mjs';
import {validate} from './model.mjs';
const specs=[
 {id:'wedding-cinema',title:'Wedding — Cinematography',names:'Alex + Jordan · DEMO',eventType:'Wedding',service:'hb-0-01',optional:'hb-0-04',headline:'Your day, in motion',intro:'The voices, the anticipation, the way it all felt. This demonstration collection brings your wedding story together through GioLina cinematography.',copy:'A cinematic feature film collection with up to eight hours of coverage. Explore the full service details below.'},
 {id:'wedding-photo',title:'Wedding — Photography',names:'Jamie + Taylor · DEMO',eventType:'Wedding',service:'hb-0-06',optional:'hb-0-09',headline:'A day worth holding onto',intro:'Quiet gestures. Unscripted joy. The people who make it yours. A photography collection, thoughtfully presented for your wedding.',copy:'The source-backed Premier eight-hour wedding photography collection. Full inclusions are preserved below.'},
 {id:'sweet-sixteen',title:'Sweet Sixteen',names:'Avery · DEMO',eventType:'Sweet Sixteen',service:'hb-1-17',optional:'hb-1-19',headline:'One unforgettable celebration',intro:'A little anticipation, a lot of energy, and a celebration that is entirely yours. Explore this Sweet Sixteen film collection.',copy:'Six-hour Feature Film & Edit Services from the 2024 Sweet Sixteen source. Historical pricing is shown for demonstration; confirm current pricing before use.'},
 {id:'corporate',title:'Event / Corporate',names:'Your team · DEMO',eventType:'Corporate',service:'hb-2-24',headline:'A gathering, remembered',intro:'A clear, considered approach to documenting an occasion. This demonstration uses a preserved historical corporate service—not a newly quoted rate.',copy:'Five-hour corporate video package. Historical December 8, 2025 service and price retained for evaluation only.'}
];
export async function seedDemoProposals(db,org,user){const now=new Date().toISOString(),ops=[];for(const spec of specs){const contactId='demo-presentation-'+spec.id,projectId=contactId,proposalId=contactId;const rows=[];for(const id of [spec.service,spec.optional].filter(Boolean)){const r=await db.prepare("SELECT id,data FROM records WHERE organization_id=? AND kind='services' AND id=?").bind(org,id).first();if(!r)throw new Error('Import the supplied catalog first.');const source=catalogRecord({...JSON.parse(r.data),id:r.id});if(source.archived||source.priceCents==null)throw new Error('Demo source must be active and priced.');rows.push(source);}
const contact={name:spec.names,email:'demo-'+spec.id+'@example.test',demo:true},project={name:'DEMO — '+spec.title,contactId,eventType:spec.eventType,status:'Proposal',eventDate:'2027-06-12',venue:'Demonstration venue',demo:true},proposal=validate('proposals',{name:'DEMO — '+spec.title,projectId,contactId,eventType:spec.eventType,clientNames:spec.names,introduction:spec.intro,status:'Draft',demo:true,sectionOrder:['introduction','services','investment'],discountCents:0,lineItems:rows.map((r,i)=>({name:i?r.name:spec.headline,description:i?r.description:spec.copy,sourceKind:'services',sourceId:r.id,quantity:1,unitPriceCents:r.priceCents,optional:i>0}))});
for(const [kind,id,data]of [['contacts',contactId,contact],['projects',projectId,project],['proposals',proposalId,proposal]])ops.push(db.prepare('INSERT OR IGNORE INTO records(organization_id,kind,id,data,created_at,updated_at) VALUES(?,?,?,?,?,?)').bind(org,kind,id,JSON.stringify(data),now,now));}
ops.push(db.prepare('INSERT INTO audit_events VALUES(?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),org,user.email,'demo-presentations-created','proposals','demo-presentations',now,'{}'));await db.batch(ops);return {message:'Four labeled DEMO presentations ready. Existing demo edits preserved.'};}
